// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  exceptionsql
//
// orm — https://github.com/the-protobuf-project/orm

package exceptionsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one ScheduleExceptions row.
type CreateInput struct {
	// AvailabilityExceptionId sets the "availabilityExceptionId" column (required).
	AvailabilityExceptionId string `json:"availabilityExceptionId"`
	// AvailabilityExceptionName sets the "availabilityExceptionName" column (required).
	AvailabilityExceptionName string `json:"availabilityExceptionName"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// ScheduleId sets the "scheduleId" column (required).
	ScheduleId string `json:"scheduleId"`
}

// UpdateInput holds the fields to change on a ScheduleExceptions row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'availability_exception_id' column in the 'schedule_exceptions' collection.
	AvailabilityExceptionId graphql.Nullable[string] `json:"availabilityExceptionId"`
	// Update the 'availability_exception_name' column in the 'schedule_exceptions' collection.
	AvailabilityExceptionName graphql.Nullable[string] `json:"availabilityExceptionName"`
	// Update the 'id' column in the 'schedule_exceptions' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'schedule_id' column in the 'schedule_exceptions' collection.
	ScheduleId graphql.Nullable[string] `json:"scheduleId"`
}
