// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  exceptionsql
//
// orm — https://github.com/the-protobuf-project/orm

package exceptionsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleExceptionsByIdResponse = schemaql.DeleteScheduleExceptionsByIdResponse
type InsertScheduleExceptionsResponse = schemaql.InsertScheduleExceptionsResponse
type ScheduleExceptions = schemaql.ScheduleExceptions
type ScheduleExceptionsAggExp = schemaql.ScheduleExceptionsAggExp
type UpdateScheduleExceptionsByIdResponse = schemaql.UpdateScheduleExceptionsByIdResponse
