// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitslinkql
//
// orm — https://github.com/the-protobuf-project/orm

package unitslinkql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyUnitsLinkByIdResponse = schemaql.DeletePropertyUnitsLinkByIdResponse
type InsertPropertyUnitsLinkResponse = schemaql.InsertPropertyUnitsLinkResponse
type PropertyUnitsLink = schemaql.PropertyUnitsLink
type PropertyUnitsLinkAggExp = schemaql.PropertyUnitsLinkAggExp
type UpdatePropertyUnitsLinkByIdResponse = schemaql.UpdatePropertyUnitsLinkByIdResponse
