// Code generated by protoc-gen-orm. DO NOT EDIT.

package buffersettingsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleBufferSettingsByIdResponse = schemaql.DeleteScheduleBufferSettingsByIdResponse
type InsertScheduleBufferSettingsResponse = schemaql.InsertScheduleBufferSettingsResponse
type ScheduleBufferSettings = schemaql.ScheduleBufferSettings
type ScheduleBufferSettingsAggExp = schemaql.ScheduleBufferSettingsAggExp
type UpdateScheduleBufferSettingsByIdResponse = schemaql.UpdateScheduleBufferSettingsByIdResponse
