// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  pricecomponentsql
//
// orm — https://github.com/the-protobuf-project/orm

package pricecomponentsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one SharedPriceComponents row.
type CreateInput struct {
	// AmountId sets the "amountId" column; the zero value is omitted (column default / NULL).
	AmountId string `json:"amountId,omitzero"`
	// BookingId sets the "bookingId" column (required).
	BookingId string `json:"bookingId"`
	// Code sets the "code" column; the zero value is omitted (column default / NULL).
	Code string `json:"code,omitzero"`
	// DisplayName sets the "displayName" column; the zero value is omitted (column default / NULL).
	DisplayName string `json:"displayName,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Type sets the "type" column; the zero value is omitted (column default / NULL).
	Type string `json:"type,omitzero"`
}

// UpdateInput holds the fields to change on a SharedPriceComponents row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'amount_id' column in the 'shared_price_components' collection.
	AmountId graphql.Nullable[string] `json:"amountId"`
	// Update the 'booking_id' column in the 'shared_price_components' collection.
	BookingId graphql.Nullable[string] `json:"bookingId"`
	// Update the 'code' column in the 'shared_price_components' collection.
	Code graphql.Nullable[string] `json:"code"`
	// Update the 'display_name' column in the 'shared_price_components' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'id' column in the 'shared_price_components' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'type' column in the 'shared_price_components' collection.
	Type graphql.Nullable[string] `json:"type"`
}
