// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  postaladdressql
//
// orm — https://github.com/the-protobuf-project/orm

package postaladdressql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/commonql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type CommonPostalAddress = schemaql.CommonPostalAddress
type CommonPostalAddressAggExp = schemaql.CommonPostalAddressAggExp
type DeleteCommonPostalAddressByIdResponse = schemaql.DeleteCommonPostalAddressByIdResponse
type InsertCommonPostalAddressResponse = schemaql.InsertCommonPostalAddressResponse
type UpdateCommonPostalAddressByIdResponse = schemaql.UpdateCommonPostalAddressByIdResponse
