// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitmediasql
//
// orm — https://github.com/the-protobuf-project/orm

package unitmediasql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PropertyUnitMedias query operations.
type QueryHandler interface {
	// List runs the "propertyUnitMedias" query.
	List(ctx context.Context, req ...*ListRequest) ([]PropertyUnitMedias, error)
	// Find runs the "propertyUnitMedias" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*PropertyUnitMedias, error)
	// Aggregate runs the "propertyUnitMediasAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*PropertyUnitMediasAggExp, error)
	// Get runs the "propertyUnitMediasById" query.
	Get(ctx context.Context, id string) (*PropertyUnitMedias, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PropertyUnitMedias mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePropertyUnitMediasById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeletePropertyUnitMediasByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeletePropertyUnitMediasByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPropertyUnitMedias" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertPropertyUnitMediasResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertPropertyUnitMediasResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePropertyUnitMediasById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdatePropertyUnitMediasByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdatePropertyUnitMediasByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdatePropertyUnitMediasByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PropertyUnitMedias subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "propertyUnitMedias" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "propertyUnitMediasAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "propertyUnitMediasById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[PropertyUnitMedias] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertPropertyUnitMediasResponse, UpdatePropertyUnitMediasByIdResponse, DeletePropertyUnitMediasByIdResponse] = (*mutationHandler)(nil)
