// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitmediasql
//
// orm — https://github.com/the-protobuf-project/orm

package unitmediasql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyUnitMedias row.
type CreateInput struct {
	// Description sets the "description" column; the zero value is omitted (column default / NULL).
	Description string `json:"description,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// MimeType sets the "mimeType" column; the zero value is omitted (column default / NULL).
	MimeType string `json:"mimeType,omitzero"`
	// Primary sets the "primary" column; the zero value is omitted (column default / NULL).
	Primary bool `json:"primary,omitzero"`
	// SortOrder sets the "sortOrder" column; the zero value is omitted (column default / NULL).
	SortOrder int32 `json:"sortOrder,omitzero"`
	// Title sets the "title" column; the zero value is omitted (column default / NULL).
	Title string `json:"title,omitzero"`
	// Type sets the "type" column; the zero value is omitted (column default / NULL).
	Type string `json:"type,omitzero"`
	// UnitId sets the "unitId" column (required).
	UnitId string `json:"unitId"`
	// Uri sets the "uri" column (required).
	Uri string `json:"uri"`
}

// UpdateInput holds the fields to change on a PropertyUnitMedias row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'description' column in the 'property_unit_medias' collection.
	Description graphql.Nullable[string] `json:"description"`
	// Update the 'id' column in the 'property_unit_medias' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'mime_type' column in the 'property_unit_medias' collection.
	MimeType graphql.Nullable[string] `json:"mimeType"`
	// Update the 'primary' column in the 'property_unit_medias' collection.
	Primary graphql.Nullable[bool] `json:"primary"`
	// Update the 'sort_order' column in the 'property_unit_medias' collection.
	SortOrder graphql.Nullable[int32] `json:"sortOrder"`
	// Update the 'title' column in the 'property_unit_medias' collection.
	Title graphql.Nullable[string] `json:"title"`
	// Update the 'type' column in the 'property_unit_medias' collection.
	Type graphql.Nullable[string] `json:"type"`
	// Update the 'unit_id' column in the 'property_unit_medias' collection.
	UnitId graphql.Nullable[string] `json:"unitId"`
	// Update the 'uri' column in the 'property_unit_medias' collection.
	Uri graphql.Nullable[string] `json:"uri"`
}
