// Code generated by protoc-gen-orm. DO NOT EDIT.

package taxesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyTaxes row.
type CreateInput struct {
	Code        string             `json:"code"`
	DisplayName string             `json:"displayName,omitzero"`
	Id          string             `json:"id"`
	Percent     graphql.Bigdecimal `json:"percent"`
	UnitId      string             `json:"unitId"`
}

// UpdateInput holds the fields to change on a PropertyTaxes row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'code' column in the 'property_taxes' collection.
	Code graphql.Nullable[string] `json:"code"`
	// Update the 'display_name' column in the 'property_taxes' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'id' column in the 'property_taxes' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'percent' column in the 'property_taxes' collection.
	Percent graphql.Nullable[graphql.Bigdecimal] `json:"percent"`
	// Update the 'unit_id' column in the 'property_taxes' collection.
	UnitId graphql.Nullable[string] `json:"unitId"`
}
