// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  taxesql
//
// orm — https://github.com/the-protobuf-project/orm

package taxesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type mutationHandler struct {
	gql *runtime.GraphQLClient
}

func (h *mutationHandler) Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeletePropertyTaxesByIdResponse, error) {
	var out DeletePropertyTaxesByIdResponse
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "PropertyTaxesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "deletePropertyTaxesById", &out, args)
	return out, res.Error
}

// DeleteOp returns Delete as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) DeleteOp(keyId string, result *DeletePropertyTaxesByIdResponse, req ...*DeleteRequest) runtime.BatchOp {
	var r DeleteRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "PropertyTaxesBoolExp")
	}
	return runtime.BatchOp{Field: "deletePropertyTaxesById", Args: args, Result: result}
}

func (h *mutationHandler) Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertPropertyTaxesResponse, error) {
	var out InsertPropertyTaxesResponse
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertPropertyTaxesObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "PropertyTaxesBoolExp")
	}
	res := <-h.gql.MutateFields(ctx, "insertPropertyTaxes", &out, args)
	return out, res.Error
}

// CreateOp returns Create as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) CreateOp(obj CreateInput, result *InsertPropertyTaxesResponse, req ...*CreateRequest) runtime.BatchOp {
	var r CreateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["objects"] = graphql.Var([]CreateInput{obj}, "[InsertPropertyTaxesObjectInput!]")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "PropertyTaxesBoolExp")
	}
	return runtime.BatchOp{Field: "insertPropertyTaxes", Args: args, Result: result}
}

func (h *mutationHandler) Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdatePropertyTaxesByIdResponse, error) {
	var out UpdatePropertyTaxesByIdResponse
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "PropertyTaxesBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "PropertyTaxesBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdatePropertyTaxesByIdUpdateColumnsInput")
	res := <-h.gql.MutateFields(ctx, "updatePropertyTaxesById", &out, args)
	return out, res.Error
}

// UpdateIfMatch runs Update guarded by match, an optimistic-concurrency precondition
// (e.g. Etag.Eq(prev)). It returns graphql.ErrConflict when no row matched the precondition.
func (h *mutationHandler) UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdatePropertyTaxesByIdResponse, error) {
	resp, err := h.Update(ctx, keyId, patch, Update().PreCheck(match))
	if err != nil {
		return resp, err
	}
	if resp.AffectedRows == 0 {
		return resp, graphql.ErrConflict
	}
	return resp, nil
}

// UpdateOp returns Update as a deferred mutation for a Tx batch; result is filled when the
// batch commits. Queue it with svc.Mutation.Tx().Add(...) to commit several mutations atomically.
func (h *mutationHandler) UpdateOp(keyId string, patch UpdateInput, result *UpdatePropertyTaxesByIdResponse, req ...*UpdateRequest) runtime.BatchOp {
	var r UpdateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	args["keyId"] = graphql.Var(keyId, "String1")
	if !graphql.IsOmitted(r.GetPostCheck()) {
		args["postCheck"] = graphql.VarPtr(r.GetPostCheck(), "PropertyTaxesBoolExp")
	}
	if !graphql.IsOmitted(r.GetPreCheck()) {
		args["preCheck"] = graphql.VarPtr(r.GetPreCheck(), "PropertyTaxesBoolExp")
	}
	args["updateColumns"] = graphql.Var(graphql.SetColumns(patch), "UpdatePropertyTaxesByIdUpdateColumnsInput")
	return runtime.BatchOp{Field: "updatePropertyTaxesById", Args: args, Result: result}
}
