// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  taxesql
//
// orm — https://github.com/the-protobuf-project/orm

package taxesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, req ...*ListRequest) ([]PropertyTaxes, error) {
	var out []PropertyTaxes
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		args["limit"] = graphql.VarPtr(r.GetLimit(), "Int")
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[PropertyTaxesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "PropertyTaxesBoolExp")
	}
	res := <-h.gql.QueryFields(ctx, "propertyTaxes", &out, args)
	return out, res.Error
}

func (h *queryHandler) Find(ctx context.Context, req ...*ListRequest) (*PropertyTaxes, error) {
	var out []PropertyTaxes
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[PropertyTaxesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "PropertyTaxesBoolExp")
	}
	args["limit"] = graphql.VarPtr(1, "Int")
	res := <-h.gql.QueryFields(ctx, "propertyTaxes", &out, args)
	if res.Error != nil {
		return nil, res.Error
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

func (h *queryHandler) Aggregate(ctx context.Context, req ...*AggregateRequest) (*PropertyTaxesAggExp, error) {
	var out *PropertyTaxesAggExp
	var r AggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		filterInput["limit"] = r.GetLimit()
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		filterInput["offset"] = r.GetOffset()
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		filterInput["order_by"] = r.GetOrderBy()
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		filterInput["where"] = r.GetWhere()
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "PropertyTaxesFilterInput")
	}
	res := <-h.gql.QueryFields(ctx, "propertyTaxesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) Get(ctx context.Context, id string) (*PropertyTaxes, error) {
	var out *PropertyTaxes
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	res := <-h.gql.QueryFields(ctx, "propertyTaxesById", &out, args)
	return out, res.Error
}
