// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  resourceql
//
// orm — https://github.com/the-protobuf-project/orm

package resourceql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleResourceByIdResponse = schemaql.DeleteScheduleResourceByIdResponse
type InsertScheduleResourceResponse = schemaql.InsertScheduleResourceResponse
type ScheduleResource = schemaql.ScheduleResource
type ScheduleResourceAggExp = schemaql.ScheduleResourceAggExp
type UpdateScheduleResourceByIdResponse = schemaql.UpdateScheduleResourceByIdResponse
