// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
// source: freebusy/property/v1/property.proto
//
// database: freebusy
// schema:   property
//
// orm — https://github.com/the-protobuf-project/orm

package property

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// LosDiscountStore provides typed CRUD access to LosDiscount records.
// A discount applied to a NIGHTLY subtotal once the stay reaches a minimum length. Exactly one of percent_off or amount_off is set.
type LosDiscountStore struct{ DB *gorm.DB }

// Compile-time proof that LosDiscountStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[LosDiscount] = (*LosDiscountStore)(nil)

// NewLosDiscountStore returns a LosDiscountStore backed by db.
func NewLosDiscountStore(db *gorm.DB) *LosDiscountStore { return &LosDiscountStore{DB: db} }

// Create inserts m.
func (s *LosDiscountStore) Create(ctx context.Context, m *LosDiscount) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the LosDiscount records matching opts.
func (s *LosDiscountStore) List(ctx context.Context, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of LosDiscount records matching opts.Where
// (pagination and ordering are ignored).
func (s *LosDiscountStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&LosDiscount{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *LosDiscountStore) Update(ctx context.Context, m *LosDiscount) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the LosDiscount with the given primary key.
func (s *LosDiscountStore) GetByID(ctx context.Context, id string) (*LosDiscount, error) {
	var m LosDiscount
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the LosDiscount with the given primary key.
func (s *LosDiscountStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&LosDiscount{}, "id = ?", id).Error
}

// ListByUnitID returns the LosDiscount records whose unit_id matches id, with opts applied.
func (s *LosDiscountStore) ListByUnitID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	q := opts.Apply(s.DB.WithContext(ctx).Where("unit_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAmountOffID returns the LosDiscount records whose amount_off_id matches id, with opts applied.
func (s *LosDiscountStore) ListByAmountOffID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	q := opts.Apply(s.DB.WithContext(ctx).Where("amount_off_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
