// Code generated by protoc-gen-orm. DO NOT EDIT.

package resourceql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeResourceByIdResponse = schemaql.DeletePromocodeResourceByIdResponse
type InsertPromocodeResourceResponse = schemaql.InsertPromocodeResourceResponse
type PromocodeResource = schemaql.PromocodeResource
type PromocodeResourceAggExp = schemaql.PromocodeResourceAggExp
type UpdatePromocodeResourceByIdResponse = schemaql.UpdatePromocodeResourceByIdResponse
