// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// DiscountStore provides typed CRUD access to Discount records.
// Discount describes how a promo code reduces a subtotal. Nested value object → belongs-to child table promocode.discounts (FK discount_id on promo_codes). Exactly one of percent_off / amount_off is set; the oneof case is the discriminator, so no separate type enum is needed.
type DiscountStore struct{ DB *gorm.DB }

// Compile-time proof that DiscountStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Discount] = (*DiscountStore)(nil)

// NewDiscountStore returns a DiscountStore backed by db.
func NewDiscountStore(db *gorm.DB) *DiscountStore { return &DiscountStore{DB: db} }

// Create inserts m.
func (s *DiscountStore) Create(ctx context.Context, m *Discount) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Discount records matching opts.
func (s *DiscountStore) List(ctx context.Context, opts gormx.ListOptions) ([]Discount, error) {
	var out []Discount
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Discount records matching opts.Where
// (pagination and ordering are ignored).
func (s *DiscountStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&Discount{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *DiscountStore) Update(ctx context.Context, m *Discount) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Discount with the given primary key.
func (s *DiscountStore) GetByID(ctx context.Context, id string) (*Discount, error) {
	var m Discount
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Discount with the given primary key.
func (s *DiscountStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Discount{}, "id = ?", id).Error
}

// ListByAmountOffID returns the Discount records whose amount_off_id matches id, with opts applied.
func (s *DiscountStore) ListByAmountOffID(ctx context.Context, id string, opts gormx.ListOptions) ([]Discount, error) {
	var out []Discount
	q := opts.Apply(s.DB.WithContext(ctx).Where("amount_off_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
