// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.2.1
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// RedemptionWindowStore provides typed CRUD access to RedemptionWindow records.
// RedemptionWindow bounds when a code can be redeemed; an unset bound is open-ended. Nested value object → belongs-to promocode.redemption_windows.
type RedemptionWindowStore struct{ DB *gorm.DB }

// Compile-time proof that RedemptionWindowStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[RedemptionWindow] = (*RedemptionWindowStore)(nil)

// NewRedemptionWindowStore returns a RedemptionWindowStore backed by db.
func NewRedemptionWindowStore(db *gorm.DB) *RedemptionWindowStore {
	return &RedemptionWindowStore{DB: db}
}

// Create inserts m.
func (s *RedemptionWindowStore) Create(ctx context.Context, m *RedemptionWindow) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the RedemptionWindow records matching opts.
func (s *RedemptionWindowStore) List(ctx context.Context, opts gormx.ListOptions) ([]RedemptionWindow, error) {
	var out []RedemptionWindow
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of RedemptionWindow records matching opts.Where
// (pagination and ordering are ignored).
func (s *RedemptionWindowStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&RedemptionWindow{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *RedemptionWindowStore) Update(ctx context.Context, m *RedemptionWindow) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the RedemptionWindow with the given primary key.
func (s *RedemptionWindowStore) GetByID(ctx context.Context, id string) (*RedemptionWindow, error) {
	var m RedemptionWindow
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the RedemptionWindow with the given primary key.
func (s *RedemptionWindowStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&RedemptionWindow{}, "id = ?", id).Error
}
