// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.3.1
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// RedemptionStore provides typed CRUD access to Redemption records.
// Redemption is a single use of a promo code, modeled as a sub-resource of PromoCode rather than an inline list — so it has its own name/lifecycle and is listed with paging (ListRedemptions). The {promo_code} parent segment generates the promo_code_id FK back to the owning code (1:n into promocode.redemptions); amount_applied is the shared google.type.Money in common.moneys. Redemptions are created during CreateBooking, never directly.
type RedemptionStore struct{ DB *gorm.DB }

// Compile-time proof that RedemptionStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Redemption] = (*RedemptionStore)(nil)

// NewRedemptionStore returns a RedemptionStore backed by db.
func NewRedemptionStore(db *gorm.DB) *RedemptionStore { return &RedemptionStore{DB: db} }

// Create inserts m.
func (s *RedemptionStore) Create(ctx context.Context, m *Redemption) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Redemption records matching opts.
func (s *RedemptionStore) List(ctx context.Context, opts gormx.ListOptions) ([]Redemption, error) {
	var out []Redemption
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Redemption records matching opts.Where
// (pagination and ordering are ignored).
func (s *RedemptionStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&Redemption{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *RedemptionStore) Update(ctx context.Context, m *Redemption) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Redemption with the given primary key.
func (s *RedemptionStore) GetByID(ctx context.Context, id string) (*Redemption, error) {
	var m Redemption
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Redemption with the given primary key.
func (s *RedemptionStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Redemption{}, "id = ?", id).Error
}

// GetByName fetches the Redemption with the given name (a unique column).
func (s *RedemptionStore) GetByName(ctx context.Context, v string) (*Redemption, error) {
	var m Redemption
	if err := s.DB.WithContext(ctx).First(&m, "name = ?", v).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByCustomerID returns the Redemption records whose customer matches id, with opts applied.
func (s *RedemptionStore) ListByCustomerID(ctx context.Context, id string, opts gormx.ListOptions) ([]Redemption, error) {
	var out []Redemption
	q := opts.Apply(s.DB.WithContext(ctx).Where("customer = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByBookingID returns the Redemption records whose booking matches id, with opts applied.
func (s *RedemptionStore) ListByBookingID(ctx context.Context, id string, opts gormx.ListOptions) ([]Redemption, error) {
	var out []Redemption
	q := opts.Apply(s.DB.WithContext(ctx).Where("booking = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByPromoCodeID returns the Redemption records whose promo_code_id matches id, with opts applied.
func (s *RedemptionStore) ListByPromoCodeID(ctx context.Context, id string, opts gormx.ListOptions) ([]Redemption, error) {
	var out []Redemption
	q := opts.Apply(s.DB.WithContext(ctx).Where("promo_code_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAmountAppliedID returns the Redemption records whose amount_applied_id matches id, with opts applied.
func (s *RedemptionStore) ListByAmountAppliedID(ctx context.Context, id string, opts gormx.ListOptions) ([]Redemption, error) {
	var out []Redemption
	q := opts.Apply(s.DB.WithContext(ctx).Where("amount_applied_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
