// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  usagelimitsql
//
// orm — https://github.com/the-protobuf-project/orm

package usagelimitsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeUsageLimitsByIdResponse = schemaql.DeletePromocodeUsageLimitsByIdResponse
type InsertPromocodeUsageLimitsResponse = schemaql.InsertPromocodeUsageLimitsResponse
type PromocodeUsageLimits = schemaql.PromocodeUsageLimits
type PromocodeUsageLimitsAggExp = schemaql.PromocodeUsageLimitsAggExp
type UpdatePromocodeUsageLimitsByIdResponse = schemaql.UpdatePromocodeUsageLimitsByIdResponse
