// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
//
// orm — https://github.com/the-protobuf-project/orm

package schedule

import (
	"context"
	"fmt"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/schedule"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/shared"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/schedule/v1/schedulepbv1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormAvailabilityExceptionRepository is the GORM adapter of AvailabilityExceptionRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormAvailabilityExceptionRepository struct {
	DB    *gorm.DB
	Hooks AvailabilityExceptionHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormAvailabilityExceptionRepository returns the GORM adapter bound to db.
func NewGormAvailabilityExceptionRepository(db *gorm.DB) *GormAvailabilityExceptionRepository {
	return &GormAvailabilityExceptionRepository{DB: db}
}

// Create persists in under parent and returns the stored record.
func (r *GormAvailabilityExceptionRepository) Create(ctx context.Context, parent string, in *schedulepbv1.AvailabilityException) (*schedulepbv1.AvailabilityException, error) {
	parentIDs, err := repox.SplitName(parent, "properties", "units")
	if err != nil {
		return nil, err
	}
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "properties", "units", "availabilityExceptions")
		if err != nil {
			return nil, err
		}
		for i := range parentIDs {
			if ids[i] != parentIDs[i] {
				return nil, fmt.Errorf("%w: name %q is not under parent %q", repox.ErrInvalidArgument, in.GetName(), parent)
			}
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*schedulepbv1.AvailabilityException)
	in.Name = FormatAvailabilityExceptionName(parentIDs[0], parentIDs[1], id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := schedule.AvailabilityExceptionFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	m.PropertyID = parentIDs[0]
	m.UnitID = parentIDs[1]
	if err := r.DB.Transaction(func(tx *gorm.DB) error {
		if v := in.GetWindow(); v != nil {
			vo := shared.TimeWindowFromProto(v)
			vo.ID = repox.NewULID()
			if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
				return err
			}
			m.WindowID = repox.Ptr(vo.ID)
			c := schedule.AvailabilityExceptionSpanCaseWindow
			m.SpanCase = &c
		}
		if v := in.GetDateRange(); v != nil {
			vo := shared.DateRangeFromProto(v)
			vo.ID = repox.NewULID()
			if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
				return err
			}
			m.DateRangeID = repox.Ptr(vo.ID)
			c := schedule.AvailabilityExceptionSpanCaseDateRange
			m.SpanCase = &c
		}
		return schedule.NewAvailabilityExceptionStore(tx).Create(ctx, m)
	}); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormAvailabilityExceptionRepository) Get(ctx context.Context, name string) (*schedulepbv1.AvailabilityException, error) {
	ids, err := repox.SplitName(name, "properties", "units", "availabilityExceptions")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormAvailabilityExceptionRepository) get(ctx context.Context, id string) (*schedulepbv1.AvailabilityException, error) {
	var m schedule.AvailabilityException
	if err := r.DB.WithContext(ctx).Preload("Window").Preload("DateRange").First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormAvailabilityExceptionRepository) toProto(ctx context.Context, m *schedule.AvailabilityException) (*schedulepbv1.AvailabilityException, error) {
	out := schedule.AvailabilityExceptionToProto(m)
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records under parent.
func (r *GormAvailabilityExceptionRepository) List(ctx context.Context, parent string, in repox.ListInput) ([]*schedulepbv1.AvailabilityException, string, error) {
	parentIDs, err := repox.SplitName(parent, "properties", "units")
	if err != nil {
		return nil, "", err
	}
	scope := r.DB.Where("unit_id = ?", parentIDs[len(parentIDs)-1])
	return r.list(ctx, scope, in)
}

func (r *GormAvailabilityExceptionRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*schedulepbv1.AvailabilityException, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[schedule.AvailabilityException](schedule.AvailabilityExceptionFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope.Preload("Window").Preload("DateRange"), filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*schedulepbv1.AvailabilityException, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormAvailabilityExceptionRepository) Update(ctx context.Context, in *schedulepbv1.AvailabilityException, paths []string) (*schedulepbv1.AvailabilityException, error) {
	ids, err := repox.SplitName(in.GetName(), "properties", "units", "availabilityExceptions")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing schedule.AvailabilityException
		if err := tx.WithContext(ctx).Preload("Window").Preload("DateRange").First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		var staleWindow string
		var staleDateRange string
		existingPB := schedule.AvailabilityExceptionToProto(&existing)
		merged := proto.Clone(existingPB).(*schedulepbv1.AvailabilityException)
		applyAvailabilityExceptionMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := schedule.AvailabilityExceptionFromProto(merged)
		_ = next
		existing.Name = next.Name
		existing.Kind = next.Kind
		existing.Reason = next.Reason
		if repox.GroupTouched(paths, "window") || repox.GroupTouched(paths, "date_range") {
			if existing.WindowID != nil {
				staleWindow = *existing.WindowID
			}
			existing.WindowID = nil
			if existing.DateRangeID != nil {
				staleDateRange = *existing.DateRangeID
			}
			existing.DateRangeID = nil
			existing.SpanCase = nil
			if v := merged.GetWindow(); v != nil {
				vo := shared.TimeWindowFromProto(v)
				vo.ID = repox.NewULID()
				if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
					return err
				}
				existing.WindowID = repox.Ptr(vo.ID)
				c := schedule.AvailabilityExceptionSpanCaseWindow
				existing.SpanCase = &c
			}
			if v := merged.GetDateRange(); v != nil {
				vo := shared.DateRangeFromProto(v)
				vo.ID = repox.NewULID()
				if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
					return err
				}
				existing.DateRangeID = repox.Ptr(vo.ID)
				c := schedule.AvailabilityExceptionSpanCaseDateRange
				existing.SpanCase = &c
			}
		}
		if err := schedule.NewAvailabilityExceptionStore(tx).Update(ctx, &existing); err != nil {
			return err
		}
		if staleWindow != "" {
			if err := tx.WithContext(ctx).Delete(&shared.TimeWindow{}, "id = ?", staleWindow).Error; err != nil {
				return err
			}
		}
		if staleDateRange != "" {
			if err := tx.WithContext(ctx).Delete(&shared.DateRange{}, "id = ?", staleDateRange).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormAvailabilityExceptionRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "properties", "units", "availabilityExceptions")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing schedule.AvailabilityException
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(r.DB.Transaction(func(tx *gorm.DB) error {
		if err := schedule.NewAvailabilityExceptionStore(tx).DeleteByID(ctx, id); err != nil {
			return err
		}
		if existing.WindowID != nil {
			if err := tx.WithContext(ctx).Delete(&shared.TimeWindow{}, "id = ?", *existing.WindowID).Error; err != nil {
				return err
			}
		}
		if existing.DateRangeID != nil {
			if err := tx.WithContext(ctx).Delete(&shared.DateRange{}, "id = ?", *existing.DateRangeID).Error; err != nil {
				return err
			}
		}
		return nil
	}))
}

// Compile-time proof the adapter satisfies the interface.
var _ AvailabilityExceptionRepository = (*GormAvailabilityExceptionRepository)(nil)
