// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm 1.1.1
// 	protoc             (unknown)
// source: freebusy/organisation/v1/organisation.proto
//
// database: freebusy
// schema:   organisation
//
// protorm — https://github.com/the-protobuf-project/protorm

package organisation

import (
	"encoding/json"
	"time"
)

// Lifecycle state of an organisation.
type OrganisationState string

// OrganisationState values as stored in the database.
const (
	// Active.
	OrganisationStateActive OrganisationState = "ACTIVE"
	// Suspended; access blocked.
	OrganisationStateSuspended OrganisationState = "SUSPENDED"
)

// A member's role within an organisation.
type OrganisationRole string

// OrganisationRole values as stored in the database.
const (
	// Full control, including billing and deletion.
	OrganisationRoleOwner OrganisationRole = "OWNER"
	// Manage members and resources.
	OrganisationRoleAdmin OrganisationRole = "ADMIN"
	// Create and manage bookings and resources.
	OrganisationRoleMember OrganisationRole = "MEMBER"
	// Read-only access.
	OrganisationRoleViewer OrganisationRole = "VIEWER"
)

// Confirmation state of a membership.
type MemberState string

// MemberState values as stored in the database.
const (
	// Invited, awaiting acceptance.
	MemberStateInvited MemberState = "INVITED"
	// Active member.
	MemberStateActive MemberState = "ACTIVE"
	// Suspended within the organisation.
	MemberStateSuspended MemberState = "SUSPENDED"
)

// A tenant. Organisation is the unit of multi-tenancy; the shell enforces isolation with row-level security keyed off the caller's organisation, so most resource names stay flat and the organisation appears explicitly only here.
type Organisation struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// The organisation name. Format: organisations/{organisation}
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Human-friendly organisation name (e.g. "Acme Inc.").
	DisplayName string `gorm:"column:display_name;not null" json:"display_name" validate:"required"`
	// URL-safe slug, unique across organisations.
	Slug *string `gorm:"column:slug" json:"slug,omitempty"`
	// Billing contact email.
	BillingEmail *string `gorm:"column:billing_email" json:"billing_email,omitempty"`
	// Lifecycle state.
	State *OrganisationState `gorm:"column:state;check:chk_resource_state,state IN ('ACTIVE','SUSPENDED')" json:"state,omitempty"`
	// Arbitrary organisation-level settings.
	Settings json.RawMessage `gorm:"column:settings;type:jsonb" json:"settings,omitempty"`
	// Number of members across all states.
	MemberCount *int64 `gorm:"column:member_count" json:"member_count,omitempty"`
	// Creation timestamp.
	CreateTime time.Time `gorm:"column:create_time;type:timestamptz;not null;autoCreateTime" json:"create_time"`
	// Last-modification timestamp.
	UpdateTime time.Time `gorm:"column:update_time;type:timestamptz;not null;autoUpdateTime" json:"update_time"`
	// Opaque version for optimistic concurrency (AIP-154); echo on update/delete.
	Etag *string `gorm:"column:etag" json:"etag,omitempty"`
	// Back-relation: Member records that reference this via organisation_id.
	Members []Member `gorm:"foreignKey:OrganisationID" json:"members,omitempty"`
}

func (*Organisation) TableName() string { return "organisation.resource" }

// The membership of a user in an organisation, with their role.
type Member struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// The member name. Format: organisations/{organisation}/members/{member}
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// The user, once the invite is accepted. Format: users/{user}
	UserID *string `gorm:"column:user;index:idx_members_user" json:"user,omitempty"`
	// The invited email address.
	Email string `gorm:"column:email;not null" json:"email" validate:"required"`
	// Cached display name of the member.
	DisplayName *string `gorm:"column:display_name" json:"display_name,omitempty"`
	// The member's role in the organisation.
	Role OrganisationRole `gorm:"column:role;not null;default:'OWNER';check:chk_members_role,role IN ('OWNER','ADMIN','MEMBER','VIEWER')" json:"role" validate:"required"`
	// Confirmation state of the membership.
	State *MemberState `gorm:"column:state;check:chk_members_state,state IN ('INVITED','ACTIVE','SUSPENDED')" json:"state,omitempty"`
	// The user who issued the invite. Format: users/{user}
	InviterID *string `gorm:"column:inviter;index:idx_members_inviter" json:"inviter,omitempty"`
	// Creation timestamp (when the invite was created).
	CreateTime time.Time `gorm:"column:create_time;type:timestamptz;not null;autoCreateTime" json:"create_time"`
	// Last-modification timestamp.
	UpdateTime time.Time `gorm:"column:update_time;type:timestamptz;not null;autoUpdateTime" json:"update_time"`
	// Opaque version for optimistic concurrency (AIP-154); echo on update/delete.
	Etag *string `gorm:"column:etag" json:"etag,omitempty"`
	// Parent reference to Organisation (from the AIP resource pattern).
	OrganisationID string        `gorm:"column:organisation_id;not null;index:idx_members_organisation_id" json:"organisation_id" validate:"required"`
	Organisation   *Organisation `gorm:"foreignKey:OrganisationID;constraint:OnDelete:CASCADE" json:"organisation,omitempty"`
}

func (*Member) TableName() string { return "organisation.members" }
