// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file mcp/protobuf/annotations.proto (package mcp.protobuf, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { EnumOptions, EnumValueOptions, FieldOptions, MethodOptions, ServiceOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { MCPServiceOptions } from "./service_options_pb";
import { file_mcp_protobuf_service_options } from "./service_options_pb";
import type { MCPPrompt, MCPToolOptions } from "./prompt_pb";
import { file_mcp_protobuf_prompt } from "./prompt_pb";
import type { MCPElicitation } from "./elicitation_pb";
import { file_mcp_protobuf_elicitation } from "./elicitation_pb";
import type { MCPFieldOptions } from "./field_pb";
import { file_mcp_protobuf_field } from "./field_pb";
import type { MCPEnumOptions, MCPEnumValueOptions } from "./enum_pb";
import { file_mcp_protobuf_enum } from "./enum_pb";

/**
 * Describes the file mcp/protobuf/annotations.proto.
 */
export const file_mcp_protobuf_annotations: GenFile = /*@__PURE__*/
  fileDesc("Ch5tY3AvcHJvdG9idWYvYW5ub3RhdGlvbnMucHJvdG8SDG1jcC5wcm90b2J1ZjpfCgdzZXJ2aWNlEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGLiOAyABKAsyHy5tY3AucHJvdG9idWYuTUNQU2VydmljZU9wdGlvbnNSB3NlcnZpY2WIAQE6VQoEdG9vbBIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGLmOAyABKAsyHC5tY3AucHJvdG9idWYuTUNQVG9vbE9wdGlvbnNSBHRvb2yIAQE6VAoGcHJvbXB0Eh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYuo4DIAEoCzIXLm1jcC5wcm90b2J1Zi5NQ1BQcm9tcHRSBnByb21wdIgBATpjCgtlbGljaXRhdGlvbhIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGLuOAyABKAsyHC5tY3AucHJvdG9idWYuTUNQRWxpY2l0YXRpb25SC2VsaWNpdGF0aW9uiAEBOlcKBWZpZWxkEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxi8jgMgASgLMh0ubWNwLnByb3RvYnVmLk1DUEZpZWxkT3B0aW9uc1IFZmllbGSIAQE6UwoEZW51bRIcLmdvb2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxi9jgMgASgLMhwubWNwLnByb3RvYnVmLk1DUEVudW1PcHRpb25zUgRlbnVtiAEBOmgKCmVudW1fdmFsdWUSIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxi+jgMgASgLMiEubWNwLnByb3RvYnVmLk1DUEVudW1WYWx1ZU9wdGlvbnNSCWVudW1WYWx1ZYgBAUK1AQoQY29tLm1jcC5wcm90b2J1ZkIQQW5ub3RhdGlvbnNQcm90b1ABWj5naXRodWIuY29tL21hY2hhbmlyb2JvdGljcy9ncnBjLW1jcC1nYXRld2F5L21jcC9wcm90b2J1Zi9tY3BwYqICA01QWKoCDE1jcC5Qcm90b2J1ZsoCDE1jcFxQcm90b2J1ZuICGE1jcFxQcm90b2J1ZlxHUEJNZXRhZGF0YeoCDU1jcDo6UHJvdG9idWZiBnByb3RvMw", [file_google_protobuf_descriptor, file_mcp_protobuf_service_options, file_mcp_protobuf_prompt, file_mcp_protobuf_elicitation, file_mcp_protobuf_field, file_mcp_protobuf_enum]);

/**
 * @generated from extension: optional mcp.protobuf.MCPServiceOptions service = 51000;
 */
export const service: GenExtension<ServiceOptions, MCPServiceOptions> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 0);

/**
 * @generated from extension: optional mcp.protobuf.MCPToolOptions tool = 51001;
 */
export const tool: GenExtension<MethodOptions, MCPToolOptions> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 1);

/**
 * @generated from extension: optional mcp.protobuf.MCPPrompt prompt = 51002;
 */
export const prompt: GenExtension<MethodOptions, MCPPrompt> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 2);

/**
 * @generated from extension: optional mcp.protobuf.MCPElicitation elicitation = 51003;
 */
export const elicitation: GenExtension<MethodOptions, MCPElicitation> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 3);

/**
 * @generated from extension: optional mcp.protobuf.MCPFieldOptions field = 51004;
 */
export const field: GenExtension<FieldOptions, MCPFieldOptions> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 4);

/**
 * @generated from extension: optional mcp.protobuf.MCPEnumOptions enum = 51005;
 */
export const enum$: GenExtension<EnumOptions, MCPEnumOptions> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 5);

/**
 * @generated from extension: optional mcp.protobuf.MCPEnumValueOptions enum_value = 51006;
 */
export const enum_value: GenExtension<EnumValueOptions, MCPEnumValueOptions> = /*@__PURE__*/
  extDesc(file_mcp_protobuf_annotations, 6);

