// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file mcp/protobuf/enum.proto (package mcp.protobuf, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mcp/protobuf/enum.proto.
 */
export const file_mcp_protobuf_enum: GenFile = /*@__PURE__*/
  fileDesc("ChdtY3AvcHJvdG9idWYvZW51bS5wcm90bxIMbWNwLnByb3RvYnVmIiUKDk1DUEVudW1PcHRpb25zEhMKC2Rlc2NyaXB0aW9uGAEgASgJIioKE01DUEVudW1WYWx1ZU9wdGlvbnMSEwoLZGVzY3JpcHRpb24YASABKAlCrgEKEGNvbS5tY3AucHJvdG9idWZCCUVudW1Qcm90b1ABWj5naXRodWIuY29tL21hY2hhbmlyb2JvdGljcy9ncnBjLW1jcC1nYXRld2F5L21jcC9wcm90b2J1Zi9tY3BwYqICA01QWKoCDE1jcC5Qcm90b2J1ZsoCDE1jcFxQcm90b2J1ZuICGE1jcFxQcm90b2J1ZlxHUEJNZXRhZGF0YeoCDU1jcDo6UHJvdG9idWZiBnByb3RvMw");

/**
 * MCPEnumOptions attaches a description to an enum type.
 * Used as: option (mcp.protobuf.enum) = { description: "..." };
 * The description appears in the MCP tool inputSchema for enum fields.
 *
 * @generated from message mcp.protobuf.MCPEnumOptions
 */
export type MCPEnumOptions = Message<"mcp.protobuf.MCPEnumOptions"> & {
  /**
   * Human-readable description of the enum (e.g. for JSON Schema).
   *
   * @generated from field: string description = 1;
   */
  description: string;
};

/**
 * Describes the message mcp.protobuf.MCPEnumOptions.
 * Use `create(MCPEnumOptionsSchema)` to create a new message.
 */
export const MCPEnumOptionsSchema: GenMessage<MCPEnumOptions> = /*@__PURE__*/
  messageDesc(file_mcp_protobuf_enum, 0);

/**
 * MCPEnumValueOptions attaches a description to an enum value.
 * Used as: ENUM_VALUE = 0 [(mcp.protobuf.enum_value) = { description: "..." }];
 * Value descriptions are combined into the schema description for the enum field.
 *
 * @generated from message mcp.protobuf.MCPEnumValueOptions
 */
export type MCPEnumValueOptions = Message<"mcp.protobuf.MCPEnumValueOptions"> & {
  /**
   * Human-readable description of this enum value.
   *
   * @generated from field: string description = 1;
   */
  description: string;
};

/**
 * Describes the message mcp.protobuf.MCPEnumValueOptions.
 * Use `create(MCPEnumValueOptionsSchema)` to create a new message.
 */
export const MCPEnumValueOptionsSchema: GenMessage<MCPEnumValueOptions> = /*@__PURE__*/
  messageDesc(file_mcp_protobuf_enum, 1);

