// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file mcp/protobuf/field_type.proto (package mcp.protobuf, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file mcp/protobuf/field_type.proto.
 */
export const file_mcp_protobuf_field_type: GenFile = /*@__PURE__*/
  fileDesc("Ch1tY3AvcHJvdG9idWYvZmllbGRfdHlwZS5wcm90bxIMbWNwLnByb3RvYnVmKpwBCgxNQ1BGaWVsZFR5cGUSHgoaTUNQX0ZJRUxEX1RZUEVfVU5TUEVDSUZJRUQQABIZChVNQ1BfRklFTERfVFlQRV9TVFJJTkcQARIZChVNQ1BfRklFTERfVFlQRV9OVU1CRVIQAhIaChZNQ1BfRklFTERfVFlQRV9CT09MRUFOEAMSGgoWTUNQX0ZJRUxEX1RZUEVfSU5URUdFUhAEQrMBChBjb20ubWNwLnByb3RvYnVmQg5GaWVsZFR5cGVQcm90b1ABWj5naXRodWIuY29tL21hY2hhbmlyb2JvdGljcy9ncnBjLW1jcC1nYXRld2F5L21jcC9wcm90b2J1Zi9tY3BwYqICA01QWKoCDE1jcC5Qcm90b2J1ZsoCDE1jcFxQcm90b2J1ZuICGE1jcFxQcm90b2J1ZlxHUEJNZXRhZGF0YeoCDU1jcDo6UHJvdG9idWZiBnByb3RvMw");

/**
 * MCPFieldType enumerates JSON Schema primitive types used by elicitation fields.
 *
 * @generated from enum mcp.protobuf.MCPFieldType
 */
export enum MCPFieldType {
  /**
   * Default value; treated as string.
   *
   * @generated from enum value: MCP_FIELD_TYPE_UNSPECIFIED = 0;
   */
  MCP_FIELD_TYPE_UNSPECIFIED = 0,

  /**
   * JSON Schema "string" type.
   *
   * @generated from enum value: MCP_FIELD_TYPE_STRING = 1;
   */
  MCP_FIELD_TYPE_STRING = 1,

  /**
   * JSON Schema "number" type (floating-point).
   *
   * @generated from enum value: MCP_FIELD_TYPE_NUMBER = 2;
   */
  MCP_FIELD_TYPE_NUMBER = 2,

  /**
   * JSON Schema "boolean" type.
   *
   * @generated from enum value: MCP_FIELD_TYPE_BOOLEAN = 3;
   */
  MCP_FIELD_TYPE_BOOLEAN = 3,

  /**
   * JSON Schema "integer" type.
   *
   * @generated from enum value: MCP_FIELD_TYPE_INTEGER = 4;
   */
  MCP_FIELD_TYPE_INTEGER = 4,
}

/**
 * Describes the enum mcp.protobuf.MCPFieldType.
 */
export const MCPFieldTypeSchema: GenEnum<MCPFieldType> = /*@__PURE__*/
  enumDesc(file_mcp_protobuf_field_type, 0);

