// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file mcp/protobuf/resource.proto (package mcp.protobuf, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MCPMimeType } from "./mime_type_pb";
import { file_mcp_protobuf_mime_type } from "./mime_type_pb";
import type { MCPRole } from "./prompt_pb";
import { file_mcp_protobuf_prompt } from "./prompt_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mcp/protobuf/resource.proto.
 */
export const file_mcp_protobuf_resource: GenFile = /*@__PURE__*/
  fileDesc("ChttY3AvcHJvdG9idWYvcmVzb3VyY2UucHJvdG8SDG1jcC5wcm90b2J1ZiKLAQoOTUNQQW5ub3RhdGlvbnMSJwoIYXVkaWVuY2UYASADKA4yFS5tY3AucHJvdG9idWYuTUNQUm9sZRIaCg1sYXN0X21vZGlmaWVkGAIgASgJSACIAQESFQoIcHJpb3JpdHkYAyABKAFIAYgBAUIQCg5fbGFzdF9tb2RpZmllZEILCglfcHJpb3JpdHkidgoHTUNQSWNvbhILCgNzcmMYASABKAkSFgoJbWltZV90eXBlGAIgASgJSACIAQESDQoFc2l6ZXMYAyADKAkSKQoFdGhlbWUYBCABKA4yGi5tY3AucHJvdG9idWYuTUNQSWNvblRoZW1lQgwKCl9taW1lX3R5cGUizwIKC01DUFJlc291cmNlEg0KA3VyaRgBIAEoCUgAEhEKB3BhdHRlcm4YAiABKAlIABIMCgRuYW1lGAMgASgJEhIKBXRpdGxlGAQgASgJSAGIAQESGAoLZGVzY3JpcHRpb24YBSABKAlIAogBARIsCgltaW1lX3R5cGUYBiABKA4yGS5tY3AucHJvdG9idWYuTUNQTWltZVR5cGUSEQoEc2l6ZRgHIAEoA0gDiAEBEjYKC2Fubm90YXRpb25zGAggASgLMhwubWNwLnByb3RvYnVmLk1DUEFubm90YXRpb25zSASIAQESJAoFaWNvbnMYCSADKAsyFS5tY3AucHJvdG9idWYuTUNQSWNvbkIQCg51cmlfb3JfcGF0dGVybkIICgZfdGl0bGVCDgoMX2Rlc2NyaXB0aW9uQgcKBV9zaXplQg4KDF9hbm5vdGF0aW9ucyphCgxNQ1BJY29uVGhlbWUSHgoaTUNQX0lDT05fVEhFTUVfVU5TUEVDSUZJRUQQABIYChRNQ1BfSUNPTl9USEVNRV9MSUdIVBABEhcKE01DUF9JQ09OX1RIRU1FX0RBUksQAkKyAQoQY29tLm1jcC5wcm90b2J1ZkINUmVzb3VyY2VQcm90b1ABWj5naXRodWIuY29tL21hY2hhbmlyb2JvdGljcy9ncnBjLW1jcC1nYXRld2F5L21jcC9wcm90b2J1Zi9tY3BwYqICA01QWKoCDE1jcC5Qcm90b2J1ZsoCDE1jcFxQcm90b2J1ZuICGE1jcFxQcm90b2J1ZlxHUEJNZXRhZGF0YeoCDU1jcDo6UHJvdG9idWZiBnByb3RvMw", [file_mcp_protobuf_mime_type, file_mcp_protobuf_prompt]);

/**
 * MCPAnnotations carries audience and priority metadata attached to a resource.
 * It corresponds to the Annotations struct in the MCP Go SDK.
 *
 * @generated from message mcp.protobuf.MCPAnnotations
 */
export type MCPAnnotations = Message<"mcp.protobuf.MCPAnnotations"> & {
  /**
   * Who the resource is intended for. May contain multiple values to indicate
   * content useful for more than one audience (e.g. both user and assistant).
   *
   * @generated from field: repeated mcp.protobuf.MCPRole audience = 1;
   */
  audience: MCPRole[];

  /**
   * ISO 8601 formatted timestamp of when the resource was last modified.
   * Examples: last activity in an open file, time the resource was attached.
   *
   * @generated from field: optional string last_modified = 2;
   */
  lastModified?: string | undefined;

  /**
   * Describes how important this data is for operating the server.
   * A value of 1.0 means "most important" (effectively required);
   * 0.0 means "least important" (entirely optional).
   *
   * @generated from field: optional double priority = 3;
   */
  priority?: number | undefined;
};

/**
 * Describes the message mcp.protobuf.MCPAnnotations.
 * Use `create(MCPAnnotationsSchema)` to create a new message.
 */
export const MCPAnnotationsSchema: GenMessage<MCPAnnotations> = /*@__PURE__*/
  messageDesc(file_mcp_protobuf_resource, 0);

/**
 * MCPIcon describes a single icon image associated with a resource.
 * It corresponds to the Icon struct in the MCP Go SDK.
 *
 * @generated from message mcp.protobuf.MCPIcon
 */
export type MCPIcon = Message<"mcp.protobuf.MCPIcon"> & {
  /**
   * URI pointing to the icon resource. This can be an HTTP/HTTPS URL pointing
   * to an image file, or a data URI with base64-encoded image data. Required.
   *
   * @generated from field: string src = 1;
   */
  src: string;

  /**
   * MIME type of the icon image. Should be provided when the server's
   * Content-Type header is missing or too generic.
   *
   * @generated from field: optional string mime_type = 2;
   */
  mimeType?: string | undefined;

  /**
   * Size specification for the icon. Examples:
   *   ["48x48"]           — single fixed size
   *   ["any"]             — scalable format such as SVG
   *   ["48x48", "96x96"]  — multiple available sizes
   *
   * @generated from field: repeated string sizes = 3;
   */
  sizes: string[];

  /**
   * The background context this icon is designed for.
   * Omit if the icon is suitable for any background.
   *
   * @generated from field: mcp.protobuf.MCPIconTheme theme = 4;
   */
  theme: MCPIconTheme;
};

/**
 * Describes the message mcp.protobuf.MCPIcon.
 * Use `create(MCPIconSchema)` to create a new message.
 */
export const MCPIconSchema: GenMessage<MCPIcon> = /*@__PURE__*/
  messageDesc(file_mcp_protobuf_resource, 1);

/**
 * MCPResource describes an MCP resource exposed by a gRPC service.
 * It corresponds to the Resource struct in the MCP Go SDK.
 *
 * Either uri or pattern must be set (enforced by the oneof).
 * Use uri for a concrete resource at a fixed location.
 * Use pattern for a URI template that matches a family of resources.
 *
 * @generated from message mcp.protobuf.MCPResource
 */
export type MCPResource = Message<"mcp.protobuf.MCPResource"> & {
  /**
   * Identifies whether this is a concrete resource (uri) or a URI-template
   * resource (pattern). Exactly one must be set.
   *
   * @generated from oneof mcp.protobuf.MCPResource.uri_or_pattern
   */
  uriOrPattern: {
    /**
     * The URI of a specific resource, e.g. "file:///home/user/report.pdf".
     *
     * @generated from field: string uri = 1;
     */
    value: string;
    case: "uri";
  } | {
    /**
     * A URI template pattern for a family of resources,
     * e.g. "file:///home/user/{filename}".
     *
     * @generated from field: string pattern = 2;
     */
    value: string;
    case: "pattern";
  } | { case: undefined; value?: undefined };

  /**
   * Programmatic identifier for the resource. Used as the display name when
   * title is absent.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Human-readable display name, optimised for UI and end-user contexts.
   * Preferred over name when both are present.
   *
   * @generated from field: optional string title = 4;
   */
  title?: string | undefined;

  /**
   * A description of what this resource represents. Clients may use this
   * as a hint to help the LLM understand what the resource contains.
   *
   * @generated from field: optional string description = 5;
   */
  description?: string | undefined;

  /**
   * The MIME type of the resource content, if known.
   *
   * @generated from field: mcp.protobuf.MCPMimeType mime_type = 6;
   */
  mimeType: MCPMimeType;

  /**
   * The size of the raw resource content in bytes (before any base64 encoding
   * or tokenisation), if known. Clients may use this to estimate context usage.
   *
   * @generated from field: optional int64 size = 7;
   */
  size?: bigint | undefined;

  /**
   * Optional annotations describing intended audience and priority.
   *
   * @generated from field: optional mcp.protobuf.MCPAnnotations annotations = 8;
   */
  annotations?: MCPAnnotations | undefined;

  /**
   * Icons representing the resource in client UIs.
   *
   * @generated from field: repeated mcp.protobuf.MCPIcon icons = 9;
   */
  icons: MCPIcon[];
};

/**
 * Describes the message mcp.protobuf.MCPResource.
 * Use `create(MCPResourceSchema)` to create a new message.
 */
export const MCPResourceSchema: GenMessage<MCPResource> = /*@__PURE__*/
  messageDesc(file_mcp_protobuf_resource, 2);

/**
 * MCPIconTheme indicates the background context an icon is designed for.
 *
 * @generated from enum mcp.protobuf.MCPIconTheme
 */
export enum MCPIconTheme {
  /**
   * @generated from enum value: MCP_ICON_THEME_UNSPECIFIED = 0;
   */
  MCP_ICON_THEME_UNSPECIFIED = 0,

  /**
   * The icon is designed for display on a light background.
   *
   * @generated from enum value: MCP_ICON_THEME_LIGHT = 1;
   */
  MCP_ICON_THEME_LIGHT = 1,

  /**
   * The icon is designed for display on a dark background.
   *
   * @generated from enum value: MCP_ICON_THEME_DARK = 2;
   */
  MCP_ICON_THEME_DARK = 2,
}

/**
 * Describes the enum mcp.protobuf.MCPIconTheme.
 */
export const MCPIconThemeSchema: GenEnum<MCPIconTheme> = /*@__PURE__*/
  enumDesc(file_mcp_protobuf_resource, 0);

