// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.3.0
// 	protoc (unknown)
// source: freebusy/shared/v1/types.proto
//
// database: freebusy
// schema:   shared
//
// orm — https://github.com/the-protobuf-project/orm

package shared

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// PriceComponentStore provides typed CRUD access to PriceComponent records.
// One line in a price breakdown: a base charge, a fee, a tax, or a discount. Clients branch on `type` and `code`; the signed `amount` rolls up to the booking total (charges positive, discounts negative).
type PriceComponentStore struct{ DB *gorm.DB }

// Compile-time proof that PriceComponentStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[PriceComponent] = (*PriceComponentStore)(nil)

// NewPriceComponentStore returns a PriceComponentStore backed by db.
func NewPriceComponentStore(db *gorm.DB) *PriceComponentStore { return &PriceComponentStore{DB: db} }

// Create inserts m.
func (s *PriceComponentStore) Create(ctx context.Context, m *PriceComponent) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the PriceComponent records matching opts.
func (s *PriceComponentStore) List(ctx context.Context, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of PriceComponent records matching opts.Where
// (pagination and ordering are ignored).
func (s *PriceComponentStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&PriceComponent{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *PriceComponentStore) Update(ctx context.Context, m *PriceComponent) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the PriceComponent with the given primary key.
func (s *PriceComponentStore) GetByID(ctx context.Context, id string) (*PriceComponent, error) {
	var m PriceComponent
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the PriceComponent with the given primary key.
func (s *PriceComponentStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&PriceComponent{}, "id = ?", id).Error
}

// ListByBookingID returns the PriceComponent records whose booking_id matches id, with opts applied.
func (s *PriceComponentStore) ListByBookingID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	q := opts.Apply(s.DB.WithContext(ctx).Where("booking_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAmountID returns the PriceComponent records whose amount_id matches id, with opts applied.
func (s *PriceComponentStore) ListByAmountID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	q := opts.Apply(s.DB.WithContext(ctx).Where("amount_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
