// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file protorm/v1/column.proto (package protorm.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protorm/v1/column.proto.
 */
export const file_protorm_v1_column: GenFile = /*@__PURE__*/
  fileDesc("Chdwcm90b3JtL3YxL2NvbHVtbi5wcm90bxIKcHJvdG9ybS52MSKaAgoNQ29sdW1uT3B0aW9ucxIOCgZjb2x1bW4YASABKAkSDAoEdHlwZRgCIAEoCRIVCg1kZWZhdWx0X3ZhbHVlGAMgASgJEg4KBnVuaXF1ZRgEIAEoCBINCgVpbmRleBgFIAEoCBIMCgRza2lwGAYgASgIEhIKCm1heF9sZW5ndGgYByABKAUSEQoJcHJlY2lzaW9uGAggASgFEg0KBXNjYWxlGAkgASgFEjAKCW9uX2RlbGV0ZRgKIAEoDjIdLnByb3Rvcm0udjEuUmVmZXJlbnRpYWxBY3Rpb24SMAoJb25fdXBkYXRlGAsgASgOMh0ucHJvdG9ybS52MS5SZWZlcmVudGlhbEFjdGlvbkoECAwQDVIHc3RvcmFnZSrfAQoRUmVmZXJlbnRpYWxBY3Rpb24SIgoeUkVGRVJFTlRJQUxfQUNUSU9OX1VOU1BFQ0lGSUVEEAASHgoaUkVGRVJFTlRJQUxfQUNUSU9OX0NBU0NBREUQARIfChtSRUZFUkVOVElBTF9BQ1RJT05fUkVTVFJJQ1QQAhIfChtSRUZFUkVOVElBTF9BQ1RJT05fU0VUX05VTEwQAxIiCh5SRUZFUkVOVElBTF9BQ1RJT05fU0VUX0RFRkFVTFQQBBIgChxSRUZFUkVOVElBTF9BQ1RJT05fTk9fQUNUSU9OEAVCsQEKDmNvbS5wcm90b3JtLnYxQgtDb2x1bW5Qcm90b1ABWklnaXRodWIuY29tL3RoZS1wcm90b2J1Zi1wcm9qZWN0L3Byb3Rvcm0vcGx1Z2luL3BiL3Byb3Rvcm1wYnYxO3Byb3Rvcm1wYnYxogIDUFhYqgIKUHJvdG9ybS5WMcoCClByb3Rvcm1cVjHiAhZQcm90b3JtXFYxXEdQQk1ldGFkYXRh6gILUHJvdG9ybTo6VjFiBnByb3RvMw");

/**
 * ColumnOptions overrides column-level generation for a single field.
 *
 * Applied via:
 *
 * 	string title = 2 [(protorm.v1.column) = { max_length: 500 }];
 *
 * @generated from message protorm.v1.ColumnOptions
 */
export type ColumnOptions = Message<"protorm.v1.ColumnOptions"> & {
  /**
   * column is an explicit column name.
   * Defaults to the proto field name, which is already snake_case.
   *
   * @generated from field: string column = 1;
   */
  column: string;

  /**
   * type is an explicit database type, e.g. "VARCHAR(255)", "JSONB", "TIMESTAMPTZ".
   * Provider-specific escape hatch; prefer max_length / precision for
   * provider-neutral sizing. Overrides all inference.
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * default_value is a SQL default expression, e.g. "NOW()", "'active'", "0".
   * Written verbatim into the DEFAULT clause.
   *
   * @generated from field: string default_value = 3;
   */
  defaultValue: string;

  /**
   * unique adds a UNIQUE constraint to this column.
   *
   * @generated from field: bool unique = 4;
   */
  unique: boolean;

  /**
   * index adds a single-column index on this column.
   * Use TableOptions.indexes for composite indexes.
   *
   * @generated from field: bool index = 5;
   */
  index: boolean;

  /**
   * skip excludes this field from all output — no column is generated.
   *
   * @generated from field: bool skip = 6;
   */
  skip: boolean;

  /**
   * max_length caps a string field: VARCHAR(max_length) instead of the
   * VARCHAR(255) default. Provider-neutral (Mongo ignores it).
   *
   * @generated from field: int32 max_length = 7;
   */
  maxLength: number;

  /**
   * precision sizes the integral digit count of a numeric field:
   * NUMERIC(precision, scale). Applies to double/float fields.
   *
   * @generated from field: int32 precision = 8;
   */
  precision: number;

  /**
   * scale sizes the fractional digit count of a numeric field.
   * Defaults to 0 when only precision is set.
   *
   * @generated from field: int32 scale = 9;
   */
  scale: number;

  /**
   * on_delete sets the FK ON DELETE referential action for a field carrying
   * google.api.resource_reference. Ignored on non-reference fields.
   *
   * @generated from field: protorm.v1.ReferentialAction on_delete = 10;
   */
  onDelete: ReferentialAction;

  /**
   * on_update sets the FK ON UPDATE referential action for a field carrying
   * google.api.resource_reference. Ignored on non-reference fields.
   *
   * @generated from field: protorm.v1.ReferentialAction on_update = 11;
   */
  onUpdate: ReferentialAction;
};

/**
 * Describes the message protorm.v1.ColumnOptions.
 * Use `create(ColumnOptionsSchema)` to create a new message.
 */
export const ColumnOptionsSchema: GenMessage<ColumnOptions> = /*@__PURE__*/
  messageDesc(file_protorm_v1_column, 0);

/**
 * ReferentialAction is the ON DELETE / ON UPDATE behavior of a foreign key
 * inferred from google.api.resource_reference.
 *
 * @generated from enum protorm.v1.ReferentialAction
 */
export enum ReferentialAction {
  /**
   * Database default behavior (NO ACTION in PostgreSQL).
   *
   * @generated from enum value: REFERENTIAL_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Delete/update child rows when the parent row is deleted/updated.
   *
   * @generated from enum value: REFERENTIAL_ACTION_CASCADE = 1;
   */
  CASCADE = 1,

  /**
   * Reject the parent delete/update while child rows exist.
   *
   * @generated from enum value: REFERENTIAL_ACTION_RESTRICT = 2;
   */
  RESTRICT = 2,

  /**
   * Null the FK column when the parent row is deleted/updated.
   *
   * @generated from enum value: REFERENTIAL_ACTION_SET_NULL = 3;
   */
  SET_NULL = 3,

  /**
   * Reset the FK column to its default value.
   *
   * @generated from enum value: REFERENTIAL_ACTION_SET_DEFAULT = 4;
   */
  SET_DEFAULT = 4,

  /**
   * Explicit NO ACTION.
   *
   * @generated from enum value: REFERENTIAL_ACTION_NO_ACTION = 5;
   */
  NO_ACTION = 5,
}

/**
 * Describes the enum protorm.v1.ReferentialAction.
 */
export const ReferentialActionSchema: GenEnum<ReferentialAction> = /*@__PURE__*/
  enumDesc(file_protorm_v1_column, 0);

