// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  propertyql
//
// orm — https://github.com/the-protobuf-project/orm

package propertyql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/feesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/licencesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/losdiscountsql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/mediasql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/policiesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/propertiesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/rateoverridesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/taxesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/unitapplicablepromocodesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/unitmediasql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/unitslinkql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/unitsql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// Model type aliases for this domain, re-exported from the owning resource packages.
type DeletePropertyFeesByIdResponse = feesql.DeletePropertyFeesByIdResponse
type InsertPropertyFeesResponse = feesql.InsertPropertyFeesResponse
type PropertyFees = feesql.PropertyFees
type PropertyFeesAggExp = feesql.PropertyFeesAggExp
type UpdatePropertyFeesByIdResponse = feesql.UpdatePropertyFeesByIdResponse
type DeletePropertyLicencesByIdResponse = licencesql.DeletePropertyLicencesByIdResponse
type InsertPropertyLicencesResponse = licencesql.InsertPropertyLicencesResponse
type PropertyLicences = licencesql.PropertyLicences
type PropertyLicencesAggExp = licencesql.PropertyLicencesAggExp
type UpdatePropertyLicencesByIdResponse = licencesql.UpdatePropertyLicencesByIdResponse
type DeletePropertyLosDiscountsByIdResponse = losdiscountsql.DeletePropertyLosDiscountsByIdResponse
type InsertPropertyLosDiscountsResponse = losdiscountsql.InsertPropertyLosDiscountsResponse
type PropertyLosDiscounts = losdiscountsql.PropertyLosDiscounts
type PropertyLosDiscountsAggExp = losdiscountsql.PropertyLosDiscountsAggExp
type UpdatePropertyLosDiscountsByIdResponse = losdiscountsql.UpdatePropertyLosDiscountsByIdResponse
type DeletePropertyMediasByIdResponse = mediasql.DeletePropertyMediasByIdResponse
type InsertPropertyMediasResponse = mediasql.InsertPropertyMediasResponse
type PropertyMedias = mediasql.PropertyMedias
type PropertyMediasAggExp = mediasql.PropertyMediasAggExp
type UpdatePropertyMediasByIdResponse = mediasql.UpdatePropertyMediasByIdResponse
type DeletePropertyPoliciesByIdResponse = policiesql.DeletePropertyPoliciesByIdResponse
type InsertPropertyPoliciesResponse = policiesql.InsertPropertyPoliciesResponse
type PropertyPolicies = policiesql.PropertyPolicies
type PropertyPoliciesAggExp = policiesql.PropertyPoliciesAggExp
type UpdatePropertyPoliciesByIdResponse = policiesql.UpdatePropertyPoliciesByIdResponse
type DeletePropertyPropertiesByIdResponse = propertiesql.DeletePropertyPropertiesByIdResponse
type InsertPropertyPropertiesResponse = propertiesql.InsertPropertyPropertiesResponse
type PropertyProperties = propertiesql.PropertyProperties
type PropertyPropertiesAggExp = propertiesql.PropertyPropertiesAggExp
type UpdatePropertyPropertiesByIdResponse = propertiesql.UpdatePropertyPropertiesByIdResponse
type DeletePropertyRateOverridesByIdResponse = rateoverridesql.DeletePropertyRateOverridesByIdResponse
type InsertPropertyRateOverridesResponse = rateoverridesql.InsertPropertyRateOverridesResponse
type PropertyRateOverrides = rateoverridesql.PropertyRateOverrides
type PropertyRateOverridesAggExp = rateoverridesql.PropertyRateOverridesAggExp
type UpdatePropertyRateOverridesByIdResponse = rateoverridesql.UpdatePropertyRateOverridesByIdResponse
type DeletePropertyTaxesByIdResponse = taxesql.DeletePropertyTaxesByIdResponse
type InsertPropertyTaxesResponse = taxesql.InsertPropertyTaxesResponse
type PropertyTaxes = taxesql.PropertyTaxes
type PropertyTaxesAggExp = taxesql.PropertyTaxesAggExp
type UpdatePropertyTaxesByIdResponse = taxesql.UpdatePropertyTaxesByIdResponse
type DeletePropertyUnitApplicablePromoCodesByIdResponse = unitapplicablepromocodesql.DeletePropertyUnitApplicablePromoCodesByIdResponse
type InsertPropertyUnitApplicablePromoCodesResponse = unitapplicablepromocodesql.InsertPropertyUnitApplicablePromoCodesResponse
type PropertyUnitApplicablePromoCodes = unitapplicablepromocodesql.PropertyUnitApplicablePromoCodes
type PropertyUnitApplicablePromoCodesAggExp = unitapplicablepromocodesql.PropertyUnitApplicablePromoCodesAggExp
type UpdatePropertyUnitApplicablePromoCodesByIdResponse = unitapplicablepromocodesql.UpdatePropertyUnitApplicablePromoCodesByIdResponse
type DeletePropertyUnitMediasByIdResponse = unitmediasql.DeletePropertyUnitMediasByIdResponse
type InsertPropertyUnitMediasResponse = unitmediasql.InsertPropertyUnitMediasResponse
type PropertyUnitMedias = unitmediasql.PropertyUnitMedias
type PropertyUnitMediasAggExp = unitmediasql.PropertyUnitMediasAggExp
type UpdatePropertyUnitMediasByIdResponse = unitmediasql.UpdatePropertyUnitMediasByIdResponse
type DeletePropertyUnitsLinkByIdResponse = unitslinkql.DeletePropertyUnitsLinkByIdResponse
type InsertPropertyUnitsLinkResponse = unitslinkql.InsertPropertyUnitsLinkResponse
type PropertyUnitsLink = unitslinkql.PropertyUnitsLink
type PropertyUnitsLinkAggExp = unitslinkql.PropertyUnitsLinkAggExp
type UpdatePropertyUnitsLinkByIdResponse = unitslinkql.UpdatePropertyUnitsLinkByIdResponse
type DeletePropertyUnitsByIdResponse = unitsql.DeletePropertyUnitsByIdResponse
type InsertPropertyUnitsResponse = unitsql.InsertPropertyUnitsResponse
type PropertyUnits = unitsql.PropertyUnits
type PropertyUnitsAggExp = unitsql.PropertyUnitsAggExp
type UpdatePropertyUnitsByIdResponse = unitsql.UpdatePropertyUnitsByIdResponse

// QueryHandler aggregates query handlers for the propertyql domain.
type QueryHandler struct {
	Fees                     feesql.QueryHandler
	Licences                 licencesql.QueryHandler
	LosDiscounts             losdiscountsql.QueryHandler
	Medias                   mediasql.QueryHandler
	Policies                 policiesql.QueryHandler
	Properties               propertiesql.QueryHandler
	RateOverrides            rateoverridesql.QueryHandler
	Taxes                    taxesql.QueryHandler
	UnitApplicablePromoCodes unitapplicablepromocodesql.QueryHandler
	UnitMedias               unitmediasql.QueryHandler
	Units                    unitsql.QueryHandler
	UnitsLink                unitslinkql.QueryHandler
}

// NewQuery wires every query handler in the domain.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler {
	return QueryHandler{
		Fees:                     feesql.NewQuery(gql),
		Licences:                 licencesql.NewQuery(gql),
		LosDiscounts:             losdiscountsql.NewQuery(gql),
		Medias:                   mediasql.NewQuery(gql),
		Policies:                 policiesql.NewQuery(gql),
		Properties:               propertiesql.NewQuery(gql),
		RateOverrides:            rateoverridesql.NewQuery(gql),
		Taxes:                    taxesql.NewQuery(gql),
		UnitApplicablePromoCodes: unitapplicablepromocodesql.NewQuery(gql),
		UnitMedias:               unitmediasql.NewQuery(gql),
		Units:                    unitsql.NewQuery(gql),
		UnitsLink:                unitslinkql.NewQuery(gql),
	}
}

// MutationHandler aggregates mutation handlers for the propertyql domain.
type MutationHandler struct {
	Fees                     feesql.MutationHandler
	Licences                 licencesql.MutationHandler
	LosDiscounts             losdiscountsql.MutationHandler
	Medias                   mediasql.MutationHandler
	Policies                 policiesql.MutationHandler
	Properties               propertiesql.MutationHandler
	RateOverrides            rateoverridesql.MutationHandler
	Taxes                    taxesql.MutationHandler
	UnitApplicablePromoCodes unitapplicablepromocodesql.MutationHandler
	UnitMedias               unitmediasql.MutationHandler
	Units                    unitsql.MutationHandler
	UnitsLink                unitslinkql.MutationHandler
}

// NewMutation wires every mutation handler in the domain.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler {
	return MutationHandler{
		Fees:                     feesql.NewMutation(gql),
		Licences:                 licencesql.NewMutation(gql),
		LosDiscounts:             losdiscountsql.NewMutation(gql),
		Medias:                   mediasql.NewMutation(gql),
		Policies:                 policiesql.NewMutation(gql),
		Properties:               propertiesql.NewMutation(gql),
		RateOverrides:            rateoverridesql.NewMutation(gql),
		Taxes:                    taxesql.NewMutation(gql),
		UnitApplicablePromoCodes: unitapplicablepromocodesql.NewMutation(gql),
		UnitMedias:               unitmediasql.NewMutation(gql),
		Units:                    unitsql.NewMutation(gql),
		UnitsLink:                unitslinkql.NewMutation(gql),
	}
}

// SubscriptionHandler aggregates subscription handlers for the propertyql domain.
type SubscriptionHandler struct {
	Fees                     feesql.SubscriptionHandler
	Licences                 licencesql.SubscriptionHandler
	LosDiscounts             losdiscountsql.SubscriptionHandler
	Medias                   mediasql.SubscriptionHandler
	Policies                 policiesql.SubscriptionHandler
	Properties               propertiesql.SubscriptionHandler
	RateOverrides            rateoverridesql.SubscriptionHandler
	Taxes                    taxesql.SubscriptionHandler
	UnitApplicablePromoCodes unitapplicablepromocodesql.SubscriptionHandler
	UnitMedias               unitmediasql.SubscriptionHandler
	Units                    unitsql.SubscriptionHandler
	UnitsLink                unitslinkql.SubscriptionHandler
}

// NewSubscription wires every subscription handler in the domain.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return SubscriptionHandler{
		Fees:                     feesql.NewSubscription(gql),
		Licences:                 licencesql.NewSubscription(gql),
		LosDiscounts:             losdiscountsql.NewSubscription(gql),
		Medias:                   mediasql.NewSubscription(gql),
		Policies:                 policiesql.NewSubscription(gql),
		Properties:               propertiesql.NewSubscription(gql),
		RateOverrides:            rateoverridesql.NewSubscription(gql),
		Taxes:                    taxesql.NewSubscription(gql),
		UnitApplicablePromoCodes: unitapplicablepromocodesql.NewSubscription(gql),
		UnitMedias:               unitmediasql.NewSubscription(gql),
		Units:                    unitsql.NewSubscription(gql),
		UnitsLink:                unitslinkql.NewSubscription(gql),
	}
}
