// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  schemaql
//
// orm — https://github.com/the-protobuf-project/orm

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CommonMoneys is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type CommonMoneys struct {
	// CurrencyCode selects the "currencyCode" field; nil when the column is NULL.
	CurrencyCode *string `graphql:"currencyCode"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Nanos selects the "nanos" field; nil when the column is NULL.
	Nanos *int32 `graphql:"nanos"`
	// Units selects the "units" field; nil when the column is NULL.
	Units *graphql.Int64 `graphql:"units"`
}

// CommonMoneysAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type CommonMoneysAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// CurrencyCode selects the "currencyCode" field.
	CurrencyCode struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"currencyCode"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Nanos selects the "nanos" field.
	Nanos struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"nanos"`
	// Units selects the "units" field.
	Units struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *graphql.Int64 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *graphql.Int64 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *graphql.Int64 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *graphql.Int64 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *graphql.Int64 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Bigdecimal `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"units"`
}

// DeleteCommonMoneysByIdResponse — Responses from the 'delete_common_moneys_by_id' procedure
type DeleteCommonMoneysByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CurrencyCode selects the "currencyCode" field; nil when the column is NULL.
		CurrencyCode *string `graphql:"currencyCode"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Nanos selects the "nanos" field; nil when the column is NULL.
		Nanos *int32 `graphql:"nanos"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *graphql.Int64 `graphql:"units"`
	} `graphql:"returning"`
}

// InsertCommonMoneysResponse — Responses from the 'insert_common_moneys' procedure
type InsertCommonMoneysResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CurrencyCode selects the "currencyCode" field; nil when the column is NULL.
		CurrencyCode *string `graphql:"currencyCode"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Nanos selects the "nanos" field; nil when the column is NULL.
		Nanos *int32 `graphql:"nanos"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *graphql.Int64 `graphql:"units"`
	} `graphql:"returning"`
}

// UpdateCommonMoneysByIdResponse — Responses from the 'update_common_moneys_by_id' procedure
type UpdateCommonMoneysByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CurrencyCode selects the "currencyCode" field; nil when the column is NULL.
		CurrencyCode *string `graphql:"currencyCode"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Nanos selects the "nanos" field; nil when the column is NULL.
		Nanos *int32 `graphql:"nanos"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *graphql.Int64 `graphql:"units"`
	} `graphql:"returning"`
}
