// Code generated by generateql. DO NOT EDIT.

package schemaql

// UpdateCommonPostalAddressByIdResponse is the UpdateCommonPostalAddressByIdResponse model.
type UpdateCommonPostalAddressByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AddressLines       []*string `graphql:"addressLines"`
		AdministrativeArea *string   `graphql:"administrativeArea"`
		Id                 string    `graphql:"id"`
		LanguageCode       *string   `graphql:"languageCode"`
		Locality           *string   `graphql:"locality"`
		Organization       *string   `graphql:"organization"`
		PostalCode         *string   `graphql:"postalCode"`
		Recipients         []*string `graphql:"recipients"`
		RegionCode         *string   `graphql:"regionCode"`
		Revision           *int32    `graphql:"revision"`
		SortingCode        *string   `graphql:"sortingCode"`
		Sublocality        *string   `graphql:"sublocality"`
	} `graphql:"returning"`
}
