// Code generated by protoc-gen-orm. DO NOT EDIT.

package unitapplicablepromocodesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyUnitApplicablePromoCodesByIdResponse = schemaql.DeletePropertyUnitApplicablePromoCodesByIdResponse
type InsertPropertyUnitApplicablePromoCodesResponse = schemaql.InsertPropertyUnitApplicablePromoCodesResponse
type PropertyUnitApplicablePromoCodes = schemaql.PropertyUnitApplicablePromoCodes
type PropertyUnitApplicablePromoCodesAggExp = schemaql.PropertyUnitApplicablePromoCodesAggExp
type UpdatePropertyUnitApplicablePromoCodesByIdResponse = schemaql.UpdatePropertyUnitApplicablePromoCodesByIdResponse
