// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  propertiesql
//
// orm — https://github.com/the-protobuf-project/orm

package propertiesql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyProperties row.
type CreateInput struct {
	// AddressId sets the "addressId" column; the zero value is omitted (column default / NULL).
	AddressId string `json:"addressId,omitzero"`
	// Attributes sets the "attributes" column; the zero value is omitted (column default / NULL).
	Attributes json.RawMessage `json:"attributes,omitzero"`
	// CreateTime sets the "createTime" column; the zero value is omitted (column default / NULL).
	CreateTime string `json:"createTime,omitzero"`
	// Description sets the "description" column; the zero value is omitted (column default / NULL).
	Description string `json:"description,omitzero"`
	// DisplayName sets the "displayName" column (required).
	DisplayName string `json:"displayName"`
	// Etag sets the "etag" column; the zero value is omitted (column default / NULL).
	Etag string `json:"etag,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Name sets the "name" column (required).
	Name string `json:"name"`
	// Organisation sets the "organisation" column (required).
	Organisation string `json:"organisation"`
	// PolicyId sets the "policyId" column; the zero value is omitted (column default / NULL).
	PolicyId string `json:"policyId,omitzero"`
	// State sets the "state" column; the zero value is omitted (column default / NULL).
	State string `json:"state,omitzero"`
	// Tags sets the "tags" column; the zero value is omitted (column default / NULL).
	Tags []*string `json:"tags,omitzero"`
	// TimeZone sets the "timeZone" column (required).
	TimeZone string `json:"timeZone"`
	// UpdateTime sets the "updateTime" column (required).
	UpdateTime string `json:"updateTime"`
}

// UpdateInput holds the fields to change on a PropertyProperties row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'address_id' column in the 'property_properties' collection.
	AddressId graphql.Nullable[string] `json:"addressId"`
	// Update the 'attributes' column in the 'property_properties' collection.
	Attributes graphql.Nullable[json.RawMessage] `json:"attributes"`
	// Update the 'create_time' column in the 'property_properties' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'description' column in the 'property_properties' collection.
	Description graphql.Nullable[string] `json:"description"`
	// Update the 'display_name' column in the 'property_properties' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'etag' column in the 'property_properties' collection.
	Etag graphql.Nullable[string] `json:"etag"`
	// Update the 'id' column in the 'property_properties' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'name' column in the 'property_properties' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'organisation' column in the 'property_properties' collection.
	Organisation graphql.Nullable[string] `json:"organisation"`
	// Update the 'policy_id' column in the 'property_properties' collection.
	PolicyId graphql.Nullable[string] `json:"policyId"`
	// Update the 'state' column in the 'property_properties' collection.
	State graphql.Nullable[string] `json:"state"`
	// Update the 'tags' column in the 'property_properties' collection.
	Tags graphql.Nullable[[]*string] `json:"tags"`
	// Update the 'time_zone' column in the 'property_properties' collection.
	TimeZone graphql.Nullable[string] `json:"timeZone"`
	// Update the 'update_time' column in the 'property_properties' collection.
	UpdateTime graphql.Nullable[string] `json:"updateTime"`
}
