// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  propertiesql
//
// orm — https://github.com/the-protobuf-project/orm

package propertiesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyPropertiesByIdResponse = schemaql.DeletePropertyPropertiesByIdResponse
type InsertPropertyPropertiesResponse = schemaql.InsertPropertyPropertiesResponse
type PropertyProperties = schemaql.PropertyProperties
type PropertyPropertiesAggExp = schemaql.PropertyPropertiesAggExp
type UpdatePropertyPropertiesByIdResponse = schemaql.UpdatePropertyPropertiesByIdResponse
