// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  guestsql
//
// orm — https://github.com/the-protobuf-project/orm

package guestsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/identityql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteIdentityGuestsByBookingIdResponse = schemaql.DeleteIdentityGuestsByBookingIdResponse
type DeleteIdentityGuestsByIdResponse = schemaql.DeleteIdentityGuestsByIdResponse
type IdentityGuests = schemaql.IdentityGuests
type IdentityGuestsAggExp = schemaql.IdentityGuestsAggExp
type InsertIdentityGuestsResponse = schemaql.InsertIdentityGuestsResponse
type UpdateIdentityGuestsByIdResponse = schemaql.UpdateIdentityGuestsByIdResponse
