// Code generated by protoc-gen-orm. DO NOT EDIT.

package guestsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/identityql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteIdentityGuestsByBookingIdResponse = schemaql.DeleteIdentityGuestsByBookingIdResponse
type DeleteIdentityGuestsByIdResponse = schemaql.DeleteIdentityGuestsByIdResponse
type IdentityGuests = schemaql.IdentityGuests
type IdentityGuestsAggExp = schemaql.IdentityGuestsAggExp
type InsertIdentityGuestsResponse = schemaql.InsertIdentityGuestsResponse
type UpdateIdentityGuestsByIdResponse = schemaql.UpdateIdentityGuestsByIdResponse
