// Code generated by generateql. DO NOT EDIT.

package scopeapplicableresourcesql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeScopeApplicableResources row.
type CreateInput struct {
	Id         string `json:"id"`
	ResourceId string `json:"resourceId"`
	ScopeId    string `json:"scopeId"`
}

// UpdateInput holds the fields to change on a PromocodeScopeApplicableResources row; each set field becomes a column update.
type UpdateInput struct {
	Id         graphql.Nullable[string] `json:"id"`
	ResourceId graphql.Nullable[string] `json:"resourceId"`
	ScopeId    graphql.Nullable[string] `json:"scopeId"`
}
