// Code generated by generateql. DO NOT EDIT.

package licencesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyLicencesByIdResponse = schemaql.DeletePropertyLicencesByIdResponse
type InsertPropertyLicencesResponse = schemaql.InsertPropertyLicencesResponse
type PropertyLicences = schemaql.PropertyLicences
type PropertyLicencesAggExp = schemaql.PropertyLicencesAggExp
type UpdatePropertyLicencesByIdResponse = schemaql.UpdatePropertyLicencesByIdResponse
