// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  licencesql
//
// orm — https://github.com/the-protobuf-project/orm

package licencesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyLicencesByIdResponse = schemaql.DeletePropertyLicencesByIdResponse
type InsertPropertyLicencesResponse = schemaql.InsertPropertyLicencesResponse
type PropertyLicences = schemaql.PropertyLicences
type PropertyLicencesAggExp = schemaql.PropertyLicencesAggExp
type UpdatePropertyLicencesByIdResponse = schemaql.UpdatePropertyLicencesByIdResponse
