// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// GraphQL adapters over the generated client — same repository surface as the gorm adapters.
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"context"
	"errors"
	"fmt"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/promocode"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/redemptionsql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/resourceql"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/promocode/v1/promocodepbv1"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// mapGraphQLErr translates the client's errors onto the repox sentinels.
func mapGraphQLErr(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, graphql.ErrConflict):
		return repox.ErrConflict
	default:
		return err
	}
}

// GraphQLPromoCodeRepository is the GraphQL adapter of PromoCodeRepository
// over the generated client: the same flat CRUD the gorm adapter implements,
// against Promocode.Resource. Exported fields are the Tier-2 seam.
type GraphQLPromoCodeRepository struct {
	Svc   *freebusyql.Service
	Hooks PromoCodeHooks
	// ListOverrides substitute the generated dispatch for single filter fields.
	ListOverrides map[string]filterx.GraphQLHandler
}

// NewGraphQLPromoCodeRepository returns the GraphQL adapter bound to svc.
func NewGraphQLPromoCodeRepository(svc *freebusyql.Service) *GraphQLPromoCodeRepository {
	return &GraphQLPromoCodeRepository{Svc: svc}
}

// Create persists in and returns the stored record.
func (r *GraphQLPromoCodeRepository) Create(ctx context.Context, in *promocodepbv1.PromoCode) (*promocodepbv1.PromoCode, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "promoCodes")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*promocodepbv1.PromoCode)
	in.Name = FormatPromoCodeName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	ci := promoCodeToCreateInput(in)
	ci.Id = id
	ci.Etag = repox.NewULID()
	now := tsToStr(timestamppb.New(time.Now().UTC()))
	ci.CreateTime = now
	ci.UpdateTime = now
	if v := in.GetWindow(); v != nil {
		vi := promocodeRedemptionWindowToCreateInput(v)
		vi.Id = repox.NewULID()
		if _, err := r.Svc.Mutation.Promocode.RedemptionWindows.Create(ctx, vi); err != nil {
			return nil, mapGraphQLErr(err)
		}
		ci.WindowId = vi.Id
	}
	if v := in.GetLimits(); v != nil {
		vi := promocodeUsageLimitsToCreateInput(v)
		vi.Id = repox.NewULID()
		if _, err := r.Svc.Mutation.Promocode.UsageLimits.Create(ctx, vi); err != nil {
			return nil, mapGraphQLErr(err)
		}
		ci.LimitsId = vi.Id
	}
	if _, err := r.Svc.Mutation.Promocode.Resource.Create(ctx, ci); err != nil {
		return nil, mapGraphQLErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GraphQLPromoCodeRepository) Get(ctx context.Context, name string) (*promocodepbv1.PromoCode, error) {
	ids, err := repox.SplitName(name, "promoCodes")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method
// re-reads through.
func (r *GraphQLPromoCodeRepository) get(ctx context.Context, id string) (*promocodepbv1.PromoCode, error) {
	row, err := r.Svc.Query.Promocode.Resource.Get(ctx, id)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if row == nil {
		return nil, repox.ErrNotFound
	}
	return r.toProto(ctx, row)
}

// toProto converts a loaded row, hydrating value objects through their
// stored references, and runs the AfterRead hook.
func (r *GraphQLPromoCodeRepository) toProto(ctx context.Context, row *resourceql.PromocodeResource) (*promocodepbv1.PromoCode, error) {
	out := promoCodeFromRow(row)
	if id := repox.Deref(row.WindowId); id != "" {
		w, err := r.Svc.Query.Promocode.RedemptionWindows.Get(ctx, id)
		if err != nil {
			return nil, mapGraphQLErr(err)
		}
		if w != nil {
			out.Window = promocodeRedemptionWindowFromRow(w)
		}
	}
	if id := repox.Deref(row.LimitsId); id != "" {
		w, err := r.Svc.Query.Promocode.UsageLimits.Get(ctx, id)
		if err != nil {
			return nil, mapGraphQLErr(err)
		}
		if w != nil {
			out.Limits = promocodeUsageLimitsFromRow(w)
		}
	}
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GraphQLPromoCodeRepository) List(ctx context.Context, in repox.ListInput) ([]*promocodepbv1.PromoCode, string, error) {
	return r.list(ctx, in)
}

func (r *GraphQLPromoCodeRepository) list(ctx context.Context, in repox.ListInput, scope ...graphql.Predicate) ([]*promocodepbv1.PromoCode, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Hasura[resourceql.PromocodeResource](promocode.PromoCodeFilterSpec, r.Svc.Query.Promocode.Resource).Scope(scope...)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*promocodepbv1.PromoCode, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. When in.Etag is set the write is guarded server-side
// (UpdateIfMatch); a stale etag returns repox.ErrConflict.
func (r *GraphQLPromoCodeRepository) Update(ctx context.Context, in *promocodepbv1.PromoCode, paths []string) (*promocodepbv1.PromoCode, error) {
	ids, err := repox.SplitName(in.GetName(), "promoCodes")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	row, err := r.Svc.Query.Promocode.Resource.Get(ctx, id)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if row == nil {
		return nil, repox.ErrNotFound
	}
	var staleWindow string
	var staleLimits string
	existingPB := promoCodeFromRow(row)
	merged := proto.Clone(existingPB).(*promocodepbv1.PromoCode)
	applyPromoCodeMask(merged, in, paths)
	if h := r.Hooks.BeforeUpdate; h != nil {
		if err := h(ctx, existingPB, merged, paths); err != nil {
			return nil, err
		}
	}
	patch := promoCodeToUpdatePatch(merged)
	patch.Etag = graphql.Value(repox.NewULID())
	patch.UpdateTime = graphql.Value(tsToStr(timestamppb.New(time.Now().UTC())))
	if repox.GroupTouched(paths, "window") {
		staleWindow = repox.Deref(row.WindowId)
		patch.WindowId = graphql.Null[string]()
		if v := merged.GetWindow(); v != nil {
			vi := promocodeRedemptionWindowToCreateInput(v)
			vi.Id = repox.NewULID()
			if _, err := r.Svc.Mutation.Promocode.RedemptionWindows.Create(ctx, vi); err != nil {
				return nil, mapGraphQLErr(err)
			}
			patch.WindowId = graphql.Value(vi.Id)
		}
	}
	if repox.GroupTouched(paths, "limits") {
		staleLimits = repox.Deref(row.LimitsId)
		patch.LimitsId = graphql.Null[string]()
		if v := merged.GetLimits(); v != nil {
			vi := promocodeUsageLimitsToCreateInput(v)
			vi.Id = repox.NewULID()
			if _, err := r.Svc.Mutation.Promocode.UsageLimits.Create(ctx, vi); err != nil {
				return nil, mapGraphQLErr(err)
			}
			patch.LimitsId = graphql.Value(vi.Id)
		}
	}
	if in.GetEtag() != "" {
		if _, err := r.Svc.Mutation.Promocode.Resource.UpdateIfMatch(ctx, id, patch, resourceql.Etag.Eq(in.GetEtag())); err != nil {
			return nil, mapGraphQLErr(err)
		}
		if staleWindow != "" {
			if _, err := r.Svc.Mutation.Promocode.RedemptionWindows.Delete(ctx, staleWindow); err != nil {
				return nil, mapGraphQLErr(err)
			}
		}
		if staleLimits != "" {
			if _, err := r.Svc.Mutation.Promocode.UsageLimits.Delete(ctx, staleLimits); err != nil {
				return nil, mapGraphQLErr(err)
			}
		}
		return r.get(ctx, id)
	}
	resp, err := r.Svc.Mutation.Promocode.Resource.Update(ctx, id, patch)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if resp.AffectedRows == 0 {
		return nil, repox.ErrNotFound
	}
	if staleWindow != "" {
		if _, err := r.Svc.Mutation.Promocode.RedemptionWindows.Delete(ctx, staleWindow); err != nil {
			return nil, mapGraphQLErr(err)
		}
	}
	if staleLimits != "" {
		if _, err := r.Svc.Mutation.Promocode.UsageLimits.Delete(ctx, staleLimits); err != nil {
			return nil, mapGraphQLErr(err)
		}
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GraphQLPromoCodeRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "promoCodes")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	resp, err := r.Svc.Mutation.Promocode.Resource.Delete(ctx, id)
	if err != nil {
		return mapGraphQLErr(err)
	}
	if resp.AffectedRows == 0 {
		return repox.ErrNotFound
	}
	for i := range resp.Returning {
		if id := repox.Deref(resp.Returning[i].WindowId); id != "" {
			if _, err := r.Svc.Mutation.Promocode.RedemptionWindows.Delete(ctx, id); err != nil {
				return mapGraphQLErr(err)
			}
		}
	}
	for i := range resp.Returning {
		if id := repox.Deref(resp.Returning[i].LimitsId); id != "" {
			if _, err := r.Svc.Mutation.Promocode.UsageLimits.Delete(ctx, id); err != nil {
				return mapGraphQLErr(err)
			}
		}
	}
	return nil
}

// Compile-time proof the adapter satisfies the interface.
var _ PromoCodeRepository = (*GraphQLPromoCodeRepository)(nil)

// GraphQLRedemptionRepository is the GraphQL adapter of RedemptionRepository
// over the generated client: the same flat CRUD the gorm adapter implements,
// against Promocode.Redemptions. Exported fields are the Tier-2 seam.
type GraphQLRedemptionRepository struct {
	Svc   *freebusyql.Service
	Hooks RedemptionHooks
	// ListOverrides substitute the generated dispatch for single filter fields.
	ListOverrides map[string]filterx.GraphQLHandler
}

// NewGraphQLRedemptionRepository returns the GraphQL adapter bound to svc.
func NewGraphQLRedemptionRepository(svc *freebusyql.Service) *GraphQLRedemptionRepository {
	return &GraphQLRedemptionRepository{Svc: svc}
}

// Create persists in under parent and returns the stored record.
func (r *GraphQLRedemptionRepository) Create(ctx context.Context, parent string, in *promocodepbv1.Redemption) (*promocodepbv1.Redemption, error) {
	parentIDs, err := repox.SplitName(parent, "promoCodes")
	if err != nil {
		return nil, err
	}
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "promoCodes", "redemptions")
		if err != nil {
			return nil, err
		}
		for i := range parentIDs {
			if ids[i] != parentIDs[i] {
				return nil, fmt.Errorf("%w: name %q is not under parent %q", repox.ErrInvalidArgument, in.GetName(), parent)
			}
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*promocodepbv1.Redemption)
	in.Name = FormatRedemptionName(parentIDs[0], id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	ci := redemptionToCreateInput(in)
	ci.Id = id
	ci.PromoCodeId = parentIDs[0]
	if v := in.GetAmountApplied(); v != nil {
		vi := commonMoneyToCreateInput(v)
		vi.Id = repox.NewULID()
		if _, err := r.Svc.Mutation.Common.Moneys.Create(ctx, vi); err != nil {
			return nil, mapGraphQLErr(err)
		}
		ci.AmountAppliedId = vi.Id
	}
	if _, err := r.Svc.Mutation.Promocode.Redemptions.Create(ctx, ci); err != nil {
		return nil, mapGraphQLErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GraphQLRedemptionRepository) Get(ctx context.Context, name string) (*promocodepbv1.Redemption, error) {
	ids, err := repox.SplitName(name, "promoCodes", "redemptions")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method
// re-reads through.
func (r *GraphQLRedemptionRepository) get(ctx context.Context, id string) (*promocodepbv1.Redemption, error) {
	row, err := r.Svc.Query.Promocode.Redemptions.Get(ctx, id)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if row == nil {
		return nil, repox.ErrNotFound
	}
	return r.toProto(ctx, row)
}

// toProto converts a loaded row, hydrating value objects through their
// stored references, and runs the AfterRead hook.
func (r *GraphQLRedemptionRepository) toProto(ctx context.Context, row *redemptionsql.PromocodeRedemptions) (*promocodepbv1.Redemption, error) {
	out := redemptionFromRow(row)
	if id := repox.Deref(row.AmountAppliedId); id != "" {
		w, err := r.Svc.Query.Common.Moneys.Get(ctx, id)
		if err != nil {
			return nil, mapGraphQLErr(err)
		}
		if w != nil {
			out.AmountApplied = commonMoneyFromRow(w)
		}
	}
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records under parent.
func (r *GraphQLRedemptionRepository) List(ctx context.Context, parent string, in repox.ListInput) ([]*promocodepbv1.Redemption, string, error) {
	parentIDs, err := repox.SplitName(parent, "promoCodes")
	if err != nil {
		return nil, "", err
	}
	return r.list(ctx, in, redemptionsql.PromoCodeId.Eq(parentIDs[len(parentIDs)-1]))
}

func (r *GraphQLRedemptionRepository) list(ctx context.Context, in repox.ListInput, scope ...graphql.Predicate) ([]*promocodepbv1.Redemption, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Hasura[redemptionsql.PromocodeRedemptions](promocode.RedemptionFilterSpec, r.Svc.Query.Promocode.Redemptions).Scope(scope...)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*promocodepbv1.Redemption, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. When in.Etag is set the write is guarded server-side
// (UpdateIfMatch); a stale etag returns repox.ErrConflict.
func (r *GraphQLRedemptionRepository) Update(ctx context.Context, in *promocodepbv1.Redemption, paths []string) (*promocodepbv1.Redemption, error) {
	ids, err := repox.SplitName(in.GetName(), "promoCodes", "redemptions")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	row, err := r.Svc.Query.Promocode.Redemptions.Get(ctx, id)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if row == nil {
		return nil, repox.ErrNotFound
	}
	var staleAmountApplied string
	existingPB := redemptionFromRow(row)
	merged := proto.Clone(existingPB).(*promocodepbv1.Redemption)
	applyRedemptionMask(merged, in, paths)
	if h := r.Hooks.BeforeUpdate; h != nil {
		if err := h(ctx, existingPB, merged, paths); err != nil {
			return nil, err
		}
	}
	patch := redemptionToUpdatePatch(merged)
	if repox.GroupTouched(paths, "amount_applied") {
		staleAmountApplied = repox.Deref(row.AmountAppliedId)
		patch.AmountAppliedId = graphql.Null[string]()
		if v := merged.GetAmountApplied(); v != nil {
			vi := commonMoneyToCreateInput(v)
			vi.Id = repox.NewULID()
			if _, err := r.Svc.Mutation.Common.Moneys.Create(ctx, vi); err != nil {
				return nil, mapGraphQLErr(err)
			}
			patch.AmountAppliedId = graphql.Value(vi.Id)
		}
	}
	resp, err := r.Svc.Mutation.Promocode.Redemptions.Update(ctx, id, patch)
	if err != nil {
		return nil, mapGraphQLErr(err)
	}
	if resp.AffectedRows == 0 {
		return nil, repox.ErrNotFound
	}
	if staleAmountApplied != "" {
		if _, err := r.Svc.Mutation.Common.Moneys.Delete(ctx, staleAmountApplied); err != nil {
			return nil, mapGraphQLErr(err)
		}
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GraphQLRedemptionRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "promoCodes", "redemptions")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	resp, err := r.Svc.Mutation.Promocode.Redemptions.Delete(ctx, id)
	if err != nil {
		return mapGraphQLErr(err)
	}
	if resp.AffectedRows == 0 {
		return repox.ErrNotFound
	}
	for i := range resp.Returning {
		if id := repox.Deref(resp.Returning[i].AmountAppliedId); id != "" {
			if _, err := r.Svc.Mutation.Common.Moneys.Delete(ctx, id); err != nil {
				return mapGraphQLErr(err)
			}
		}
	}
	return nil
}

// Compile-time proof the adapter satisfies the interface.
var _ RedemptionRepository = (*GraphQLRedemptionRepository)(nil)
