// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// Field-mask merge functions shared by every adapter of this schema.
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/promocode/v1/promocodepbv1"
)

// applyPromoCodeMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyPromoCodeMask(merged, in *promocodepbv1.PromoCode, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "code") {
		merged.Code = in.GetCode()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "description") {
		merged.Description = in.GetDescription()
	}
	if repox.InMask(paths, "disabled") {
		merged.Disabled = in.GetDisabled()
	}
	if repox.GroupTouched(paths, "window") {
		merged.Window = in.GetWindow()
	}
	if repox.GroupTouched(paths, "limits") {
		merged.Limits = in.GetLimits()
	}
}

// applyRedemptionMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyRedemptionMask(merged, in *promocodepbv1.Redemption, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "customer") {
		merged.Customer = in.GetCustomer()
	}
	if repox.InMask(paths, "booking") {
		merged.Booking = in.GetBooking()
	}
	if repox.GroupTouched(paths, "amount_applied") {
		merged.AmountApplied = in.GetAmountApplied()
	}
}
