// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
// source: freebusy/promocode/v1/promocode.proto
//
// database: freebusy
// schema:   promocode
//
// AIP resource-name codecs for this schema's repositories.
//
// orm — https://github.com/the-protobuf-project/orm

package promocode

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatPromoCodeName builds "promoCodes/{promo_code}" from bare ids.
func FormatPromoCodeName(promoCode string) string {
	return "promoCodes" + "/" + promoCode
}

// ParsePromoCodeName splits a "promoCodes/{promo_code}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParsePromoCodeName(name string) (promoCode string, err error) {
	ids, err := repox.SplitName(name, "promoCodes")
	if err != nil {
		return
	}
	promoCode = ids[0]
	return
}

// FormatRedemptionName builds "promoCodes/{promo_code}/redemptions/{redemption}" from bare ids.
func FormatRedemptionName(promoCode, redemption string) string {
	return "promoCodes" + "/" + promoCode + "/" + "redemptions" + "/" + redemption
}

// ParseRedemptionName splits a "promoCodes/{promo_code}/redemptions/{redemption}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseRedemptionName(name string) (promoCode, redemption string, err error) {
	ids, err := repox.SplitName(name, "promoCodes", "redemptions")
	if err != nil {
		return
	}
	promoCode = ids[0]
	redemption = ids[1]
	return
}
