// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  scopeapplicablepropertiesql
//
// orm — https://github.com/the-protobuf-project/orm

package scopeapplicablepropertiesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeScopeApplicableProperties row.
type CreateInput struct {
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// PropertyId sets the "propertyId" column (required).
	PropertyId string `json:"propertyId"`
	// ScopeId sets the "scopeId" column (required).
	ScopeId string `json:"scopeId"`
}

// UpdateInput holds the fields to change on a PromocodeScopeApplicableProperties row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'id' column in the 'promocode_scope_applicable_properties' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'property_id' column in the 'promocode_scope_applicable_properties' collection.
	PropertyId graphql.Nullable[string] `json:"propertyId"`
	// Update the 'scope_id' column in the 'promocode_scope_applicable_properties' collection.
	ScopeId graphql.Nullable[string] `json:"scopeId"`
}
