// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  scopeapplicablepropertiesql
//
// orm — https://github.com/the-protobuf-project/orm

package scopeapplicablepropertiesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeScopeApplicablePropertiesByIdResponse = schemaql.DeletePromocodeScopeApplicablePropertiesByIdResponse
type InsertPromocodeScopeApplicablePropertiesResponse = schemaql.InsertPromocodeScopeApplicablePropertiesResponse
type PromocodeScopeApplicableProperties = schemaql.PromocodeScopeApplicableProperties
type PromocodeScopeApplicablePropertiesAggExp = schemaql.PromocodeScopeApplicablePropertiesAggExp
type UpdatePromocodeScopeApplicablePropertiesByIdResponse = schemaql.UpdatePromocodeScopeApplicablePropertiesByIdResponse
