// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  idempotencykeysql
//
// orm — https://github.com/the-protobuf-project/orm

package idempotencykeysql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one SharedIdempotencyKeys row.
type CreateInput struct {
	// CreateTime sets the "createTime" column; the zero value is omitted (column default / NULL).
	CreateTime string `json:"createTime,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Method sets the "method" column (required).
	Method string `json:"method"`
	// Name sets the "name" column (required).
	Name string `json:"name"`
	// RequestId sets the "requestId" column (required).
	RequestId string `json:"requestId"`
	// Response sets the "response" column; the zero value is omitted (column default / NULL).
	Response string `json:"response,omitzero"`
	// State sets the "state" column; the zero value is omitted (column default / NULL).
	State string `json:"state,omitzero"`
	// UpdateTime sets the "updateTime" column (required).
	UpdateTime string `json:"updateTime"`
}

// UpdateInput holds the fields to change on a SharedIdempotencyKeys row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'create_time' column in the 'shared_idempotency_keys' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'id' column in the 'shared_idempotency_keys' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'method' column in the 'shared_idempotency_keys' collection.
	Method graphql.Nullable[string] `json:"method"`
	// Update the 'name' column in the 'shared_idempotency_keys' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'request_id' column in the 'shared_idempotency_keys' collection.
	RequestId graphql.Nullable[string] `json:"requestId"`
	// Update the 'response' column in the 'shared_idempotency_keys' collection.
	Response graphql.Nullable[string] `json:"response"`
	// Update the 'state' column in the 'shared_idempotency_keys' collection.
	State graphql.Nullable[string] `json:"state"`
	// Update the 'update_time' column in the 'shared_idempotency_keys' collection.
	UpdateTime graphql.Nullable[string] `json:"updateTime"`
}
