// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  idempotencykeysql
//
// orm — https://github.com/the-protobuf-project/orm

package idempotencykeysql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteSharedIdempotencyKeysByIdResponse — Responses from the 'delete_shared_idempotency_keys_by_id' procedure
type DeleteSharedIdempotencyKeysByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Method selects the "method" field.
		Method string `graphql:"method"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// RequestId selects the "requestId" field.
		RequestId string `graphql:"requestId"`
		// Response selects the "response" field; nil when the column is NULL.
		Response *string `graphql:"response"`
		// State selects the "state" field.
		State string `graphql:"state"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// InsertSharedIdempotencyKeysResponse — Responses from the 'insert_shared_idempotency_keys' procedure
type InsertSharedIdempotencyKeysResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Method selects the "method" field.
		Method string `graphql:"method"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// RequestId selects the "requestId" field.
		RequestId string `graphql:"requestId"`
		// Response selects the "response" field; nil when the column is NULL.
		Response *string `graphql:"response"`
		// State selects the "state" field.
		State string `graphql:"state"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// SharedIdempotencyKeys is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type SharedIdempotencyKeys struct {
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Method selects the "method" field.
	Method string `graphql:"method"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// RequestId selects the "requestId" field.
	RequestId string `graphql:"requestId"`
	// Response selects the "response" field; nil when the column is NULL.
	Response *string `graphql:"response"`
	// State selects the "state" field.
	State string `graphql:"state"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime string `graphql:"updateTime"`
}

// SharedIdempotencyKeysAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type SharedIdempotencyKeysAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Method selects the "method" field.
	Method struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"method"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// RequestId selects the "requestId" field.
	RequestId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"requestId"`
	// Response selects the "response" field.
	Response struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"response"`
	// State selects the "state" field.
	State struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"state"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"updateTime"`
}

// UpdateSharedIdempotencyKeysByIdResponse — Responses from the 'update_shared_idempotency_keys_by_id' procedure
type UpdateSharedIdempotencyKeysByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Method selects the "method" field.
		Method string `graphql:"method"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// RequestId selects the "requestId" field.
		RequestId string `graphql:"requestId"`
		// Response selects the "response" field; nil when the column is NULL.
		Response *string `graphql:"response"`
		// State selects the "state" field.
		State string `graphql:"state"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}
