// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  idempotencykeysql
//
// orm — https://github.com/the-protobuf-project/orm

package idempotencykeysql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for SharedIdempotencyKeys. Build predicates like CreateTime.Eq(v) and combine
// them with And/Or/Not.
var (
	CreateTime = graphql.StringField{Col: "createTime"}
	Id         = graphql.StringField{Col: "id"}
	Method     = graphql.StringField{Col: "method"}
	Name       = graphql.StringField{Col: "name"}
	RequestId  = graphql.StringField{Col: "requestId"}
	Response   = graphql.StringField{Col: "response"}
	State      = graphql.StringField{Col: "state"}
	UpdateTime = graphql.StringField{Col: "updateTime"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
