// Code generated by protoc-gen-orm. DO NOT EDIT.

package unitmappingsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one ChannelUnitMappings row.
type CreateInput struct {
	ChannelId          string `json:"channelId"`
	CreateTime         string `json:"createTime"`
	Etag               string `json:"etag,omitzero"`
	ExternalRatePlanId string `json:"externalRatePlanId,omitzero"`
	ExternalRoomTypeId string `json:"externalRoomTypeId"`
	Id                 string `json:"id"`
	Name               string `json:"name"`
	State              string `json:"state,omitzero"`
	Unit               string `json:"unit"`
	UpdateTime         string `json:"updateTime"`
}

// UpdateInput holds the fields to change on a ChannelUnitMappings row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'channel_id' column in the 'channel_unit_mappings' collection.
	ChannelId graphql.Nullable[string] `json:"channelId"`
	// Update the 'create_time' column in the 'channel_unit_mappings' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'etag' column in the 'channel_unit_mappings' collection.
	Etag graphql.Nullable[string] `json:"etag"`
	// Update the 'external_rate_plan_id' column in the 'channel_unit_mappings' collection.
	ExternalRatePlanId graphql.Nullable[string] `json:"externalRatePlanId"`
	// Update the 'external_room_type_id' column in the 'channel_unit_mappings' collection.
	ExternalRoomTypeId graphql.Nullable[string] `json:"externalRoomTypeId"`
	// Update the 'id' column in the 'channel_unit_mappings' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'name' column in the 'channel_unit_mappings' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'state' column in the 'channel_unit_mappings' collection.
	State graphql.Nullable[string] `json:"state"`
	// Update the 'unit' column in the 'channel_unit_mappings' collection.
	Unit graphql.Nullable[string] `json:"unit"`
	// Update the 'update_time' column in the 'channel_unit_mappings' collection.
	UpdateTime graphql.Nullable[string] `json:"updateTime"`
}
