// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  membersql
//
// orm — https://github.com/the-protobuf-project/orm

package membersql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one OrganisationMembers row.
type CreateInput struct {
	// CreateTime sets the "createTime" column; the zero value is omitted (column default / NULL).
	CreateTime string `json:"createTime,omitzero"`
	// DisplayName sets the "displayName" column; the zero value is omitted (column default / NULL).
	DisplayName string `json:"displayName,omitzero"`
	// Email sets the "email" column (required).
	Email string `json:"email"`
	// Etag sets the "etag" column; the zero value is omitted (column default / NULL).
	Etag string `json:"etag,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Inviter sets the "inviter" column; the zero value is omitted (column default / NULL).
	Inviter string `json:"inviter,omitzero"`
	// Name sets the "name" column (required).
	Name string `json:"name"`
	// OrganisationId sets the "organisationId" column (required).
	OrganisationId string `json:"organisationId"`
	// Role sets the "role" column; the zero value is omitted (column default / NULL).
	Role string `json:"role,omitzero"`
	// State sets the "state" column; the zero value is omitted (column default / NULL).
	State string `json:"state,omitzero"`
	// UpdateTime sets the "updateTime" column (required).
	UpdateTime string `json:"updateTime"`
	// User sets the "user" column; the zero value is omitted (column default / NULL).
	User string `json:"user,omitzero"`
}

// UpdateInput holds the fields to change on a OrganisationMembers row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'create_time' column in the 'organisation_members' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'display_name' column in the 'organisation_members' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'email' column in the 'organisation_members' collection.
	Email graphql.Nullable[string] `json:"email"`
	// Update the 'etag' column in the 'organisation_members' collection.
	Etag graphql.Nullable[string] `json:"etag"`
	// Update the 'id' column in the 'organisation_members' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'inviter' column in the 'organisation_members' collection.
	Inviter graphql.Nullable[string] `json:"inviter"`
	// Update the 'name' column in the 'organisation_members' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'organisation_id' column in the 'organisation_members' collection.
	OrganisationId graphql.Nullable[string] `json:"organisationId"`
	// Update the 'role' column in the 'organisation_members' collection.
	Role graphql.Nullable[string] `json:"role"`
	// Update the 'state' column in the 'organisation_members' collection.
	State graphql.Nullable[string] `json:"state"`
	// Update the 'update_time' column in the 'organisation_members' collection.
	UpdateTime graphql.Nullable[string] `json:"updateTime"`
	// Update the 'user' column in the 'organisation_members' collection.
	User graphql.Nullable[string] `json:"user"`
}
