// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  resourceql
//
// orm — https://github.com/the-protobuf-project/orm

package resourceql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one OrganisationResource row.
type CreateInput struct {
	// BillingEmail sets the "billingEmail" column; the zero value is omitted (column default / NULL).
	BillingEmail string `json:"billingEmail,omitzero"`
	// CreateTime sets the "createTime" column; the zero value is omitted (column default / NULL).
	CreateTime string `json:"createTime,omitzero"`
	// DisplayName sets the "displayName" column (required).
	DisplayName string `json:"displayName"`
	// Etag sets the "etag" column; the zero value is omitted (column default / NULL).
	Etag string `json:"etag,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// MemberCount sets the "memberCount" column; the zero value is omitted (column default / NULL).
	MemberCount graphql.Int64 `json:"memberCount,omitzero"`
	// Name sets the "name" column (required).
	Name string `json:"name"`
	// Settings sets the "settings" column; the zero value is omitted (column default / NULL).
	Settings json.RawMessage `json:"settings,omitzero"`
	// Slug sets the "slug" column; the zero value is omitted (column default / NULL).
	Slug string `json:"slug,omitzero"`
	// State sets the "state" column; the zero value is omitted (column default / NULL).
	State string `json:"state,omitzero"`
	// UpdateTime sets the "updateTime" column (required).
	UpdateTime string `json:"updateTime"`
}

// UpdateInput holds the fields to change on a OrganisationResource row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'billing_email' column in the 'organisation_resource' collection.
	BillingEmail graphql.Nullable[string] `json:"billingEmail"`
	// Update the 'create_time' column in the 'organisation_resource' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'display_name' column in the 'organisation_resource' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'etag' column in the 'organisation_resource' collection.
	Etag graphql.Nullable[string] `json:"etag"`
	// Update the 'id' column in the 'organisation_resource' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'member_count' column in the 'organisation_resource' collection.
	MemberCount graphql.Nullable[graphql.Int64] `json:"memberCount"`
	// Update the 'name' column in the 'organisation_resource' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'settings' column in the 'organisation_resource' collection.
	Settings graphql.Nullable[json.RawMessage] `json:"settings"`
	// Update the 'slug' column in the 'organisation_resource' collection.
	Slug graphql.Nullable[string] `json:"slug"`
	// Update the 'state' column in the 'organisation_resource' collection.
	State graphql.Nullable[string] `json:"state"`
	// Update the 'update_time' column in the 'organisation_resource' collection.
	UpdateTime graphql.Nullable[string] `json:"updateTime"`
}
