// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  usersql
//
// orm — https://github.com/the-protobuf-project/orm

package usersql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/identityql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteIdentityUsersByIdResponse = schemaql.DeleteIdentityUsersByIdResponse
type IdentityUsers = schemaql.IdentityUsers
type IdentityUsersAggExp = schemaql.IdentityUsersAggExp
type InsertIdentityUsersResponse = schemaql.InsertIdentityUsersResponse
type UpdateIdentityUsersByIdResponse = schemaql.UpdateIdentityUsersByIdResponse
