// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  schemaql
//
// orm — https://github.com/the-protobuf-project/orm

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteScheduleBufferSettingsByIdResponse — Responses from the 'delete_schedule_buffer_settings_by_id' procedure
type DeleteScheduleBufferSettingsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EndDelta selects the "endDelta" field; nil when the column is NULL.
		EndDelta *string `graphql:"endDelta"`
		// Gap selects the "gap" field; nil when the column is NULL.
		Gap *string `graphql:"gap"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxAdvance selects the "maxAdvance" field; nil when the column is NULL.
		MaxAdvance *string `graphql:"maxAdvance"`
		// MinNotice selects the "minNotice" field; nil when the column is NULL.
		MinNotice *string `graphql:"minNotice"`
		// StartDelta selects the "startDelta" field; nil when the column is NULL.
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}

// InsertScheduleBufferSettingsResponse — Responses from the 'insert_schedule_buffer_settings' procedure
type InsertScheduleBufferSettingsResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EndDelta selects the "endDelta" field; nil when the column is NULL.
		EndDelta *string `graphql:"endDelta"`
		// Gap selects the "gap" field; nil when the column is NULL.
		Gap *string `graphql:"gap"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxAdvance selects the "maxAdvance" field; nil when the column is NULL.
		MaxAdvance *string `graphql:"maxAdvance"`
		// MinNotice selects the "minNotice" field; nil when the column is NULL.
		MinNotice *string `graphql:"minNotice"`
		// StartDelta selects the "startDelta" field; nil when the column is NULL.
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}

// ScheduleBufferSettings is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type ScheduleBufferSettings struct {
	// EndDelta selects the "endDelta" field; nil when the column is NULL.
	EndDelta *string `graphql:"endDelta"`
	// Gap selects the "gap" field; nil when the column is NULL.
	Gap *string `graphql:"gap"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// MaxAdvance selects the "maxAdvance" field; nil when the column is NULL.
	MaxAdvance *string `graphql:"maxAdvance"`
	// MinNotice selects the "minNotice" field; nil when the column is NULL.
	MinNotice *string `graphql:"minNotice"`
	// StartDelta selects the "startDelta" field; nil when the column is NULL.
	StartDelta *string `graphql:"startDelta"`
}

// ScheduleBufferSettingsAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type ScheduleBufferSettingsAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// EndDelta selects the "endDelta" field.
	EndDelta struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"endDelta"`
	// Gap selects the "gap" field.
	Gap struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"gap"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// MaxAdvance selects the "maxAdvance" field.
	MaxAdvance struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"maxAdvance"`
	// MinNotice selects the "minNotice" field.
	MinNotice struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"minNotice"`
	// StartDelta selects the "startDelta" field.
	StartDelta struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"startDelta"`
}

// UpdateScheduleBufferSettingsByIdResponse — Responses from the 'update_schedule_buffer_settings_by_id' procedure
type UpdateScheduleBufferSettingsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EndDelta selects the "endDelta" field; nil when the column is NULL.
		EndDelta *string `graphql:"endDelta"`
		// Gap selects the "gap" field; nil when the column is NULL.
		Gap *string `graphql:"gap"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxAdvance selects the "maxAdvance" field; nil when the column is NULL.
		MaxAdvance *string `graphql:"maxAdvance"`
		// MinNotice selects the "minNotice" field; nil when the column is NULL.
		MinNotice *string `graphql:"minNotice"`
		// StartDelta selects the "startDelta" field; nil when the column is NULL.
		StartDelta *string `graphql:"startDelta"`
	} `graphql:"returning"`
}
