// Code generated by generateql. DO NOT EDIT.

package schemaql

// ScheduleStayConstraints is the ScheduleStayConstraints model.
type ScheduleStayConstraints struct {
	AdvanceMaxDays   *int32  `graphql:"advanceMaxDays"`
	AdvanceMinDays   *int32  `graphql:"advanceMinDays"`
	CheckinWeekdays  *string `graphql:"checkinWeekdays"`
	CheckoutWeekdays *string `graphql:"checkoutWeekdays"`
	Id               string  `graphql:"id"`
	MaxNights        *int32  `graphql:"maxNights"`
	MinNights        *int32  `graphql:"minNights"`
}
