// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  mediasql
//
// orm — https://github.com/the-protobuf-project/orm

package mediasql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyMediasByIdResponse = schemaql.DeletePropertyMediasByIdResponse
type InsertPropertyMediasResponse = schemaql.InsertPropertyMediasResponse
type PropertyMedias = schemaql.PropertyMedias
type PropertyMediasAggExp = schemaql.PropertyMediasAggExp
type UpdatePropertyMediasByIdResponse = schemaql.UpdatePropertyMediasByIdResponse
