// Code generated by generateql. DO NOT EDIT.

package schemaql

// ChannelSyncStatuses is the ChannelSyncStatuses model.
type ChannelSyncStatuses struct {
	FailedCount  *int32  `graphql:"failedCount"`
	Id           string  `graphql:"id"`
	LastError    *string `graphql:"lastError"`
	LastSyncTime *string `graphql:"lastSyncTime"`
	Name         string  `graphql:"name"`
	PendingCount *int32  `graphql:"pendingCount"`
	State        *string `graphql:"state"`
}
