// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  schemaql
//
// orm — https://github.com/the-protobuf-project/orm

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// ChannelUnitMappings is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type ChannelUnitMappings struct {
	// ChannelId selects the "channelId" field.
	ChannelId string `graphql:"channelId"`
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// Etag selects the "etag" field; nil when the column is NULL.
	Etag *string `graphql:"etag"`
	// ExternalRatePlanId selects the "externalRatePlanId" field; nil when the column is NULL.
	ExternalRatePlanId *string `graphql:"externalRatePlanId"`
	// ExternalRoomTypeId selects the "externalRoomTypeId" field.
	ExternalRoomTypeId string `graphql:"externalRoomTypeId"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// State selects the "state" field; nil when the column is NULL.
	State *string `graphql:"state"`
	// Unit selects the "unit" field.
	Unit string `graphql:"unit"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime string `graphql:"updateTime"`
}

// ChannelUnitMappingsAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type ChannelUnitMappingsAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// ChannelId selects the "channelId" field.
	ChannelId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"channelId"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// Etag selects the "etag" field.
	Etag struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"etag"`
	// ExternalRatePlanId selects the "externalRatePlanId" field.
	ExternalRatePlanId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"externalRatePlanId"`
	// ExternalRoomTypeId selects the "externalRoomTypeId" field.
	ExternalRoomTypeId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"externalRoomTypeId"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// State selects the "state" field.
	State struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"state"`
	// Unit selects the "unit" field.
	Unit struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"unit"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"updateTime"`
}

// DeleteChannelUnitMappingsByIdResponse — Responses from the 'delete_channel_unit_mappings_by_id' procedure
type DeleteChannelUnitMappingsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ChannelId selects the "channelId" field.
		ChannelId string `graphql:"channelId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// ExternalRatePlanId selects the "externalRatePlanId" field; nil when the column is NULL.
		ExternalRatePlanId *string `graphql:"externalRatePlanId"`
		// ExternalRoomTypeId selects the "externalRoomTypeId" field.
		ExternalRoomTypeId string `graphql:"externalRoomTypeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// InsertChannelUnitMappingsResponse — Responses from the 'insert_channel_unit_mappings' procedure
type InsertChannelUnitMappingsResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ChannelId selects the "channelId" field.
		ChannelId string `graphql:"channelId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// ExternalRatePlanId selects the "externalRatePlanId" field; nil when the column is NULL.
		ExternalRatePlanId *string `graphql:"externalRatePlanId"`
		// ExternalRoomTypeId selects the "externalRoomTypeId" field.
		ExternalRoomTypeId string `graphql:"externalRoomTypeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// UpdateChannelUnitMappingsByIdResponse — Responses from the 'update_channel_unit_mappings_by_id' procedure
type UpdateChannelUnitMappingsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ChannelId selects the "channelId" field.
		ChannelId string `graphql:"channelId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// ExternalRatePlanId selects the "externalRatePlanId" field; nil when the column is NULL.
		ExternalRatePlanId *string `graphql:"externalRatePlanId"`
		// ExternalRoomTypeId selects the "externalRoomTypeId" field.
		ExternalRoomTypeId string `graphql:"externalRoomTypeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}
