// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeletePromocodeDiscountsByIdResponse is the DeletePromocodeDiscountsByIdResponse model.
type DeletePromocodeDiscountsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountCase  *string `graphql:"amountCase"`
		AmountOffId *string `graphql:"amountOffId"`
		Id          string  `graphql:"id"`
		PercentOff  *int32  `graphql:"percentOff"`
	} `graphql:"returning"`
}
