// Code generated by protoc-gen-orm. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePromocodeRedemptionsByIdResponse is the DeletePromocodeRedemptionsByIdResponse model.
type DeletePromocodeRedemptionsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		AmountAppliedId *string `graphql:"amountAppliedId"`
		Booking         string  `graphql:"booking"`
		Customer        string  `graphql:"customer"`
		Id              string  `graphql:"id"`
		Name            string  `graphql:"name"`
		PromoCodeId     string  `graphql:"promoCodeId"`
		RedeemedTime    *string `graphql:"redeemedTime"`
	} `graphql:"returning"`
}

// InsertPromocodeRedemptionsResponse is the InsertPromocodeRedemptionsResponse model.
type InsertPromocodeRedemptionsResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		AmountAppliedId *string `graphql:"amountAppliedId"`
		Booking         string  `graphql:"booking"`
		Customer        string  `graphql:"customer"`
		Id              string  `graphql:"id"`
		Name            string  `graphql:"name"`
		PromoCodeId     string  `graphql:"promoCodeId"`
		RedeemedTime    *string `graphql:"redeemedTime"`
	} `graphql:"returning"`
}

// PromocodeRedemptions is the PromocodeRedemptions model.
type PromocodeRedemptions struct {
	AmountAppliedId *string `graphql:"amountAppliedId"`
	Booking         string  `graphql:"booking"`
	Customer        string  `graphql:"customer"`
	Id              string  `graphql:"id"`
	Name            string  `graphql:"name"`
	PromoCodeId     string  `graphql:"promoCodeId"`
	RedeemedTime    *string `graphql:"redeemedTime"`
}

// PromocodeRedemptionsAggExp is the PromocodeRedemptionsAggExp model.
type PromocodeRedemptionsAggExp struct {
	Count           graphql.Int64 `graphql:"_count"`
	AmountAppliedId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"amountAppliedId"`
	Booking struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"booking"`
	Customer struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"customer"`
	Id struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	Name struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"name"`
	PromoCodeId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"promoCodeId"`
	RedeemedTime struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"redeemedTime"`
}

// UpdatePromocodeRedemptionsByIdResponse is the UpdatePromocodeRedemptionsByIdResponse model.
type UpdatePromocodeRedemptionsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		AmountAppliedId *string `graphql:"amountAppliedId"`
		Booking         string  `graphql:"booking"`
		Customer        string  `graphql:"customer"`
		Id              string  `graphql:"id"`
		Name            string  `graphql:"name"`
		PromoCodeId     string  `graphql:"promoCodeId"`
		RedeemedTime    *string `graphql:"redeemedTime"`
	} `graphql:"returning"`
}
