// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// PromocodeScopeApplicableResourcesAggExp is the PromocodeScopeApplicableResourcesAggExp model.
type PromocodeScopeApplicableResourcesAggExp struct {
	Count graphql.Int64 `graphql:"_count"`
	Id    struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	ResourceId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"resourceId"`
	ScopeId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"scopeId"`
}
