// Code generated by generateql. DO NOT EDIT.

package schemaql

// PromocodeScopeApplicableResources is the PromocodeScopeApplicableResources model.
type PromocodeScopeApplicableResources struct {
	Id         string `graphql:"id"`
	ResourceId string `graphql:"resourceId"`
	ScopeId    string `graphql:"scopeId"`
}
