// Code generated by generateql. DO NOT EDIT.

package schemaql

// PromocodeScopeApplicableProperties is the PromocodeScopeApplicableProperties model.
type PromocodeScopeApplicableProperties struct {
	Id         string `graphql:"id"`
	PropertyId string `graphql:"propertyId"`
	ScopeId    string `graphql:"scopeId"`
}
