// Code generated by generateql. DO NOT EDIT.

package schemaql

// UpdatePromocodeScopeApplicableUnitsByIdResponse is the UpdatePromocodeScopeApplicableUnitsByIdResponse model.
type UpdatePromocodeScopeApplicableUnitsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id       string `graphql:"id"`
		ScopeId  string `graphql:"scopeId"`
		UnitId   string `graphql:"unitId"`
		UnitName string `graphql:"unitName"`
	} `graphql:"returning"`
}
