// Code generated by generateql. DO NOT EDIT.

package schemaql

// UpdatePromocodeRedemptionWindowsByIdResponse is the UpdatePromocodeRedemptionWindowsByIdResponse model.
type UpdatePromocodeRedemptionWindowsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		EndTime   *string `graphql:"endTime"`
		Id        string  `graphql:"id"`
		StartTime *string `graphql:"startTime"`
	} `graphql:"returning"`
}
