// Code generated by generateql. DO NOT EDIT.

package schemaql

import (
	"github.com/oh-tarnished/generateql/runtime/go/graphql"
)

// UpdatePromocodeUsageLimitsByIdResponse is the UpdatePromocodeUsageLimitsByIdResponse model.
type UpdatePromocodeUsageLimitsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id               string         `graphql:"id"`
		MaxRedemptions   *graphql.Int64 `graphql:"maxRedemptions"`
		PerCustomerLimit *int32         `graphql:"perCustomerLimit"`
	} `graphql:"returning"`
}
