// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeletePropertyRateOverridesByIdResponse is the DeletePropertyRateOverridesByIdResponse model.
type DeletePropertyRateOverridesByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		DateRangeId *string `graphql:"dateRangeId"`
		Id          string  `graphql:"id"`
		PriceId     string  `graphql:"priceId"`
		UnitId      string  `graphql:"unitId"`
		Weekdays    *string `graphql:"weekdays"`
	} `graphql:"returning"`
}
