// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeletePropertyUnitsLinkByIdResponse is the DeletePropertyUnitsLinkByIdResponse model.
type DeletePropertyUnitsLinkByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		Id         string `graphql:"id"`
		PropertyId string `graphql:"propertyId"`
		UnitId     string `graphql:"unitId"`
		UnitName   string `graphql:"unitName"`
	} `graphql:"returning"`
}
