// Code generated by protoc-gen-orm. DO NOT EDIT.

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePropertyRateOverridesByIdResponse is the DeletePropertyRateOverridesByIdResponse model.
type DeletePropertyRateOverridesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		DateRangeId *string `graphql:"dateRangeId"`
		ID          string  `graphql:"id"`
		PriceId     string  `graphql:"priceId"`
		UnitId      string  `graphql:"unitId"`
		Weekdays    *string `graphql:"weekdays"`
	} `graphql:"returning"`
}

// InsertPropertyRateOverridesResponse is the InsertPropertyRateOverridesResponse model.
type InsertPropertyRateOverridesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		DateRangeId *string `graphql:"dateRangeId"`
		ID          string  `graphql:"id"`
		PriceId     string  `graphql:"priceId"`
		UnitId      string  `graphql:"unitId"`
		Weekdays    *string `graphql:"weekdays"`
	} `graphql:"returning"`
}

// PropertyRateOverrides is the PropertyRateOverrides model.
type PropertyRateOverrides struct {
	DateRangeId *string `graphql:"dateRangeId"`
	ID          string  `graphql:"id"`
	PriceId     string  `graphql:"priceId"`
	UnitId      string  `graphql:"unitId"`
	Weekdays    *string `graphql:"weekdays"`
}

// PropertyRateOverridesAggExp is the PropertyRateOverridesAggExp model.
type PropertyRateOverridesAggExp struct {
	Count       graphql.Int64 `graphql:"_count"`
	DateRangeId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"dateRangeId"`
	ID struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"id"`
	PriceId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"priceId"`
	UnitId struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"unitId"`
	Weekdays struct {
		Count         graphql.Int64 `graphql:"_count"`
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		Max           *string       `graphql:"max"`
		Min           *string       `graphql:"min"`
	} `graphql:"weekdays"`
}

// UpdatePropertyRateOverridesByIdResponse is the UpdatePropertyRateOverridesByIdResponse model.
type UpdatePropertyRateOverridesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		DateRangeId *string `graphql:"dateRangeId"`
		ID          string  `graphql:"id"`
		PriceId     string  `graphql:"priceId"`
		UnitId      string  `graphql:"unitId"`
		Weekdays    *string `graphql:"weekdays"`
	} `graphql:"returning"`
}
