// Code generated by generateql. DO NOT EDIT.

package schemaql

// PropertyRateOverrides is the PropertyRateOverrides model.
type PropertyRateOverrides struct {
	DateRangeId *string `graphql:"dateRangeId"`
	Id          string  `graphql:"id"`
	PriceId     string  `graphql:"priceId"`
	UnitId      string  `graphql:"unitId"`
	Weekdays    *string `graphql:"weekdays"`
}
