// Code generated by generateql. DO NOT EDIT.

package schemaql

// PropertyTaxes is the PropertyTaxes model.
type PropertyTaxes struct {
	Code        string  `graphql:"code"`
	DisplayName *string `graphql:"displayName"`
	Id          string  `graphql:"id"`
	Percent     float64 `graphql:"percent"`
	UnitId      string  `graphql:"unitId"`
}
