// Code generated by generateql. DO NOT EDIT.

package schemaql

// PropertyFees is the PropertyFees model.
type PropertyFees struct {
	AmountId    *string `graphql:"amountId"`
	Code        string  `graphql:"code"`
	DisplayName *string `graphql:"displayName"`
	Id          string  `graphql:"id"`
	Percent     *int32  `graphql:"percent"`
	PricingUnit *string `graphql:"pricingUnit"`
	Taxable     *bool   `graphql:"taxable"`
	UnitId      string  `graphql:"unitId"`
}
