// Code generated by generateql. DO NOT EDIT.

package schemaql

// PropertyUnitApplicablePromoCodes is the PropertyUnitApplicablePromoCodes model.
type PropertyUnitApplicablePromoCodes struct {
	Id          string `graphql:"id"`
	PromoCodeId string `graphql:"promoCodeId"`
	UnitId      string `graphql:"unitId"`
}
