// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  schemaql
//
// orm — https://github.com/the-protobuf-project/orm

package schemaql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePropertyTaxesByIdResponse — Responses from the 'delete_property_taxes_by_id' procedure
type DeletePropertyTaxesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field.
		Percent float64 `graphql:"percent"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
	} `graphql:"returning"`
}

// InsertPropertyTaxesResponse — Responses from the 'insert_property_taxes' procedure
type InsertPropertyTaxesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field.
		Percent float64 `graphql:"percent"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
	} `graphql:"returning"`
}

// PropertyTaxes is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type PropertyTaxes struct {
	// Code selects the "code" field.
	Code string `graphql:"code"`
	// DisplayName selects the "displayName" field; nil when the column is NULL.
	DisplayName *string `graphql:"displayName"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Percent selects the "percent" field.
	Percent float64 `graphql:"percent"`
	// UnitId selects the "unitId" field.
	UnitId string `graphql:"unitId"`
}

// PropertyTaxesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type PropertyTaxesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// Code selects the "code" field.
	Code struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"code"`
	// DisplayName selects the "displayName" field.
	DisplayName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"displayName"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Percent selects the "percent" field.
	Percent struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *float64 `graphql:"avg"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *float64 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *float64 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *float64 `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *float64 `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *float64 `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *float64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *float64 `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *float64 `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *float64 `graphql:"variance"`
	} `graphql:"percent"`
	// UnitId selects the "unitId" field.
	UnitId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"unitId"`
}

// UpdatePropertyTaxesByIdResponse — Responses from the 'update_property_taxes_by_id' procedure
type UpdatePropertyTaxesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field.
		Percent float64 `graphql:"percent"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
	} `graphql:"returning"`
}
