// Code generated by generateql. DO NOT EDIT.

package schemaql

// UpdatePropertyLosDiscountsByIdResponse is the UpdatePropertyLosDiscountsByIdResponse model.
type UpdatePropertyLosDiscountsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AmountOffId *string `graphql:"amountOffId"`
		Id          string  `graphql:"id"`
		MinNights   int32   `graphql:"minNights"`
		PercentOff  *int32  `graphql:"percentOff"`
		UnitId      string  `graphql:"unitId"`
	} `graphql:"returning"`
}
