// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.2.2-0.20260708070059-6a44ba3ff73f+dirty
// 	protoc (unknown)
// source: freebusy/identity/v1/guest.proto, freebusy/identity/v1/identity.proto
//
// database: freebusy
// schema:   identity
//
// orm — https://github.com/the-protobuf-project/orm

package identity

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// IdDocumentStore provides typed CRUD access to IdDocument records.
// A government identity document. Passport fields are required for foreign nationals; domestic guests may present any accepted document type.
type IdDocumentStore struct{ DB *gorm.DB }

// Compile-time proof that IdDocumentStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[IdDocument] = (*IdDocumentStore)(nil)

// NewIdDocumentStore returns a IdDocumentStore backed by db.
func NewIdDocumentStore(db *gorm.DB) *IdDocumentStore { return &IdDocumentStore{DB: db} }

// Create inserts m.
func (s *IdDocumentStore) Create(ctx context.Context, m *IdDocument) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the IdDocument records matching opts.
func (s *IdDocumentStore) List(ctx context.Context, opts gormx.ListOptions) ([]IdDocument, error) {
	var out []IdDocument
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of IdDocument records matching opts.Where
// (pagination and ordering are ignored).
func (s *IdDocumentStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&IdDocument{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *IdDocumentStore) Update(ctx context.Context, m *IdDocument) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the IdDocument with the given primary key.
func (s *IdDocumentStore) GetByID(ctx context.Context, id string) (*IdDocument, error) {
	var m IdDocument
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the IdDocument with the given primary key.
func (s *IdDocumentStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&IdDocument{}, "id = ?", id).Error
}

// ListByAttachmentID returns the IdDocument records whose attachment_id matches id, with opts applied.
func (s *IdDocumentStore) ListByAttachmentID(ctx context.Context, id string, opts gormx.ListOptions) ([]IdDocument, error) {
	var out []IdDocument
	q := opts.Apply(s.DB.WithContext(ctx).Where("attachment_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
