// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.3.0
// 	protoc (unknown)
// source: freebusy/identity/v1/guest.proto, freebusy/identity/v1/identity.proto
//
// database: freebusy
// schema:   identity
//
// orm — https://github.com/the-protobuf-project/orm

package identity

import (
	"time"

	"github.com/lib/pq"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/common"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/shared"
)

// A guest's gender, as recorded on a registration card.
type Gender string

// Gender values as stored in the database.
const (
	// Male.
	GenderMale Gender = "MALE"
	// Female.
	GenderFemale Gender = "FEMALE"
	// Another gender identity.
	GenderOther Gender = "OTHER"
	// Declined to state.
	GenderUndisclosed Gender = "UNDISCLOSED"
)

// Which age bracket a guest falls in. Drives occupancy counting and child pricing; may be given explicitly or derived from date_of_birth.
type AgeGroup string

// AgeGroup values as stored in the database.
const (
	// An adult (occupies an adult slot; charged the adult rate).
	AgeGroupAdult AgeGroup = "ADULT"
	// A child (may be charged a child rate or stay free per policy).
	AgeGroupChild AgeGroup = "CHILD"
	// An infant (typically not counted against occupancy).
	AgeGroupInfant AgeGroup = "INFANT"
)

// The kind of government identity document a guest presents at check-in.
type IdDocumentType string

// IdDocumentType values as stored in the database.
const (
	// Passport (required for foreign nationals, e.g. India Form C).
	IdDocumentTypePassport IdDocumentType = "PASSPORT"
	// A national identity card.
	IdDocumentTypeNationalID IdDocumentType = "NATIONAL_ID"
	// A driving licence.
	IdDocumentTypeDrivingLicense IdDocumentType = "DRIVING_LICENSE"
	// India's Aadhaar card.
	IdDocumentTypeAadhaar IdDocumentType = "AADHAAR"
	// A voter identity card.
	IdDocumentTypeVoterID IdDocumentType = "VOTER_ID"
	// Any other accepted document.
	IdDocumentTypeOther IdDocumentType = "OTHER"
)

// A guest's smoking preference for room assignment.
type SmokingPreference string

// SmokingPreference values as stored in the database.
const (
	// Prefers a non-smoking room.
	SmokingPreferenceNonSmoking SmokingPreference = "NON_SMOKING"
	// Prefers a smoking room.
	SmokingPreferenceSmoking SmokingPreference = "SMOKING"
)

// A guest's bed-type preference for room assignment.
type BedPreference string

// BedPreference values as stored in the database.
const (
	// No particular preference.
	BedPreferenceNoPreference BedPreference = "NO_PREFERENCE"
	// A king bed.
	BedPreferenceKing BedPreference = "KING"
	// A queen bed.
	BedPreferenceQueen BedPreference = "QUEEN"
	// Two twin beds.
	BedPreferenceTwin BedPreference = "TWIN"
	// A single bed.
	BedPreferenceSingle BedPreference = "SINGLE"
)

// A signed-in person. Identity is deliberately thin: actual login is an OIDC redirect flow handled over plain HTTP by the IdP, so most of "auth" never appears as an RPC. Email and identity come from the IdP and are read-only here; only profile preferences are editable.
type User struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// The user name. The alias "users/me" resolves to the caller. Format: users/{user}
	Name string `gorm:"column:name;not null;uniqueIndex" json:"name" validate:"required"`
	// Email address, sourced from the IdP.
	Email *string `gorm:"column:email" json:"email,omitempty"`
	// Display name.
	DisplayName *string `gorm:"column:display_name" json:"display_name,omitempty"`
	// Avatar image URL.
	AvatarURL *string `gorm:"column:avatar_url" json:"avatar_url,omitempty"`
	// BCP 47 locale (e.g. "en-US").
	Locale *string `gorm:"column:locale" json:"locale,omitempty"`
	// IANA time zone (e.g. "America/New_York").
	TimeZone *string `gorm:"column:time_zone" json:"time_zone,omitempty"`
	// Creation timestamp.
	CreateTime time.Time `gorm:"column:create_time;type:timestamptz;not null;autoCreateTime" json:"create_time"`
	// Last-modification timestamp.
	UpdateTime time.Time `gorm:"column:update_time;type:timestamptz;not null;autoUpdateTime" json:"update_time"`
	// Opaque version for optimistic concurrency (AIP-154); echo on update.
	Etag *string `gorm:"column:etag" json:"etag,omitempty"`
}

func (*User) TableName() string { return "identity.users" }

// A guest is a person who stays under a booking. It is one of three distinct people the system models, all in the identity domain: - User   (identity.proto): the account that signs in and books online. - Guest  (this message):   a person actually staying — the party on a booking. - Member (organisation):   hotel staff who manage the chain/property. The booker (a User, or an anonymous contact) is not necessarily a guest, and a booking has one or more guests. This message captures what a hotel records on a Guest Registration Card at check-in — identity, nationality, and ID — plus the foreigner-registration details required for foreign nationals (e.g. India's Form C / FRRO), and the guest's own stay preferences. It is an embedded value on a booking, not an addressable account resource.
type Guest struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Full legal name, exactly as on the presented ID / passport.
	DisplayName string `gorm:"column:display_name;not null" json:"display_name" validate:"required"`
	// Whether this is the lead / primary guest (the registered occupant the booking is held under). Exactly one guest in a party is primary.
	Primary *bool `gorm:"column:primary" json:"primary,omitempty"`
	// Gender as recorded for registration.
	Gender *Gender `gorm:"column:gender;check:chk_guests_gender,gender IN ('MALE','FEMALE','OTHER','UNDISCLOSED')" json:"gender,omitempty"`
	// Date of birth.
	BirthDate *time.Time `gorm:"column:birth_date;type:date" json:"birth_date,omitempty"`
	// Age bracket; given explicitly, or derived from birth_date by the server.
	AgeGroup *AgeGroup `gorm:"column:age_group;check:chk_guests_age_group,age_group IN ('ADULT','CHILD','INFANT')" json:"age_group,omitempty"`
	// Nationality as an ISO 3166-1 alpha-2 country code (e.g. "IN", "GB", "US"). Required for foreign-national registration.
	Nationality *string `gorm:"column:nationality" json:"nationality,omitempty"`
	// Contact email (typically only for the lead guest).
	Email *string `gorm:"column:email" json:"email,omitempty"`
	// Contact phone in E.164 form (typically only for the lead guest).
	PhoneNumber *string `gorm:"column:phone_number" json:"phone_number,omitempty"`
	// Foreign key to Booking.
	BookingID string `gorm:"column:booking_id;not null;index:idx_guests_booking_id" json:"booking_id" validate:"required"`
	// Foreign key to IdDocument.
	IDDocumentID *string     `gorm:"column:id_document_id;index:idx_guests_id_document_id" json:"id_document_id,omitempty"`
	IDDocument   *IdDocument `gorm:"foreignKey:IDDocumentID;constraint:OnDelete:SET NULL" json:"iddocument,omitempty"`
	// Foreign key to PostalAddress.
	PermanentAddressID *string               `gorm:"column:permanent_address_id;index:idx_guests_permanent_address_id" json:"permanent_address_id,omitempty"`
	PermanentAddress   *common.PostalAddress `gorm:"foreignKey:PermanentAddressID;constraint:OnDelete:SET NULL" json:"permanentaddress,omitempty"`
	// Foreign key to PostalAddress.
	LocalAddressID *string               `gorm:"column:local_address_id;index:idx_guests_local_address_id" json:"local_address_id,omitempty"`
	LocalAddress   *common.PostalAddress `gorm:"foreignKey:LocalAddressID;constraint:OnDelete:SET NULL" json:"localaddress,omitempty"`
	// Foreign key to ForeignerDetails.
	ForeignerID *string           `gorm:"column:foreigner_id;index:idx_guests_foreigner_id" json:"foreigner_id,omitempty"`
	Foreigner   *ForeignerDetails `gorm:"foreignKey:ForeignerID;constraint:OnDelete:SET NULL" json:"foreigner,omitempty"`
	// Foreign key to GuestPreferences.
	PreferencesID *string           `gorm:"column:preferences_id;index:idx_guests_preferences_id" json:"preferences_id,omitempty"`
	Preferences   *GuestPreferences `gorm:"foreignKey:PreferencesID;constraint:OnDelete:SET NULL" json:"preferences,omitempty"`
}

func (*Guest) TableName() string { return "identity.guests" }

// A government identity document. Passport fields are required for foreign nationals; domestic guests may present any accepted document type.
type IdDocument struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Which kind of document this is.
	Type IdDocumentType `gorm:"column:type;not null;default:'PASSPORT';check:chk_id_documents_type,type IN ('PASSPORT','NATIONAL_ID','DRIVING_LICENSE','AADHAAR','VOTER_ID','OTHER')" json:"type" validate:"required"`
	// The document number.
	Number string `gorm:"column:number;not null" json:"number" validate:"required"`
	// Issuing country as an ISO 3166-1 alpha-2 code.
	IssuingCountry *string `gorm:"column:issuing_country" json:"issuing_country,omitempty"`
	// Place of issue (city / office), as printed on the document.
	IssuePlace *string `gorm:"column:issue_place" json:"issue_place,omitempty"`
	// Date the document was issued.
	IssueDate *time.Time `gorm:"column:issue_date;type:date" json:"issue_date,omitempty"`
	// Date the document expires.
	ExpiryDate *time.Time `gorm:"column:expiry_date;type:date" json:"expiry_date,omitempty"`
	// Foreign key to Attachment.
	AttachmentID *string            `gorm:"column:attachment_id;index:idx_id_documents_attachment_id" json:"attachment_id,omitempty"`
	Attachment   *shared.Attachment `gorm:"foreignKey:AttachmentID;constraint:OnDelete:SET NULL" json:"attachment,omitempty"`
	// Back-relation: Guest records that reference this via id_document_id.
	Guests []Guest `gorm:"foreignKey:IDDocumentID" json:"guests,omitempty"`
}

func (*IdDocument) TableName() string { return "identity.id_documents" }

// Foreigner-registration details a hotel must capture for foreign nationals to file Form C with the FRRO within 24 hours of arrival (India). Nationals of exempt countries (e.g. Nepal, Bhutan) and diplomats may omit these.
type ForeignerDetails struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Visa number.
	VisaNumber *string `gorm:"column:visa_number" json:"visa_number,omitempty"`
	// Visa type / category (e.g. "Tourist", "Business", "Employment").
	VisaType *string `gorm:"column:visa_type" json:"visa_type,omitempty"`
	// Place the visa was issued.
	VisaIssuePlace *string `gorm:"column:visa_issue_place" json:"visa_issue_place,omitempty"`
	// Date the visa was issued.
	VisaIssueDate *time.Time `gorm:"column:visa_issue_date;type:date" json:"visa_issue_date,omitempty"`
	// Date the visa expires.
	VisaExpiryDate *time.Time `gorm:"column:visa_expiry_date;type:date" json:"visa_expiry_date,omitempty"`
	// Date the guest arrived in the country.
	ArrivalDate *time.Time `gorm:"column:arrival_date;type:date" json:"arrival_date,omitempty"`
	// Port / place of entry into the country.
	EntryPort *string `gorm:"column:entry_port" json:"entry_port,omitempty"`
	// Where the guest is arriving from (last city / country).
	Origin *string `gorm:"column:origin" json:"origin,omitempty"`
	// The guest's next destination after this stay.
	NextDestination *string `gorm:"column:next_destination" json:"next_destination,omitempty"`
	// Purpose of visit (e.g. "Tourism", "Business", "Medical").
	VisitPurpose *string `gorm:"column:visit_purpose" json:"visit_purpose,omitempty"`
	// Back-relation: Guest records that reference this via foreigner_id.
	Guests []Guest `gorm:"foreignKey:ForeignerID" json:"guests,omitempty"`
}

func (*ForeignerDetails) TableName() string { return "identity.foreigner_details" }

// A guest's stay preferences and special requests. All optional; used to guide unit assignment and to surface requests to housekeeping / front desk.
type GuestPreferences struct {
	// Unique identifier for the record.
	ID string `gorm:"column:id;primaryKey;not null" json:"id"`
	// Preferred smoking / non-smoking room.
	Smoking *SmokingPreference `gorm:"column:smoking;check:chk_guest_preferences_smoking,smoking IN ('NON_SMOKING','SMOKING')" json:"smoking,omitempty"`
	// Preferred bed type.
	Bed *BedPreference `gorm:"column:bed;check:chk_guest_preferences_bed,bed IN ('NO_PREFERENCE','KING','QUEEN','TWIN','SINGLE')" json:"bed,omitempty"`
	// Dietary requirements / requests (e.g. "vegetarian", "jain", "halal", "gluten-free").
	Dietary pq.StringArray `gorm:"column:dietary;type:text[]" json:"dietary,omitempty"`
	// Accessibility needs (e.g. "wheelchair", "hearing-accessible", "ground-floor").
	Accessibility pq.StringArray `gorm:"column:accessibility;type:text[]" json:"accessibility,omitempty"`
	// Preferred floor; 0 means no preference.
	FloorPreference *int32 `gorm:"column:floor_preference" json:"floor_preference,omitempty"`
	// Loyalty-programme membership number, if any.
	LoyaltyNumber *string `gorm:"column:loyalty_number" json:"loyalty_number,omitempty"`
	// Free-form special requests (e.g. "late check-in", "crib", "high floor").
	SpecialRequests pq.StringArray `gorm:"column:special_requests;type:text[]" json:"special_requests,omitempty"`
	// Any additional free-text notes about the guest.
	Notes *string `gorm:"column:notes" json:"notes,omitempty"`
	// Back-relation: Guest records that reference this via preferences_id.
	Guests []Guest `gorm:"foreignKey:PreferencesID" json:"guests,omitempty"`
}

func (*GuestPreferences) TableName() string { return "identity.guest_preferences" }
