// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// orm — https://github.com/the-protobuf-project/orm

package schedule

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// ScheduleExceptionsStore provides typed CRUD access to ScheduleExceptions records.
// Join table for the many-to-many relation Schedule.exceptions ↔ AvailabilityException.
type ScheduleExceptionsStore struct{ DB *gorm.DB }

// Compile-time proof that ScheduleExceptionsStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[ScheduleExceptions] = (*ScheduleExceptionsStore)(nil)

// NewScheduleExceptionsStore returns a ScheduleExceptionsStore backed by db.
func NewScheduleExceptionsStore(db *gorm.DB) *ScheduleExceptionsStore {
	return &ScheduleExceptionsStore{DB: db}
}

// Create inserts m.
func (s *ScheduleExceptionsStore) Create(ctx context.Context, m *ScheduleExceptions) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the ScheduleExceptions records matching opts.
func (s *ScheduleExceptionsStore) List(ctx context.Context, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of ScheduleExceptions records matching opts.Where
// (pagination and ordering are ignored).
func (s *ScheduleExceptionsStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&ScheduleExceptions{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ScheduleExceptionsStore) Update(ctx context.Context, m *ScheduleExceptions) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the ScheduleExceptions with the given primary key.
func (s *ScheduleExceptionsStore) GetByID(ctx context.Context, id string) (*ScheduleExceptions, error) {
	var m ScheduleExceptions
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the ScheduleExceptions with the given primary key.
func (s *ScheduleExceptionsStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&ScheduleExceptions{}, "id = ?", id).Error
}

// ListByScheduleID returns the ScheduleExceptions records whose schedule_id matches id, with opts applied.
func (s *ScheduleExceptionsStore) ListByScheduleID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	q := opts.Apply(s.DB.WithContext(ctx).Where("schedule_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAvailabilityExceptionID returns the ScheduleExceptions records whose availability_exception_id matches id, with opts applied.
func (s *ScheduleExceptionsStore) ListByAvailabilityExceptionID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	q := opts.Apply(s.DB.WithContext(ctx).Where("availability_exception_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
