// Code generated by protoc-gen-protorm. DO NOT EDIT.
// versions:
// 	protoc-gen-protorm 1.1.1
// 	protoc             (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// protorm — https://github.com/the-protobuf-project/protorm

package schedule

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// StayConstraintsStore provides typed CRUD access to StayConstraints records.
// Stay rules that affect bookability for NIGHTLY resources.
type StayConstraintsStore struct{ DB *gorm.DB }

// Compile-time proof that StayConstraintsStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[StayConstraints] = (*StayConstraintsStore)(nil)

// NewStayConstraintsStore returns a StayConstraintsStore backed by db.
func NewStayConstraintsStore(db *gorm.DB) *StayConstraintsStore { return &StayConstraintsStore{DB: db} }

// Create inserts m.
func (s *StayConstraintsStore) Create(ctx context.Context, m *StayConstraints) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the StayConstraints records matching opts.
func (s *StayConstraintsStore) List(ctx context.Context, opts gormx.ListOptions) ([]StayConstraints, error) {
	var out []StayConstraints
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of StayConstraints records matching opts.Where
// (pagination and ordering are ignored).
func (s *StayConstraintsStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	db := s.DB.WithContext(ctx).Model(&StayConstraints{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	var n int64
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *StayConstraintsStore) Update(ctx context.Context, m *StayConstraints) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the StayConstraints with the given primary key.
func (s *StayConstraintsStore) GetByID(ctx context.Context, id string) (*StayConstraints, error) {
	var m StayConstraints
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the StayConstraints with the given primary key.
func (s *StayConstraintsStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&StayConstraints{}, "id = ?", id).Error
}
