// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  schemaql
//
// orm — https://github.com/the-protobuf-project/orm

package schemaql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// BookingResource is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type BookingResource struct {
	// AssignedUnit selects the "assignedUnit" field; nil when the column is NULL.
	AssignedUnit *string `graphql:"assignedUnit"`
	// Attributes selects the "attributes" field; nil when the column is NULL.
	Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
	// CancelReason selects the "cancelReason" field; nil when the column is NULL.
	CancelReason *string `graphql:"cancelReason"`
	// CancelTime selects the "cancelTime" field; nil when the column is NULL.
	CancelTime *string `graphql:"cancelTime"`
	// ConfirmTime selects the "confirmTime" field; nil when the column is NULL.
	ConfirmTime *string `graphql:"confirmTime"`
	// ContactId selects the "contactId" field; nil when the column is NULL.
	ContactId *string `graphql:"contactId"`
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// Customer selects the "customer" field; nil when the column is NULL.
	Customer *string `graphql:"customer"`
	// DiscountId selects the "discountId" field; nil when the column is NULL.
	DiscountId *string `graphql:"discountId"`
	// Etag selects the "etag" field; nil when the column is NULL.
	Etag *string `graphql:"etag"`
	// HoldExpireTime selects the "holdExpireTime" field; nil when the column is NULL.
	HoldExpireTime *string `graphql:"holdExpireTime"`
	// HoldTtl selects the "holdTtl" field; nil when the column is NULL.
	HoldTtl *string `graphql:"holdTtl"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// Notes selects the "notes" field; nil when the column is NULL.
	Notes *string `graphql:"notes"`
	// OccupancyId selects the "occupancyId" field; nil when the column is NULL.
	OccupancyId *string `graphql:"occupancyId"`
	// PriceId selects the "priceId" field; nil when the column is NULL.
	PriceId *string `graphql:"priceId"`
	// PromoCode selects the "promoCode" field; nil when the column is NULL.
	PromoCode *string `graphql:"promoCode"`
	// RefundAmountId selects the "refundAmountId" field; nil when the column is NULL.
	RefundAmountId *string `graphql:"refundAmountId"`
	// RefundPercent selects the "refundPercent" field; nil when the column is NULL.
	RefundPercent *int32 `graphql:"refundPercent"`
	// State selects the "state" field; nil when the column is NULL.
	State *string `graphql:"state"`
	// TotalId selects the "totalId" field; nil when the column is NULL.
	TotalId *string `graphql:"totalId"`
	// Unit selects the "unit" field.
	Unit string `graphql:"unit"`
	// Units selects the "units" field; nil when the column is NULL.
	Units *int32 `graphql:"units"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime string `graphql:"updateTime"`
	// WindowId selects the "windowId" field.
	WindowId string `graphql:"windowId"`
}

// BookingResourceAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type BookingResourceAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// AssignedUnit selects the "assignedUnit" field.
	AssignedUnit struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"assignedUnit"`
	// Attributes selects the "attributes" field.
	Attributes struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	} `graphql:"attributes"`
	// CancelReason selects the "cancelReason" field.
	CancelReason struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"cancelReason"`
	// CancelTime selects the "cancelTime" field.
	CancelTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"cancelTime"`
	// ConfirmTime selects the "confirmTime" field.
	ConfirmTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"confirmTime"`
	// ContactId selects the "contactId" field.
	ContactId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"contactId"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// Customer selects the "customer" field.
	Customer struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"customer"`
	// DiscountId selects the "discountId" field.
	DiscountId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"discountId"`
	// Etag selects the "etag" field.
	Etag struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"etag"`
	// HoldExpireTime selects the "holdExpireTime" field.
	HoldExpireTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"holdExpireTime"`
	// HoldTtl selects the "holdTtl" field.
	HoldTtl struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"holdTtl"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// Notes selects the "notes" field.
	Notes struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"notes"`
	// OccupancyId selects the "occupancyId" field.
	OccupancyId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"occupancyId"`
	// PriceId selects the "priceId" field.
	PriceId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"priceId"`
	// PromoCode selects the "promoCode" field.
	PromoCode struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"promoCode"`
	// RefundAmountId selects the "refundAmountId" field.
	RefundAmountId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"refundAmountId"`
	// RefundPercent selects the "refundPercent" field.
	RefundPercent struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"refundPercent"`
	// State selects the "state" field.
	State struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"state"`
	// TotalId selects the "totalId" field.
	TotalId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"totalId"`
	// Unit selects the "unit" field.
	Unit struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"unit"`
	// Units selects the "units" field.
	Units struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"units"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"updateTime"`
	// WindowId selects the "windowId" field.
	WindowId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"windowId"`
}

// DeleteBookingResourceByIdResponse — Responses from the 'delete_booking_resource_by_id' procedure
type DeleteBookingResourceByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AssignedUnit selects the "assignedUnit" field; nil when the column is NULL.
		AssignedUnit *string `graphql:"assignedUnit"`
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// CancelReason selects the "cancelReason" field; nil when the column is NULL.
		CancelReason *string `graphql:"cancelReason"`
		// CancelTime selects the "cancelTime" field; nil when the column is NULL.
		CancelTime *string `graphql:"cancelTime"`
		// ConfirmTime selects the "confirmTime" field; nil when the column is NULL.
		ConfirmTime *string `graphql:"confirmTime"`
		// ContactId selects the "contactId" field; nil when the column is NULL.
		ContactId *string `graphql:"contactId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Customer selects the "customer" field; nil when the column is NULL.
		Customer *string `graphql:"customer"`
		// DiscountId selects the "discountId" field; nil when the column is NULL.
		DiscountId *string `graphql:"discountId"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// HoldExpireTime selects the "holdExpireTime" field; nil when the column is NULL.
		HoldExpireTime *string `graphql:"holdExpireTime"`
		// HoldTtl selects the "holdTtl" field; nil when the column is NULL.
		HoldTtl *string `graphql:"holdTtl"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Notes selects the "notes" field; nil when the column is NULL.
		Notes *string `graphql:"notes"`
		// OccupancyId selects the "occupancyId" field; nil when the column is NULL.
		OccupancyId *string `graphql:"occupancyId"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PromoCode selects the "promoCode" field; nil when the column is NULL.
		PromoCode *string `graphql:"promoCode"`
		// RefundAmountId selects the "refundAmountId" field; nil when the column is NULL.
		RefundAmountId *string `graphql:"refundAmountId"`
		// RefundPercent selects the "refundPercent" field; nil when the column is NULL.
		RefundPercent *int32 `graphql:"refundPercent"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// TotalId selects the "totalId" field; nil when the column is NULL.
		TotalId *string `graphql:"totalId"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *int32 `graphql:"units"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
		// WindowId selects the "windowId" field.
		WindowId string `graphql:"windowId"`
	} `graphql:"returning"`
}

// InsertBookingResourceResponse — Responses from the 'insert_booking_resource' procedure
type InsertBookingResourceResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AssignedUnit selects the "assignedUnit" field; nil when the column is NULL.
		AssignedUnit *string `graphql:"assignedUnit"`
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// CancelReason selects the "cancelReason" field; nil when the column is NULL.
		CancelReason *string `graphql:"cancelReason"`
		// CancelTime selects the "cancelTime" field; nil when the column is NULL.
		CancelTime *string `graphql:"cancelTime"`
		// ConfirmTime selects the "confirmTime" field; nil when the column is NULL.
		ConfirmTime *string `graphql:"confirmTime"`
		// ContactId selects the "contactId" field; nil when the column is NULL.
		ContactId *string `graphql:"contactId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Customer selects the "customer" field; nil when the column is NULL.
		Customer *string `graphql:"customer"`
		// DiscountId selects the "discountId" field; nil when the column is NULL.
		DiscountId *string `graphql:"discountId"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// HoldExpireTime selects the "holdExpireTime" field; nil when the column is NULL.
		HoldExpireTime *string `graphql:"holdExpireTime"`
		// HoldTtl selects the "holdTtl" field; nil when the column is NULL.
		HoldTtl *string `graphql:"holdTtl"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Notes selects the "notes" field; nil when the column is NULL.
		Notes *string `graphql:"notes"`
		// OccupancyId selects the "occupancyId" field; nil when the column is NULL.
		OccupancyId *string `graphql:"occupancyId"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PromoCode selects the "promoCode" field; nil when the column is NULL.
		PromoCode *string `graphql:"promoCode"`
		// RefundAmountId selects the "refundAmountId" field; nil when the column is NULL.
		RefundAmountId *string `graphql:"refundAmountId"`
		// RefundPercent selects the "refundPercent" field; nil when the column is NULL.
		RefundPercent *int32 `graphql:"refundPercent"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// TotalId selects the "totalId" field; nil when the column is NULL.
		TotalId *string `graphql:"totalId"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *int32 `graphql:"units"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
		// WindowId selects the "windowId" field.
		WindowId string `graphql:"windowId"`
	} `graphql:"returning"`
}

// UpdateBookingResourceByIdResponse — Responses from the 'update_booking_resource_by_id' procedure
type UpdateBookingResourceByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AssignedUnit selects the "assignedUnit" field; nil when the column is NULL.
		AssignedUnit *string `graphql:"assignedUnit"`
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// CancelReason selects the "cancelReason" field; nil when the column is NULL.
		CancelReason *string `graphql:"cancelReason"`
		// CancelTime selects the "cancelTime" field; nil when the column is NULL.
		CancelTime *string `graphql:"cancelTime"`
		// ConfirmTime selects the "confirmTime" field; nil when the column is NULL.
		ConfirmTime *string `graphql:"confirmTime"`
		// ContactId selects the "contactId" field; nil when the column is NULL.
		ContactId *string `graphql:"contactId"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Customer selects the "customer" field; nil when the column is NULL.
		Customer *string `graphql:"customer"`
		// DiscountId selects the "discountId" field; nil when the column is NULL.
		DiscountId *string `graphql:"discountId"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// HoldExpireTime selects the "holdExpireTime" field; nil when the column is NULL.
		HoldExpireTime *string `graphql:"holdExpireTime"`
		// HoldTtl selects the "holdTtl" field; nil when the column is NULL.
		HoldTtl *string `graphql:"holdTtl"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Notes selects the "notes" field; nil when the column is NULL.
		Notes *string `graphql:"notes"`
		// OccupancyId selects the "occupancyId" field; nil when the column is NULL.
		OccupancyId *string `graphql:"occupancyId"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PromoCode selects the "promoCode" field; nil when the column is NULL.
		PromoCode *string `graphql:"promoCode"`
		// RefundAmountId selects the "refundAmountId" field; nil when the column is NULL.
		RefundAmountId *string `graphql:"refundAmountId"`
		// RefundPercent selects the "refundPercent" field; nil when the column is NULL.
		RefundPercent *int32 `graphql:"refundPercent"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// TotalId selects the "totalId" field; nil when the column is NULL.
		TotalId *string `graphql:"totalId"`
		// Unit selects the "unit" field.
		Unit string `graphql:"unit"`
		// Units selects the "units" field; nil when the column is NULL.
		Units *int32 `graphql:"units"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
		// WindowId selects the "windowId" field.
		WindowId string `graphql:"windowId"`
	} `graphql:"returning"`
}
