// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  availabilityexceptionsql
//
// orm — https://github.com/the-protobuf-project/orm

package availabilityexceptionsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one ScheduleAvailabilityExceptions row.
type CreateInput struct {
	// CreateTime sets the "createTime" column; the zero value is omitted (column default / NULL).
	CreateTime string `json:"createTime,omitzero"`
	// DateRangeId sets the "dateRangeId" column; the zero value is omitted (column default / NULL).
	DateRangeId string `json:"dateRangeId,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Kind sets the "kind" column; the zero value is omitted (column default / NULL).
	Kind string `json:"kind,omitzero"`
	// Name sets the "name" column (required).
	Name string `json:"name"`
	// PropertyId sets the "propertyId" column (required).
	PropertyId string `json:"propertyId"`
	// Reason sets the "reason" column; the zero value is omitted (column default / NULL).
	Reason string `json:"reason,omitzero"`
	// SpanCase sets the "spanCase" column; the zero value is omitted (column default / NULL).
	SpanCase string `json:"spanCase,omitzero"`
	// UnitId sets the "unitId" column (required).
	UnitId string `json:"unitId"`
	// WindowId sets the "windowId" column; the zero value is omitted (column default / NULL).
	WindowId string `json:"windowId,omitzero"`
}

// UpdateInput holds the fields to change on a ScheduleAvailabilityExceptions row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'create_time' column in the 'schedule_availability_exceptions' collection.
	CreateTime graphql.Nullable[string] `json:"createTime"`
	// Update the 'date_range_id' column in the 'schedule_availability_exceptions' collection.
	DateRangeId graphql.Nullable[string] `json:"dateRangeId"`
	// Update the 'id' column in the 'schedule_availability_exceptions' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'kind' column in the 'schedule_availability_exceptions' collection.
	Kind graphql.Nullable[string] `json:"kind"`
	// Update the 'name' column in the 'schedule_availability_exceptions' collection.
	Name graphql.Nullable[string] `json:"name"`
	// Update the 'property_id' column in the 'schedule_availability_exceptions' collection.
	PropertyId graphql.Nullable[string] `json:"propertyId"`
	// Update the 'reason' column in the 'schedule_availability_exceptions' collection.
	Reason graphql.Nullable[string] `json:"reason"`
	// Update the 'span_case' column in the 'schedule_availability_exceptions' collection.
	SpanCase graphql.Nullable[string] `json:"spanCase"`
	// Update the 'unit_id' column in the 'schedule_availability_exceptions' collection.
	UnitId graphql.Nullable[string] `json:"unitId"`
	// Update the 'window_id' column in the 'schedule_availability_exceptions' collection.
	WindowId graphql.Nullable[string] `json:"windowId"`
}
