// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  availabilityexceptionsql
//
// orm — https://github.com/the-protobuf-project/orm

package availabilityexceptionsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteScheduleAvailabilityExceptionsByIdResponse — Responses from the 'delete_schedule_availability_exceptions_by_id' procedure
type DeleteScheduleAvailabilityExceptionsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// DateRangeId selects the "dateRangeId" field; nil when the column is NULL.
		DateRangeId *string `graphql:"dateRangeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Kind selects the "kind" field.
		Kind string `graphql:"kind"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// Reason selects the "reason" field; nil when the column is NULL.
		Reason *string `graphql:"reason"`
		// SpanCase selects the "spanCase" field; nil when the column is NULL.
		SpanCase *string `graphql:"spanCase"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
		// WindowId selects the "windowId" field; nil when the column is NULL.
		WindowId *string `graphql:"windowId"`
	} `graphql:"returning"`
}

// InsertScheduleAvailabilityExceptionsResponse — Responses from the 'insert_schedule_availability_exceptions' procedure
type InsertScheduleAvailabilityExceptionsResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// DateRangeId selects the "dateRangeId" field; nil when the column is NULL.
		DateRangeId *string `graphql:"dateRangeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Kind selects the "kind" field.
		Kind string `graphql:"kind"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// Reason selects the "reason" field; nil when the column is NULL.
		Reason *string `graphql:"reason"`
		// SpanCase selects the "spanCase" field; nil when the column is NULL.
		SpanCase *string `graphql:"spanCase"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
		// WindowId selects the "windowId" field; nil when the column is NULL.
		WindowId *string `graphql:"windowId"`
	} `graphql:"returning"`
}

// ScheduleAvailabilityExceptions is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type ScheduleAvailabilityExceptions struct {
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// DateRangeId selects the "dateRangeId" field; nil when the column is NULL.
	DateRangeId *string `graphql:"dateRangeId"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Kind selects the "kind" field.
	Kind string `graphql:"kind"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// PropertyId selects the "propertyId" field.
	PropertyId string `graphql:"propertyId"`
	// Reason selects the "reason" field; nil when the column is NULL.
	Reason *string `graphql:"reason"`
	// SpanCase selects the "spanCase" field; nil when the column is NULL.
	SpanCase *string `graphql:"spanCase"`
	// UnitId selects the "unitId" field.
	UnitId string `graphql:"unitId"`
	// WindowId selects the "windowId" field; nil when the column is NULL.
	WindowId *string `graphql:"windowId"`
}

// ScheduleAvailabilityExceptionsAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type ScheduleAvailabilityExceptionsAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// DateRangeId selects the "dateRangeId" field.
	DateRangeId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"dateRangeId"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Kind selects the "kind" field.
	Kind struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"kind"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// PropertyId selects the "propertyId" field.
	PropertyId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"propertyId"`
	// Reason selects the "reason" field.
	Reason struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"reason"`
	// SpanCase selects the "spanCase" field.
	SpanCase struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"spanCase"`
	// UnitId selects the "unitId" field.
	UnitId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"unitId"`
	// WindowId selects the "windowId" field.
	WindowId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"windowId"`
}

// UpdateScheduleAvailabilityExceptionsByIdResponse — Responses from the 'update_schedule_availability_exceptions_by_id' procedure
type UpdateScheduleAvailabilityExceptionsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// DateRangeId selects the "dateRangeId" field; nil when the column is NULL.
		DateRangeId *string `graphql:"dateRangeId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Kind selects the "kind" field.
		Kind string `graphql:"kind"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// Reason selects the "reason" field; nil when the column is NULL.
		Reason *string `graphql:"reason"`
		// SpanCase selects the "spanCase" field; nil when the column is NULL.
		SpanCase *string `graphql:"spanCase"`
		// UnitId selects the "unitId" field.
		UnitId string `graphql:"unitId"`
		// WindowId selects the "windowId" field; nil when the column is NULL.
		WindowId *string `graphql:"windowId"`
	} `graphql:"returning"`
}
