// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  losdiscountsql
//
// orm — https://github.com/the-protobuf-project/orm

package losdiscountsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyLosDiscountsByIdResponse = schemaql.DeletePropertyLosDiscountsByIdResponse
type InsertPropertyLosDiscountsResponse = schemaql.InsertPropertyLosDiscountsResponse
type PropertyLosDiscounts = schemaql.PropertyLosDiscounts
type PropertyLosDiscountsAggExp = schemaql.PropertyLosDiscountsAggExp
type UpdatePropertyLosDiscountsByIdResponse = schemaql.UpdatePropertyLosDiscountsByIdResponse
