// Code generated by protoc-gen-orm. DO NOT EDIT.

package scopesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeScopes row.
type CreateInput struct {
	Id            string `json:"id"`
	MinSubtotalId string `json:"minSubtotalId,omitzero"`
}

// UpdateInput holds the fields to change on a PromocodeScopes row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'id' column in the 'promocode_scopes' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'min_subtotal_id' column in the 'promocode_scopes' collection.
	MinSubtotalId graphql.Nullable[string] `json:"minSubtotalId"`
}
