// Code generated by protoc-gen-orm. DO NOT EDIT.

package scopesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeScopesByIdResponse = schemaql.DeletePromocodeScopesByIdResponse
type InsertPromocodeScopesResponse = schemaql.InsertPromocodeScopesResponse
type PromocodeScopes = schemaql.PromocodeScopes
type PromocodeScopesAggExp = schemaql.PromocodeScopesAggExp
type UpdatePromocodeScopesByIdResponse = schemaql.UpdatePromocodeScopesByIdResponse
