// Code generated by generateql. DO NOT EDIT.

package daterangesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/sharedql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteSharedDateRangesByIdResponse = schemaql.DeleteSharedDateRangesByIdResponse
type InsertSharedDateRangesResponse = schemaql.InsertSharedDateRangesResponse
type SharedDateRanges = schemaql.SharedDateRanges
type SharedDateRangesAggExp = schemaql.SharedDateRangesAggExp
type UpdateSharedDateRangesByIdResponse = schemaql.UpdateSharedDateRangesByIdResponse
