// Code generated by generateql. DO NOT EDIT.

package schemaql

// DeleteIdentityGuestsByIdResponse is the DeleteIdentityGuestsByIdResponse model.
type DeleteIdentityGuestsByIdResponse struct {
	AffectedRows int32 `graphql:"affectedRows"`
	Returning    []struct {
		AgeGroup           *string `graphql:"ageGroup"`
		BirthDate          *string `graphql:"birthDate"`
		BookingId          string  `graphql:"bookingId"`
		DisplayName        string  `graphql:"displayName"`
		Email              *string `graphql:"email"`
		ForeignerId        *string `graphql:"foreignerId"`
		Gender             *string `graphql:"gender"`
		Id                 string  `graphql:"id"`
		IdDocumentId       *string `graphql:"idDocumentId"`
		LocalAddressId     *string `graphql:"localAddressId"`
		Nationality        *string `graphql:"nationality"`
		PermanentAddressId *string `graphql:"permanentAddressId"`
		PhoneNumber        *string `graphql:"phoneNumber"`
		PreferencesId      *string `graphql:"preferencesId"`
		Primary            *bool   `graphql:"primary"`
	} `graphql:"returning"`
}
