// Code generated by generateql. DO NOT EDIT.

package schemaql

// IdentityMembershipSummaries is the IdentityMembershipSummaries model.
type IdentityMembershipSummaries struct {
	Id             string  `graphql:"id"`
	OrgDisplayName *string `graphql:"orgDisplayName"`
	Organisation   *string `graphql:"organisation"`
	Role           *string `graphql:"role"`
	UserId         string  `graphql:"userId"`
}
