// Code generated by generateql. DO NOT EDIT.

package schemaql

// IdentityUsers is the IdentityUsers model.
type IdentityUsers struct {
	AvatarUrl   *string `graphql:"avatarUrl"`
	CreateTime  string  `graphql:"createTime"`
	DisplayName *string `graphql:"displayName"`
	Email       *string `graphql:"email"`
	Etag        *string `graphql:"etag"`
	Id          string  `graphql:"id"`
	Locale      *string `graphql:"locale"`
	Name        string  `graphql:"name"`
	TimeZone    *string `graphql:"timeZone"`
	UpdateTime  string  `graphql:"updateTime"`
}
