// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
// source: freebusy/channel/v1/channel.proto, freebusy/channel/v1/channel_messages.proto
//
// database: freebusy
// schema:   channel
//
// Field-mask merge functions shared by every adapter of this schema.
//
// orm — https://github.com/the-protobuf-project/orm

package channel

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/channel/v1/channelpbv1"
)

// applyChannelMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyChannelMask(merged, in *channelpbv1.Channel, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "property") {
		merged.Property = in.GetProperty()
	}
	if repox.InMask(paths, "type") {
		merged.Type = in.GetType()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "external_property_id") {
		merged.ExternalPropertyId = in.GetExternalPropertyId()
	}
	if repox.InMask(paths, "credential_ref") {
		merged.CredentialRef = in.GetCredentialRef()
	}
}

// applyUnitMappingMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyUnitMappingMask(merged, in *channelpbv1.UnitMapping, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "external_room_type_id") {
		merged.ExternalRoomTypeId = in.GetExternalRoomTypeId()
	}
	if repox.InMask(paths, "external_rate_plan_id") {
		merged.ExternalRatePlanId = in.GetExternalRatePlanId()
	}
}
