// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
// source: freebusy/booking/v1/booking.proto
//
// database: freebusy
// schema:   booking
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
//
// orm — https://github.com/the-protobuf-project/orm

package booking

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/booking"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/booking/v1/bookingpbv1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormBookingRepository is the GORM adapter of BookingRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormBookingRepository struct {
	DB    *gorm.DB
	Hooks BookingHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormBookingRepository returns the GORM adapter bound to db.
func NewGormBookingRepository(db *gorm.DB) *GormBookingRepository {
	return &GormBookingRepository{DB: db}
}

// Create persists in and returns the stored record.
func (r *GormBookingRepository) Create(ctx context.Context, in *bookingpbv1.Booking) (*bookingpbv1.Booking, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "bookings")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*bookingpbv1.Booking)
	in.Name = FormatBookingName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := booking.BookingFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	if v := in.GetCustomer(); v != "" {
		m.CustomerID = repox.Ptr(repox.LastSegment(v))
	}
	if v := in.GetPromoCode(); v != "" {
		m.PromoCodeID = repox.Ptr(repox.LastSegment(v))
	}
	m.Etag = repox.Ptr(repox.NewULID())
	if err := booking.NewBookingStore(r.DB).Create(ctx, m); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormBookingRepository) Get(ctx context.Context, name string) (*bookingpbv1.Booking, error) {
	ids, err := repox.SplitName(name, "bookings")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormBookingRepository) get(ctx context.Context, id string) (*bookingpbv1.Booking, error) {
	var m booking.Booking
	if err := r.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormBookingRepository) toProto(ctx context.Context, m *booking.Booking) (*bookingpbv1.Booking, error) {
	out := booking.BookingToProto(m)
	if m.CustomerID != nil && *m.CustomerID != "" {
		out.Customer = "users/" + *m.CustomerID
	}
	if m.PromoCodeID != nil && *m.PromoCodeID != "" {
		out.PromoCode = "promoCodes/" + *m.PromoCodeID
	}
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GormBookingRepository) List(ctx context.Context, in repox.ListInput) ([]*bookingpbv1.Booking, string, error) {
	return r.list(ctx, r.DB, in)
}

func (r *GormBookingRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*bookingpbv1.Booking, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[booking.Booking](booking.BookingFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope, filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*bookingpbv1.Booking, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormBookingRepository) Update(ctx context.Context, in *bookingpbv1.Booking, paths []string) (*bookingpbv1.Booking, error) {
	ids, err := repox.SplitName(in.GetName(), "bookings")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing booking.Booking
		if err := tx.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		if in.GetEtag() != "" && existing.Etag != nil && *existing.Etag != in.GetEtag() {
			return repox.ErrConflict
		}
		existingPB := booking.BookingToProto(&existing)
		{
			m, out := &existing, existingPB
			if m.CustomerID != nil && *m.CustomerID != "" {
				out.Customer = "users/" + *m.CustomerID
			}
			if m.PromoCodeID != nil && *m.PromoCodeID != "" {
				out.PromoCode = "promoCodes/" + *m.PromoCodeID
			}
		}
		merged := proto.Clone(existingPB).(*bookingpbv1.Booking)
		applyBookingMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := booking.BookingFromProto(merged)
		_ = next
		existing.Name = next.Name
		if v := merged.GetCustomer(); v != "" {
			existing.CustomerID = repox.Ptr(repox.LastSegment(v))
		} else {
			existing.CustomerID = nil
		}
		existing.Units = next.Units
		if v := merged.GetPromoCode(); v != "" {
			existing.PromoCodeID = repox.Ptr(repox.LastSegment(v))
		} else {
			existing.PromoCodeID = nil
		}
		existing.Notes = next.Notes
		existing.Attributes = next.Attributes
		existing.HoldTtl = next.HoldTtl
		existing.Etag = repox.Ptr(repox.NewULID())
		return booking.NewBookingStore(tx).Update(ctx, &existing)
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormBookingRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "bookings")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing booking.Booking
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(booking.NewBookingStore(r.DB).DeleteByID(ctx, id))
}

// Compile-time proof the adapter satisfies the interface.
var _ BookingRepository = (*GormBookingRepository)(nil)
