// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  discountsql
//
// orm — https://github.com/the-protobuf-project/orm

package discountsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/promocodeql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePromocodeDiscountsByIdResponse = schemaql.DeletePromocodeDiscountsByIdResponse
type InsertPromocodeDiscountsResponse = schemaql.InsertPromocodeDiscountsResponse
type PromocodeDiscounts = schemaql.PromocodeDiscounts
type PromocodeDiscountsAggExp = schemaql.PromocodeDiscountsAggExp
type UpdatePromocodeDiscountsByIdResponse = schemaql.UpdatePromocodeDiscountsByIdResponse
