// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  stayconstraintsql
//
// orm — https://github.com/the-protobuf-project/orm

package stayconstraintsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/scheduleql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeleteScheduleStayConstraintsByIdResponse = schemaql.DeleteScheduleStayConstraintsByIdResponse
type InsertScheduleStayConstraintsResponse = schemaql.InsertScheduleStayConstraintsResponse
type ScheduleStayConstraints = schemaql.ScheduleStayConstraints
type ScheduleStayConstraintsAggExp = schemaql.ScheduleStayConstraintsAggExp
type UpdateScheduleStayConstraintsByIdResponse = schemaql.UpdateScheduleStayConstraintsByIdResponse
