// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitsql
//
// orm — https://github.com/the-protobuf-project/orm

package unitsql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePropertyUnitsByIdResponse — Responses from the 'delete_property_units_by_id' procedure
type DeletePropertyUnitsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// BookingMode selects the "bookingMode" field.
		BookingMode string `graphql:"bookingMode"`
		// Capacity selects the "capacity" field; nil when the column is NULL.
		Capacity *int32 `graphql:"capacity"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Description selects the "description" field; nil when the column is NULL.
		Description *string `graphql:"description"`
		// DisplayName selects the "displayName" field.
		DisplayName string `graphql:"displayName"`
		// Duration selects the "duration" field; nil when the column is NULL.
		Duration *string `graphql:"duration"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxOccupancy selects the "maxOccupancy" field; nil when the column is NULL.
		MaxOccupancy *int32 `graphql:"maxOccupancy"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Tags selects the "tags" field.
		Tags []*string `graphql:"tags"`
		// TimeZone selects the "timeZone" field.
		TimeZone string `graphql:"timeZone"`
		// Type selects the "type" field.
		Type string `graphql:"type"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// InsertPropertyUnitsResponse — Responses from the 'insert_property_units' procedure
type InsertPropertyUnitsResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// BookingMode selects the "bookingMode" field.
		BookingMode string `graphql:"bookingMode"`
		// Capacity selects the "capacity" field; nil when the column is NULL.
		Capacity *int32 `graphql:"capacity"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Description selects the "description" field; nil when the column is NULL.
		Description *string `graphql:"description"`
		// DisplayName selects the "displayName" field.
		DisplayName string `graphql:"displayName"`
		// Duration selects the "duration" field; nil when the column is NULL.
		Duration *string `graphql:"duration"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxOccupancy selects the "maxOccupancy" field; nil when the column is NULL.
		MaxOccupancy *int32 `graphql:"maxOccupancy"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Tags selects the "tags" field.
		Tags []*string `graphql:"tags"`
		// TimeZone selects the "timeZone" field.
		TimeZone string `graphql:"timeZone"`
		// Type selects the "type" field.
		Type string `graphql:"type"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// PropertyUnits is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type PropertyUnits struct {
	// Attributes selects the "attributes" field; nil when the column is NULL.
	Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
	// BookingMode selects the "bookingMode" field.
	BookingMode string `graphql:"bookingMode"`
	// Capacity selects the "capacity" field; nil when the column is NULL.
	Capacity *int32 `graphql:"capacity"`
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// Description selects the "description" field; nil when the column is NULL.
	Description *string `graphql:"description"`
	// DisplayName selects the "displayName" field.
	DisplayName string `graphql:"displayName"`
	// Duration selects the "duration" field; nil when the column is NULL.
	Duration *string `graphql:"duration"`
	// Etag selects the "etag" field; nil when the column is NULL.
	Etag *string `graphql:"etag"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// MaxOccupancy selects the "maxOccupancy" field; nil when the column is NULL.
	MaxOccupancy *int32 `graphql:"maxOccupancy"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// PriceId selects the "priceId" field; nil when the column is NULL.
	PriceId *string `graphql:"priceId"`
	// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
	PricingUnit *string `graphql:"pricingUnit"`
	// PropertyId selects the "propertyId" field.
	PropertyId string `graphql:"propertyId"`
	// State selects the "state" field; nil when the column is NULL.
	State *string `graphql:"state"`
	// Tags selects the "tags" field.
	Tags []*string `graphql:"tags"`
	// TimeZone selects the "timeZone" field.
	TimeZone string `graphql:"timeZone"`
	// Type selects the "type" field.
	Type string `graphql:"type"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime string `graphql:"updateTime"`
}

// PropertyUnitsAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type PropertyUnitsAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// Attributes selects the "attributes" field.
	Attributes struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	} `graphql:"attributes"`
	// BookingMode selects the "bookingMode" field.
	BookingMode struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"bookingMode"`
	// Capacity selects the "capacity" field.
	Capacity struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"capacity"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// Description selects the "description" field.
	Description struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"description"`
	// DisplayName selects the "displayName" field.
	DisplayName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"displayName"`
	// Duration selects the "duration" field.
	Duration struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"duration"`
	// Etag selects the "etag" field.
	Etag struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"etag"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// MaxOccupancy selects the "maxOccupancy" field.
	MaxOccupancy struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"maxOccupancy"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// PriceId selects the "priceId" field.
	PriceId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"priceId"`
	// PricingUnit selects the "pricingUnit" field.
	PricingUnit struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"pricingUnit"`
	// PropertyId selects the "propertyId" field.
	PropertyId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"propertyId"`
	// State selects the "state" field.
	State struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"state"`
	// TimeZone selects the "timeZone" field.
	TimeZone struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"timeZone"`
	// Type selects the "type" field.
	Type struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"type"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"updateTime"`
}

// UpdatePropertyUnitsByIdResponse — Responses from the 'update_property_units_by_id' procedure
type UpdatePropertyUnitsByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Attributes selects the "attributes" field; nil when the column is NULL.
		Attributes *json.RawMessage `graphql:"attributes" scalar:"true"`
		// BookingMode selects the "bookingMode" field.
		BookingMode string `graphql:"bookingMode"`
		// Capacity selects the "capacity" field; nil when the column is NULL.
		Capacity *int32 `graphql:"capacity"`
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Description selects the "description" field; nil when the column is NULL.
		Description *string `graphql:"description"`
		// DisplayName selects the "displayName" field.
		DisplayName string `graphql:"displayName"`
		// Duration selects the "duration" field; nil when the column is NULL.
		Duration *string `graphql:"duration"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MaxOccupancy selects the "maxOccupancy" field; nil when the column is NULL.
		MaxOccupancy *int32 `graphql:"maxOccupancy"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PriceId selects the "priceId" field; nil when the column is NULL.
		PriceId *string `graphql:"priceId"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// PropertyId selects the "propertyId" field.
		PropertyId string `graphql:"propertyId"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
		// Tags selects the "tags" field.
		Tags []*string `graphql:"tags"`
		// TimeZone selects the "timeZone" field.
		TimeZone string `graphql:"timeZone"`
		// Type selects the "type" field.
		Type string `graphql:"type"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}
