// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitsql
//
// orm — https://github.com/the-protobuf-project/orm

package unitsql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/propertyql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type DeletePropertyUnitsByIdResponse = schemaql.DeletePropertyUnitsByIdResponse
type InsertPropertyUnitsResponse = schemaql.InsertPropertyUnitsResponse
type PropertyUnits = schemaql.PropertyUnits
type PropertyUnitsAggExp = schemaql.PropertyUnitsAggExp
type UpdatePropertyUnitsByIdResponse = schemaql.UpdatePropertyUnitsByIdResponse
