// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.2-0.20260711062657-d8139be6dc50+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  moneysql
//
// orm — https://github.com/the-protobuf-project/orm

package moneysql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/commonql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type CommonMoneys = schemaql.CommonMoneys
type CommonMoneysAggExp = schemaql.CommonMoneysAggExp
type DeleteCommonMoneysByIdResponse = schemaql.DeleteCommonMoneysByIdResponse
type InsertCommonMoneysResponse = schemaql.InsertCommonMoneysResponse
type UpdateCommonMoneysByIdResponse = schemaql.UpdateCommonMoneysByIdResponse
