// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  cancellationpoliciesql
//
// orm — https://github.com/the-protobuf-project/orm

package cancellationpoliciesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for ScheduleCancellationPolicies. Build predicates like Id.Eq(v) and combine
// them with And/Or/Not.
var (
	Id = graphql.StringField{Col: "id"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
