// Code generated by protoc-gen-orm. DO NOT EDIT.

package guestpreferencesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one IdentityGuestPreferences row.
type CreateInput struct {
	Accessibility   []*string `json:"accessibility,omitzero"`
	Bed             string    `json:"bed,omitzero"`
	Dietary         []*string `json:"dietary,omitzero"`
	FloorPreference int32     `json:"floorPreference,omitzero"`
	Id              string    `json:"id"`
	LoyaltyNumber   string    `json:"loyaltyNumber,omitzero"`
	Notes           string    `json:"notes,omitzero"`
	Smoking         string    `json:"smoking,omitzero"`
	SpecialRequests []*string `json:"specialRequests,omitzero"`
}

// UpdateInput holds the fields to change on a IdentityGuestPreferences row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'accessibility' column in the 'identity_guest_preferences' collection.
	Accessibility graphql.Nullable[[]*string] `json:"accessibility"`
	// Update the 'bed' column in the 'identity_guest_preferences' collection.
	Bed graphql.Nullable[string] `json:"bed"`
	// Update the 'dietary' column in the 'identity_guest_preferences' collection.
	Dietary graphql.Nullable[[]*string] `json:"dietary"`
	// Update the 'floor_preference' column in the 'identity_guest_preferences' collection.
	FloorPreference graphql.Nullable[int32] `json:"floorPreference"`
	// Update the 'id' column in the 'identity_guest_preferences' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'loyalty_number' column in the 'identity_guest_preferences' collection.
	LoyaltyNumber graphql.Nullable[string] `json:"loyaltyNumber"`
	// Update the 'notes' column in the 'identity_guest_preferences' collection.
	Notes graphql.Nullable[string] `json:"notes"`
	// Update the 'smoking' column in the 'identity_guest_preferences' collection.
	Smoking graphql.Nullable[string] `json:"smoking"`
	// Update the 'special_requests' column in the 'identity_guest_preferences' collection.
	SpecialRequests graphql.Nullable[[]*string] `json:"specialRequests"`
}
