// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
// source: freebusy/identity/v1/guest.proto, freebusy/identity/v1/identity.proto
//
// database: freebusy
// schema:   identity
//
// AIP resource-name codecs for this schema's repositories.
//
// orm — https://github.com/the-protobuf-project/orm

package identity

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatUserName builds "users/{user}" from bare ids.
func FormatUserName(user string) string {
	return "users" + "/" + user
}

// ParseUserName splits a "users/{user}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseUserName(name string) (user string, err error) {
	ids, err := repox.SplitName(name, "users")
	if err != nil {
		return
	}
	user = ids[0]
	return
}
