// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
// source: freebusy/identity/v1/guest.proto, freebusy/identity/v1/identity.proto
//
// database: freebusy
// schema:   identity
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
//
// orm — https://github.com/the-protobuf-project/orm

package identity

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/identity/v1/identitypbv1"
	"gorm.io/gorm"
)

// UserRepository is the provider-agnostic persistence surface for
// User (users/{user}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type UserRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *identitypbv1.User) (*identitypbv1.User, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*identitypbv1.User, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*identitypbv1.User, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *identitypbv1.User, paths []string) (*identitypbv1.User, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// UserHooks lets custom logic run inside the generated User
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type UserHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *identitypbv1.User) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *identitypbv1.User) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *identitypbv1.User, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Users UserRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	userHooks        UserHooks
	userOverrides    map[string]filterx.SQLHandler
	userGQLOverrides map[string]filterx.GraphQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithUserHooks installs h on the User adapters.
func WithUserHooks(h UserHooks) Option {
	return func(o *options) { o.userHooks = h }
}

// WithUserListOverride substitutes the generated filter dispatch for one
// User filter field (e.g. a derived state computed via subqueries).
func WithUserListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.userOverrides == nil {
			o.userOverrides = map[string]filterx.SQLHandler{}
		}
		o.userOverrides[field] = h
	}
}

// WithUserGraphQLListOverride substitutes the generated filter dispatch
// for one User filter field on the GraphQL adapters.
func WithUserGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.userGQLOverrides == nil {
			o.userGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.userGQLOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn: GraphQL when a
// client connection is present, otherwise GORM.
func New(conn repox.Conn, opts ...Option) Repositories {
	if conn.GraphQL != nil {
		return NewGraphQL(conn.GraphQL, opts...)
	}
	return NewGorm(conn.Gorm, opts...)
}

// NewGraphQL builds the GraphQL adapter set over svc.
func NewGraphQL(svc *freebusyql.Service, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Users: &GraphQLUserRepository{Svc: svc, Hooks: o.userHooks, ListOverrides: o.userGQLOverrides},
	}
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Users: &GormUserRepository{DB: db, Hooks: o.userHooks, ListOverrides: o.userOverrides},
	}
}
