// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  policiesql
//
// orm — https://github.com/the-protobuf-project/orm

package policiesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyPolicies row.
type CreateInput struct {
	// CheckinTime sets the "checkinTime" column; the zero value is omitted (column default / NULL).
	CheckinTime string `json:"checkinTime,omitzero"`
	// CheckoutTime sets the "checkoutTime" column; the zero value is omitted (column default / NULL).
	CheckoutTime string `json:"checkoutTime,omitzero"`
	// HouseRules sets the "houseRules" column; the zero value is omitted (column default / NULL).
	HouseRules []*string `json:"houseRules,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Notes sets the "notes" column; the zero value is omitted (column default / NULL).
	Notes string `json:"notes,omitzero"`
}

// UpdateInput holds the fields to change on a PropertyPolicies row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'checkin_time' column in the 'property_policies' collection.
	CheckinTime graphql.Nullable[string] `json:"checkinTime"`
	// Update the 'checkout_time' column in the 'property_policies' collection.
	CheckoutTime graphql.Nullable[string] `json:"checkoutTime"`
	// Update the 'house_rules' column in the 'property_policies' collection.
	HouseRules graphql.Nullable[[]*string] `json:"houseRules"`
	// Update the 'id' column in the 'property_policies' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'notes' column in the 'property_policies' collection.
	Notes graphql.Nullable[string] `json:"notes"`
}
