// Code generated by generateql. DO NOT EDIT.

package schemaql

// SharedTimeWindows is the SharedTimeWindows model.
type SharedTimeWindows struct {
	EndTime   string `graphql:"endTime"`
	Id        string `graphql:"id"`
	StartTime string `graphql:"startTime"`
}
