// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file freebusy/booking/v1/booking_actions.proto (package freebusy.booking.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_freebusy_booking_v1_booking } from "./booking_pb";
import type { CancelReason } from "./enums_pb";
import { file_freebusy_booking_v1_enums } from "./enums_pb";
import type { TimeWindow } from "../../shared/v1/types_pb";
import { file_freebusy_shared_v1_types } from "../../shared/v1/types_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import { file_google_api_field_info } from "../../../google/api/field_info_pb";
import { file_google_api_resource } from "../../../google/api/resource_pb";
import type { Money } from "../../../google/type/money_pb";
import { file_google_type_money } from "../../../google/type/money_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file freebusy/booking/v1/booking_actions.proto.
 */
export const file_freebusy_booking_v1_booking_actions: GenFile = /*@__PURE__*/
  fileDesc("CilmcmVlYnVzeS9ib29raW5nL3YxL2Jvb2tpbmdfYWN0aW9ucy5wcm90bxITZnJlZWJ1c3kuYm9va2luZy52MSKFAQoVQ29uZmlybUJvb2tpbmdSZXF1ZXN0EjEKBG5hbWUYASABKAlCI+BBAvpBHQobZnJlZWJ1c3kuYm9va2luZy52MS9Cb29raW5nEhgKC3BheW1lbnRfcmVmGAIgASgJQgPgQQESHwoKcmVxdWVzdF9pZBgDIAEoCUIL4EEB4ozP1wgCCAEitQEKFENhbmNlbEJvb2tpbmdSZXF1ZXN0EjEKBG5hbWUYASABKAlCI+BBAvpBHQobZnJlZWJ1c3kuYm9va2luZy52MS9Cb29raW5nEjYKBnJlYXNvbhgCIAEoDjIhLmZyZWVidXN5LmJvb2tpbmcudjEuQ2FuY2VsUmVhc29uQgPgQQESEQoEbm90ZRgDIAEoCUID4EEBEh8KCnJlcXVlc3RfaWQYBCABKAlCC+BBAeKMz9cIAggBItwBChhSZXNjaGVkdWxlQm9va2luZ1JlcXVlc3QSMQoEbmFtZRgBIAEoCUIj4EEC+kEdChtmcmVlYnVzeS5ib29raW5nLnYxL0Jvb2tpbmcSMwoGd2luZG93GAIgASgLMh4uZnJlZWJ1c3kuc2hhcmVkLnYxLlRpbWVXaW5kb3dCA+BBAhI3CghvZmZlcmluZxgDIAEoCUIl4EEB+kEfCh1mcmVlYnVzeS5yZXNvdXJjZS52MS9PZmZlcmluZxIfCgpyZXF1ZXN0X2lkGAQgASgJQgvgQQHijM/XCAIIASJPChpQcmV2aWV3Q2FuY2VsbGF0aW9uUmVxdWVzdBIxCgRuYW1lGAEgASgJQiPgQQL6QR0KG2ZyZWVidXN5LmJvb2tpbmcudjEvQm9va2luZyK/AQobUHJldmlld0NhbmNlbGxhdGlvblJlc3BvbnNlEhIKCnJlZnVuZGFibGUYASABKAgSFgoOcmVmdW5kX3BlcmNlbnQYAiABKAUSKQoNcmVmdW5kX2Ftb3VudBgDIAEoCzISLmdvb2dsZS50eXBlLk1vbmV5EjEKFW5vbl9yZWZ1bmRhYmxlX2Ftb3VudBgEIAEoCzISLmdvb2dsZS50eXBlLk1vbmV5EhYKDnBvbGljeV9zdW1tYXJ5GAUgASgJQvcBChdjb20uZnJlZWJ1c3kuYm9va2luZy52MUITQm9va2luZ0FjdGlvbnNQcm90b1ABWllnaXRodWIuY29tL29oLXRhcm5pc2hlZC9mcmVlYnVzeS9wcm90b2J1Zi9nZW5lcmF0ZWQvZ28vYm9va2luZy92MS9ib29raW5ncGJ2MTtib29raW5ncGJ2MaICA0ZCWKoCE0ZyZWVidXN5LkJvb2tpbmcuVjHKAhNGcmVlYnVzeVxCb29raW5nXFYx4gIfRnJlZWJ1c3lcQm9va2luZ1xWMVxHUEJNZXRhZGF0YeoCFUZyZWVidXN5OjpCb29raW5nOjpWMWIGcHJvdG8z", [file_freebusy_booking_v1_booking, file_freebusy_booking_v1_enums, file_freebusy_shared_v1_types, file_google_api_field_behavior, file_google_api_field_info, file_google_api_resource, file_google_type_money]);

/**
 * Request message for ConfirmBooking. Confirmation normally arrives via the
 * payment webhook rather than a direct client call; either way it flips a
 * PENDING_HOLD to CONFIRMED.
 *
 * @generated from message freebusy.booking.v1.ConfirmBookingRequest
 */
export type ConfirmBookingRequest = Message<"freebusy.booking.v1.ConfirmBookingRequest"> & {
  /**
   * The booking to confirm.
   * Format: bookings/{booking}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Opaque reference to the payment/settlement that confirmed this booking.
   *
   * @generated from field: string payment_ref = 2;
   */
  paymentRef: string;

  /**
   * Caller-supplied idempotency key; identical retries return the first result.
   *
   * @generated from field: string request_id = 3;
   */
  requestId: string;
};

/**
 * Describes the message freebusy.booking.v1.ConfirmBookingRequest.
 * Use `create(ConfirmBookingRequestSchema)` to create a new message.
 */
export const ConfirmBookingRequestSchema: GenMessage<ConfirmBookingRequest> = /*@__PURE__*/
  messageDesc(file_freebusy_booking_v1_booking_actions, 0);

/**
 * Request message for CancelBooking.
 *
 * @generated from message freebusy.booking.v1.CancelBookingRequest
 */
export type CancelBookingRequest = Message<"freebusy.booking.v1.CancelBookingRequest"> & {
  /**
   * The booking to cancel.
   * Format: bookings/{booking}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Why the booking is being cancelled.
   *
   * @generated from field: freebusy.booking.v1.CancelReason reason = 2;
   */
  reason: CancelReason;

  /**
   * Free-form note explaining the cancellation.
   *
   * @generated from field: string note = 3;
   */
  note: string;

  /**
   * Caller-supplied idempotency key; identical retries return the first result.
   *
   * @generated from field: string request_id = 4;
   */
  requestId: string;
};

/**
 * Describes the message freebusy.booking.v1.CancelBookingRequest.
 * Use `create(CancelBookingRequestSchema)` to create a new message.
 */
export const CancelBookingRequestSchema: GenMessage<CancelBookingRequest> = /*@__PURE__*/
  messageDesc(file_freebusy_booking_v1_booking_actions, 1);

/**
 * Request message for RescheduleBooking. Atomically moves a booking to a new
 * span (and optionally offering), re-running availability and the exclusion
 * check on the new window.
 *
 * @generated from message freebusy.booking.v1.RescheduleBookingRequest
 */
export type RescheduleBookingRequest = Message<"freebusy.booking.v1.RescheduleBookingRequest"> & {
  /**
   * The booking to reschedule.
   * Format: bookings/{booking}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The new reserved span.
   *
   * @generated from field: freebusy.shared.v1.TimeWindow window = 2;
   */
  window?: TimeWindow | undefined;

  /**
   * The new offering, when changing it as part of the reschedule.
   * Format: resources/{resource}/offerings/{offering}
   *
   * @generated from field: string offering = 3;
   */
  offering: string;

  /**
   * Caller-supplied idempotency key that dedupes retries of this reschedule.
   *
   * @generated from field: string request_id = 4;
   */
  requestId: string;
};

/**
 * Describes the message freebusy.booking.v1.RescheduleBookingRequest.
 * Use `create(RescheduleBookingRequestSchema)` to create a new message.
 */
export const RescheduleBookingRequestSchema: GenMessage<RescheduleBookingRequest> = /*@__PURE__*/
  messageDesc(file_freebusy_booking_v1_booking_actions, 2);

/**
 * Request message for PreviewCancellation. Computes the refund a cancellation
 * would yield right now, under the resource's cancellation policy, without
 * cancelling the booking.
 *
 * @generated from message freebusy.booking.v1.PreviewCancellationRequest
 */
export type PreviewCancellationRequest = Message<"freebusy.booking.v1.PreviewCancellationRequest"> & {
  /**
   * The booking to preview a cancellation for.
   * Format: bookings/{booking}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message freebusy.booking.v1.PreviewCancellationRequest.
 * Use `create(PreviewCancellationRequestSchema)` to create a new message.
 */
export const PreviewCancellationRequestSchema: GenMessage<PreviewCancellationRequest> = /*@__PURE__*/
  messageDesc(file_freebusy_booking_v1_booking_actions, 3);

/**
 * Response message for PreviewCancellation.
 *
 * @generated from message freebusy.booking.v1.PreviewCancellationResponse
 */
export type PreviewCancellationResponse = Message<"freebusy.booking.v1.PreviewCancellationResponse"> & {
  /**
   * Whether cancelling now would refund anything.
   *
   * @generated from field: bool refundable = 1;
   */
  refundable: boolean;

  /**
   * Percentage of the total that would be refunded (0-100).
   *
   * @generated from field: int32 refund_percent = 2;
   */
  refundPercent: number;

  /**
   * Amount that would be refunded now.
   *
   * @generated from field: google.type.Money refund_amount = 3;
   */
  refundAmount?: Money | undefined;

  /**
   * Amount that would be retained (total minus refund_amount).
   *
   * @generated from field: google.type.Money non_refundable_amount = 4;
   */
  nonRefundableAmount?: Money | undefined;

  /**
   * Human-readable summary of the policy tier that applied, for display.
   *
   * @generated from field: string policy_summary = 5;
   */
  policySummary: string;
};

/**
 * Describes the message freebusy.booking.v1.PreviewCancellationResponse.
 * Use `create(PreviewCancellationResponseSchema)` to create a new message.
 */
export const PreviewCancellationResponseSchema: GenMessage<PreviewCancellationResponse> = /*@__PURE__*/
  messageDesc(file_freebusy_booking_v1_booking_actions, 4);

