// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file freebusy/booking/v1/enums.proto (package freebusy.booking.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file freebusy/booking/v1/enums.proto.
 */
export const file_freebusy_booking_v1_enums: GenFile = /*@__PURE__*/
  fileDesc("Ch9mcmVlYnVzeS9ib29raW5nL3YxL2VudW1zLnByb3RvEhNmcmVlYnVzeS5ib29raW5nLnYxKtoBCgxCb29raW5nU3RhdGUSHQoZQk9PS0lOR19TVEFURV9VTlNQRUNJRklFRBAAEh4KGkJPT0tJTkdfU1RBVEVfUEVORElOR19IT0xEEAESGwoXQk9PS0lOR19TVEFURV9DT05GSVJNRUQQAhIbChdCT09LSU5HX1NUQVRFX0NBTkNFTExFRBADEhkKFUJPT0tJTkdfU1RBVEVfRVhQSVJFRBAEEhsKF0JPT0tJTkdfU1RBVEVfQ09NUExFVEVEEAUSGQoVQk9PS0lOR19TVEFURV9OT19TSE9XEAYq1QEKDENhbmNlbFJlYXNvbhIdChlDQU5DRUxfUkVBU09OX1VOU1BFQ0lGSUVEEAASJwojQ0FOQ0VMX1JFQVNPTl9SRVFVRVNURURfQllfQ1VTVE9NRVIQARInCiNDQU5DRUxfUkVBU09OX1JFUVVFU1RFRF9CWV9PUEVSQVRPUhACEiAKHENBTkNFTF9SRUFTT05fUEFZTUVOVF9GQUlMRUQQAxIZChVDQU5DRUxfUkVBU09OX05PX1NIT1cQBBIXChNDQU5DRUxfUkVBU09OX09USEVSEAVC7gEKF2NvbS5mcmVlYnVzeS5ib29raW5nLnYxQgpFbnVtc1Byb3RvUAFaWWdpdGh1Yi5jb20vb2gtdGFybmlzaGVkL2ZyZWVidXN5L3Byb3RvYnVmL2dlbmVyYXRlZC9nby9ib29raW5nL3YxL2Jvb2tpbmdwYnYxO2Jvb2tpbmdwYnYxogIDRkJYqgITRnJlZWJ1c3kuQm9va2luZy5WMcoCE0ZyZWVidXN5XEJvb2tpbmdcVjHiAh9GcmVlYnVzeVxCb29raW5nXFYxXEdQQk1ldGFkYXRh6gIVRnJlZWJ1c3k6OkJvb2tpbmc6OlYxYgZwcm90bzM");

/**
 * Lifecycle state of a booking.
 *
 * @generated from enum freebusy.booking.v1.BookingState
 */
export enum BookingState {
  /**
   * Unset.
   *
   * @generated from enum value: BOOKING_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Held but not yet confirmed; expires at hold_expire_time.
   *
   * @generated from enum value: BOOKING_STATE_PENDING_HOLD = 1;
   */
  PENDING_HOLD = 1,

  /**
   * Confirmed and active.
   *
   * @generated from enum value: BOOKING_STATE_CONFIRMED = 2;
   */
  CONFIRMED = 2,

  /**
   * Cancelled by customer or operator.
   *
   * @generated from enum value: BOOKING_STATE_CANCELLED = 3;
   */
  CANCELLED = 3,

  /**
   * Hold lapsed before confirmation (released by the sweeper).
   *
   * @generated from enum value: BOOKING_STATE_EXPIRED = 4;
   */
  EXPIRED = 4,

  /**
   * The booked time has passed and the booking was honored.
   *
   * @generated from enum value: BOOKING_STATE_COMPLETED = 5;
   */
  COMPLETED = 5,

  /**
   * The customer did not show.
   *
   * @generated from enum value: BOOKING_STATE_NO_SHOW = 6;
   */
  NO_SHOW = 6,
}

/**
 * Describes the enum freebusy.booking.v1.BookingState.
 */
export const BookingStateSchema: GenEnum<BookingState> = /*@__PURE__*/
  enumDesc(file_freebusy_booking_v1_enums, 0);

/**
 * Why a booking was cancelled.
 *
 * @generated from enum freebusy.booking.v1.CancelReason
 */
export enum CancelReason {
  /**
   * Unset.
   *
   * @generated from enum value: CANCEL_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The customer requested cancellation.
   *
   * @generated from enum value: CANCEL_REASON_REQUESTED_BY_CUSTOMER = 1;
   */
  REQUESTED_BY_CUSTOMER = 1,

  /**
   * An operator cancelled it.
   *
   * @generated from enum value: CANCEL_REASON_REQUESTED_BY_OPERATOR = 2;
   */
  REQUESTED_BY_OPERATOR = 2,

  /**
   * Payment failed or was not completed in time.
   *
   * @generated from enum value: CANCEL_REASON_PAYMENT_FAILED = 3;
   */
  PAYMENT_FAILED = 3,

  /**
   * The customer did not show.
   *
   * @generated from enum value: CANCEL_REASON_NO_SHOW = 4;
   */
  NO_SHOW = 4,

  /**
   * Any other reason.
   *
   * @generated from enum value: CANCEL_REASON_OTHER = 5;
   */
  OTHER = 5,
}

/**
 * Describes the enum freebusy.booking.v1.CancelReason.
 */
export const CancelReasonSchema: GenEnum<CancelReason> = /*@__PURE__*/
  enumDesc(file_freebusy_booking_v1_enums, 1);

