// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  feesql
//
// orm — https://github.com/the-protobuf-project/orm

package feesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PropertyFees row.
type CreateInput struct {
	// AmountId sets the "amountId" column; the zero value is omitted (column default / NULL).
	AmountId string `json:"amountId,omitzero"`
	// Code sets the "code" column (required).
	Code string `json:"code"`
	// DisplayName sets the "displayName" column; the zero value is omitted (column default / NULL).
	DisplayName string `json:"displayName,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Percent sets the "percent" column; the zero value is omitted (column default / NULL).
	Percent int32 `json:"percent,omitzero"`
	// PricingUnit sets the "pricingUnit" column; the zero value is omitted (column default / NULL).
	PricingUnit string `json:"pricingUnit,omitzero"`
	// Taxable sets the "taxable" column; the zero value is omitted (column default / NULL).
	Taxable bool `json:"taxable,omitzero"`
	// UnitId sets the "unitId" column (required).
	UnitId string `json:"unitId"`
}

// UpdateInput holds the fields to change on a PropertyFees row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'amount_id' column in the 'property_fees' collection.
	AmountId graphql.Nullable[string] `json:"amountId"`
	// Update the 'code' column in the 'property_fees' collection.
	Code graphql.Nullable[string] `json:"code"`
	// Update the 'display_name' column in the 'property_fees' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'id' column in the 'property_fees' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'percent' column in the 'property_fees' collection.
	Percent graphql.Nullable[int32] `json:"percent"`
	// Update the 'pricing_unit' column in the 'property_fees' collection.
	PricingUnit graphql.Nullable[string] `json:"pricingUnit"`
	// Update the 'taxable' column in the 'property_fees' collection.
	Taxable graphql.Nullable[bool] `json:"taxable"`
	// Update the 'unit_id' column in the 'property_fees' collection.
	UnitId graphql.Nullable[string] `json:"unitId"`
}
