// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm 1.4.2
// 	protoc (unknown)
//
// database: freebusyql
// package:  scopeapplicableunitsql
//
// orm — https://github.com/the-protobuf-project/orm

package scopeapplicableunitsql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PromocodeScopeApplicableUnits query operations.
type QueryHandler interface {
	// List runs the "promocodeScopeApplicableUnits" query.
	List(ctx context.Context, req ...*ListRequest) ([]PromocodeScopeApplicableUnits, error)
	// Find runs the "promocodeScopeApplicableUnits" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*PromocodeScopeApplicableUnits, error)
	// Aggregate runs the "promocodeScopeApplicableUnitsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*PromocodeScopeApplicableUnitsAggExp, error)
	// Get runs the "promocodeScopeApplicableUnitsById" query.
	Get(ctx context.Context, id string) (*PromocodeScopeApplicableUnits, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PromocodeScopeApplicableUnits mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePromocodeScopeApplicableUnitsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeletePromocodeScopeApplicableUnitsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeletePromocodeScopeApplicableUnitsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPromocodeScopeApplicableUnits" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertPromocodeScopeApplicableUnitsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertPromocodeScopeApplicableUnitsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePromocodeScopeApplicableUnitsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdatePromocodeScopeApplicableUnitsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdatePromocodeScopeApplicableUnitsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdatePromocodeScopeApplicableUnitsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PromocodeScopeApplicableUnits subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "promocodeScopeApplicableUnits" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "promocodeScopeApplicableUnitsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "promocodeScopeApplicableUnitsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[PromocodeScopeApplicableUnits] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertPromocodeScopeApplicableUnitsResponse, UpdatePromocodeScopeApplicableUnitsByIdResponse, DeletePromocodeScopeApplicableUnitsByIdResponse] = (*mutationHandler)(nil)
