// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.


package promocode

import (
	"context"
	"fmt"
	"log/slog"
	"math"
	"net/url"
	"time"

	gax "github.com/googleapis/gax-go/v2"
	promocodepbv1pb "github.com/oh-tarnished/freebusy/protobuf/generated/go/promocode/v1/promocodepbv1"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/protobuf/proto"
)

var newClientHook clientHook

// CallOptions contains the retry settings for each method of Client.
type CallOptions struct {
	ListPromoCodes []gax.CallOption
	GetPromoCode []gax.CallOption
	CreatePromoCode []gax.CallOption
	UpdatePromoCode []gax.CallOption
	DeletePromoCode []gax.CallOption
	ValidatePromoCode []gax.CallOption
	ListRedemptions []gax.CallOption
	GetRedemption []gax.CallOption
}

func defaultGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("freebusy.ohtarnished.dev:443"),
		internaloption.WithDefaultEndpointTemplate("freebusy.ohtarnished.dev:443"),
		internaloption.WithDefaultMTLSEndpoint("freebusy.ohtarnished.dev:443"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://freebusy.ohtarnished.dev/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
		grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultCallOptions() *CallOptions {
	return &CallOptions{
		ListPromoCodes: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		GetPromoCode: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		CreatePromoCode: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		UpdatePromoCode: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		DeletePromoCode: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		ValidatePromoCode: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		ListRedemptions: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
		GetRedemption: []gax.CallOption{
			gax.WithTimeout(30000 * time.Millisecond),
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    100 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 2.00,
				})
			}),
		},
	}
}

// internalClient is an interface that defines the methods available from FreeBusy API.
type internalClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	ListPromoCodes(context.Context, *promocodepbv1pb.ListPromoCodesRequest, ...gax.CallOption) *PromoCodeIterator
	GetPromoCode(context.Context, *promocodepbv1pb.GetPromoCodeRequest, ...gax.CallOption) (*promocodepbv1pb.PromoCode, error)
	CreatePromoCode(context.Context, *promocodepbv1pb.CreatePromoCodeRequest, ...gax.CallOption) (*promocodepbv1pb.PromoCode, error)
	UpdatePromoCode(context.Context, *promocodepbv1pb.UpdatePromoCodeRequest, ...gax.CallOption) (*promocodepbv1pb.PromoCode, error)
	DeletePromoCode(context.Context, *promocodepbv1pb.DeletePromoCodeRequest, ...gax.CallOption) error
	ValidatePromoCode(context.Context, *promocodepbv1pb.ValidatePromoCodeRequest, ...gax.CallOption) (*promocodepbv1pb.ValidatePromoCodeResponse, error)
	ListRedemptions(context.Context, *promocodepbv1pb.ListRedemptionsRequest, ...gax.CallOption) *RedemptionIterator
	GetRedemption(context.Context, *promocodepbv1pb.GetRedemptionRequest, ...gax.CallOption) (*promocodepbv1pb.Redemption, error)
}

// Client is a client for interacting with FreeBusy API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// PromoCodeService manages redeemable discount codes and validates them against
// a prospective booking. Redemption itself happens inside CreateBooking.
type Client struct {
	// The internal transport-dependent client.
	internalClient internalClient

	// The call options for this service.
	CallOptions *CallOptions

}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. **Always** call Close() when
// the client is no longer required.
func (c *Client) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *Client) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *Client) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// ListPromoCodes lists promo codes.
func (c *Client) ListPromoCodes(ctx context.Context, req *promocodepbv1pb.ListPromoCodesRequest, opts ...gax.CallOption) *PromoCodeIterator {
	return c.internalClient.ListPromoCodes(ctx, req, opts...)
}

// GetPromoCode gets a single promo code.
func (c *Client) GetPromoCode(ctx context.Context, req *promocodepbv1pb.GetPromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	return c.internalClient.GetPromoCode(ctx, req, opts...)
}

// CreatePromoCode creates a promo code.
func (c *Client) CreatePromoCode(ctx context.Context, req *promocodepbv1pb.CreatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	return c.internalClient.CreatePromoCode(ctx, req, opts...)
}

// UpdatePromoCode updates a promo code.
func (c *Client) UpdatePromoCode(ctx context.Context, req *promocodepbv1pb.UpdatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	return c.internalClient.UpdatePromoCode(ctx, req, opts...)
}

// DeletePromoCode deletes a promo code.
func (c *Client) DeletePromoCode(ctx context.Context, req *promocodepbv1pb.DeletePromoCodeRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeletePromoCode(ctx, req, opts...)
}

// ValidatePromoCode validates a code against a prospective booking and returns the discount.
func (c *Client) ValidatePromoCode(ctx context.Context, req *promocodepbv1pb.ValidatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.ValidatePromoCodeResponse, error) {
	return c.internalClient.ValidatePromoCode(ctx, req, opts...)
}

// ListRedemptions lists redemptions of a promo code (paged). Redemptions are created during
// CreateBooking, so this service exposes read-only access to them.
func (c *Client) ListRedemptions(ctx context.Context, req *promocodepbv1pb.ListRedemptionsRequest, opts ...gax.CallOption) *RedemptionIterator {
	return c.internalClient.ListRedemptions(ctx, req, opts...)
}

// GetRedemption gets a single redemption by resource name.
func (c *Client) GetRedemption(ctx context.Context, req *promocodepbv1pb.GetRedemptionRequest, opts ...gax.CallOption) (*promocodepbv1pb.Redemption, error) {
	return c.internalClient.GetRedemption(ctx, req, opts...)
}

// gRPCClient is a client for interacting with FreeBusy API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type gRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing Client
	CallOptions **CallOptions

	// The gRPC API client.
	client promocodepbv1pb.PromoCodeServiceClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string

	logger *slog.Logger
}

// NewClient creates a new promo code service client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// PromoCodeService manages redeemable discount codes and validates them against
// a prospective booking. Redemption itself happens inside CreateBooking.
func NewClient(ctx context.Context, opts ...option.ClientOption) (*Client, error) {
	clientOpts := defaultGRPCClientOptions()
	if newClientHook != nil {
		hookOpts, err := newClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := Client{CallOptions: defaultCallOptions()}

	c := &gRPCClient{
		connPool:    connPool,
		client: promocodepbv1pb.NewPromoCodeServiceClient(connPool),
		CallOptions: &client.CallOptions,
		logger: internaloption.GetLogger(opts),

	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *gRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *gRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version, "pb", protoVersion)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. **Always** call Close() when
// the client is no longer required.
func (c *gRPCClient) Close() error {
	return c.connPool.Close()
}

func (c *gRPCClient) ListPromoCodes(ctx context.Context, req *promocodepbv1pb.ListPromoCodesRequest, opts ...gax.CallOption) *PromoCodeIterator {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).ListPromoCodes[0:len((*c.CallOptions).ListPromoCodes):len((*c.CallOptions).ListPromoCodes)], opts...)
	it := &PromoCodeIterator{}
	req = proto.CloneOf(req)
	it.InternalFetch = func(pageSize int, pageToken string) ([]*promocodepbv1pb.PromoCode, string, error) {
		resp := &promocodepbv1pb.ListPromoCodesResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			var err error
			resp, err = executeRPC(ctx, c.client.ListPromoCodes, req, settings.GRPC, c.logger, "ListPromoCodes")
			return err
		}, opts...)
		if err != nil {
			return nil, "", err
		}

		it.Response = resp
		return resp.GetPromoCodes(), resp.GetNextPageToken(), nil
	}
	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

func (c *gRPCClient) GetPromoCode(ctx context.Context, req *promocodepbv1pb.GetPromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).GetPromoCode[0:len((*c.CallOptions).GetPromoCode):len((*c.CallOptions).GetPromoCode)], opts...)
	var resp *promocodepbv1pb.PromoCode
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.client.GetPromoCode, req, settings.GRPC, c.logger, "GetPromoCode")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *gRPCClient) CreatePromoCode(ctx context.Context, req *promocodepbv1pb.CreatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).CreatePromoCode[0:len((*c.CallOptions).CreatePromoCode):len((*c.CallOptions).CreatePromoCode)], opts...)
	var resp *promocodepbv1pb.PromoCode
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.client.CreatePromoCode, req, settings.GRPC, c.logger, "CreatePromoCode")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *gRPCClient) UpdatePromoCode(ctx context.Context, req *promocodepbv1pb.UpdatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.PromoCode, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "promo_code.name", url.QueryEscape(req.GetPromoCode().GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).UpdatePromoCode[0:len((*c.CallOptions).UpdatePromoCode):len((*c.CallOptions).UpdatePromoCode)], opts...)
	var resp *promocodepbv1pb.PromoCode
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.client.UpdatePromoCode, req, settings.GRPC, c.logger, "UpdatePromoCode")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *gRPCClient) DeletePromoCode(ctx context.Context, req *promocodepbv1pb.DeletePromoCodeRequest, opts ...gax.CallOption) error {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).DeletePromoCode[0:len((*c.CallOptions).DeletePromoCode):len((*c.CallOptions).DeletePromoCode)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = executeRPC(ctx, c.client.DeletePromoCode, req, settings.GRPC, c.logger, "DeletePromoCode")
		return err
	}, opts...)
	return err
}

func (c *gRPCClient) ValidatePromoCode(ctx context.Context, req *promocodepbv1pb.ValidatePromoCodeRequest, opts ...gax.CallOption) (*promocodepbv1pb.ValidatePromoCodeResponse, error) {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).ValidatePromoCode[0:len((*c.CallOptions).ValidatePromoCode):len((*c.CallOptions).ValidatePromoCode)], opts...)
	var resp *promocodepbv1pb.ValidatePromoCodeResponse
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.client.ValidatePromoCode, req, settings.GRPC, c.logger, "ValidatePromoCode")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *gRPCClient) ListRedemptions(ctx context.Context, req *promocodepbv1pb.ListRedemptionsRequest, opts ...gax.CallOption) *RedemptionIterator {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "parent", url.QueryEscape(req.GetParent()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).ListRedemptions[0:len((*c.CallOptions).ListRedemptions):len((*c.CallOptions).ListRedemptions)], opts...)
	it := &RedemptionIterator{}
	req = proto.CloneOf(req)
	it.InternalFetch = func(pageSize int, pageToken string) ([]*promocodepbv1pb.Redemption, string, error) {
		resp := &promocodepbv1pb.ListRedemptionsResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			var err error
			resp, err = executeRPC(ctx, c.client.ListRedemptions, req, settings.GRPC, c.logger, "ListRedemptions")
			return err
		}, opts...)
		if err != nil {
			return nil, "", err
		}

		it.Response = resp
		return resp.GetRedemptions(), resp.GetNextPageToken(), nil
	}
	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

func (c *gRPCClient) GetRedemption(ctx context.Context, req *promocodepbv1pb.GetRedemptionRequest, opts ...gax.CallOption) (*promocodepbv1pb.Redemption, error) {
	hds := []string{"x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName()))}

	hds = append(c.xGoogHeaders, hds...)
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, hds...)
	opts = append((*c.CallOptions).GetRedemption[0:len((*c.CallOptions).GetRedemption):len((*c.CallOptions).GetRedemption)], opts...)
	var resp *promocodepbv1pb.Redemption
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = executeRPC(ctx, c.client.GetRedemption, req, settings.GRPC, c.logger, "GetRedemption")
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
