// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.4.1+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  syncstatusesql
//
// orm — https://github.com/the-protobuf-project/orm

package syncstatusesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// ChannelSyncStatuses is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type ChannelSyncStatuses struct {
	// FailedCount selects the "failedCount" field; nil when the column is NULL.
	FailedCount *int32 `graphql:"failedCount"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// LastError selects the "lastError" field; nil when the column is NULL.
	LastError *string `graphql:"lastError"`
	// LastSyncTime selects the "lastSyncTime" field; nil when the column is NULL.
	LastSyncTime *string `graphql:"lastSyncTime"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// PendingCount selects the "pendingCount" field; nil when the column is NULL.
	PendingCount *int32 `graphql:"pendingCount"`
	// State selects the "state" field; nil when the column is NULL.
	State *string `graphql:"state"`
}

// ChannelSyncStatusesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type ChannelSyncStatusesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// FailedCount selects the "failedCount" field.
	FailedCount struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"failedCount"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// LastError selects the "lastError" field.
	LastError struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"lastError"`
	// LastSyncTime selects the "lastSyncTime" field.
	LastSyncTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"lastSyncTime"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// PendingCount selects the "pendingCount" field.
	PendingCount struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"pendingCount"`
	// State selects the "state" field.
	State struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"state"`
}

// DeleteChannelSyncStatusesByIdResponse — Responses from the 'delete_channel_sync_statuses_by_id' procedure
type DeleteChannelSyncStatusesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// FailedCount selects the "failedCount" field; nil when the column is NULL.
		FailedCount *int32 `graphql:"failedCount"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LastError selects the "lastError" field; nil when the column is NULL.
		LastError *string `graphql:"lastError"`
		// LastSyncTime selects the "lastSyncTime" field; nil when the column is NULL.
		LastSyncTime *string `graphql:"lastSyncTime"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PendingCount selects the "pendingCount" field; nil when the column is NULL.
		PendingCount *int32 `graphql:"pendingCount"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
	} `graphql:"returning"`
}

// InsertChannelSyncStatusesResponse — Responses from the 'insert_channel_sync_statuses' procedure
type InsertChannelSyncStatusesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// FailedCount selects the "failedCount" field; nil when the column is NULL.
		FailedCount *int32 `graphql:"failedCount"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LastError selects the "lastError" field; nil when the column is NULL.
		LastError *string `graphql:"lastError"`
		// LastSyncTime selects the "lastSyncTime" field; nil when the column is NULL.
		LastSyncTime *string `graphql:"lastSyncTime"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PendingCount selects the "pendingCount" field; nil when the column is NULL.
		PendingCount *int32 `graphql:"pendingCount"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
	} `graphql:"returning"`
}

// UpdateChannelSyncStatusesByIdResponse — Responses from the 'update_channel_sync_statuses_by_id' procedure
type UpdateChannelSyncStatusesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// FailedCount selects the "failedCount" field; nil when the column is NULL.
		FailedCount *int32 `graphql:"failedCount"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LastError selects the "lastError" field; nil when the column is NULL.
		LastError *string `graphql:"lastError"`
		// LastSyncTime selects the "lastSyncTime" field; nil when the column is NULL.
		LastSyncTime *string `graphql:"lastSyncTime"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// PendingCount selects the "pendingCount" field; nil when the column is NULL.
		PendingCount *int32 `graphql:"pendingCount"`
		// State selects the "state" field; nil when the column is NULL.
		State *string `graphql:"state"`
	} `graphql:"returning"`
}
