// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm v1.3.3-0.20260711072739-f1c1e0fb6c74+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  syncstatusesql
//
// orm — https://github.com/the-protobuf-project/orm

package syncstatusesql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/channelql/schemaql"
)

// Model type aliases, re-exported from this resource's schema package.
type ChannelSyncStatuses = schemaql.ChannelSyncStatuses
type ChannelSyncStatusesAggExp = schemaql.ChannelSyncStatusesAggExp
type DeleteChannelSyncStatusesByIdResponse = schemaql.DeleteChannelSyncStatusesByIdResponse
type InsertChannelSyncStatusesResponse = schemaql.InsertChannelSyncStatusesResponse
type UpdateChannelSyncStatusesByIdResponse = schemaql.UpdateChannelSyncStatusesByIdResponse
